### ISSUE TITLE
denoteableType() broken for qualified types

### ISSUE THREAD

**Issue by gavinking** [ceylon/ceylon-spec#1016]
As originally reported in ceylon/ceylon-ide-eclipse#1011, `Unit.denoteableType()` doesn't do the right thing for qualified types where the qualifying type is non-denoteable.

**Comment by gavinking** [comment]
Closing, since this is already addressed by #865.

**Comment by lucaswerkmeister** [comment]
Looks like `denoteableType()` still emits `name` instead of `\Iname`… at least that’s what the IDE currently does (see ceylon/ceylon-ide-eclipse#1011).
