### ISSUE TITLE
Circular inheritance not detected for formal member classes

### ISSUE THREAD

**Issue by sgalles** [ceylon/ceylon-spec#1110]
```ceylon
interface Foo1{
    shared formal class Bar1() satisfies Foo2{}  
}

interface Foo2{
    shared formal class Bar2() satisfies Foo1{}  
} 
```
This compiles, but this should not be accepted by the type checker, right ?

**Comment by gavinking** [comment]
Um, actually I don't see anything particularly wrong with accepting this code. Sure, you can't actually implement either of these interfaces, AFAICT, but I don't see a strong need to reject this code. Nor does the spec say it should be rejected, at least not for any reason that I can see.

I'm closing this, unless you can think of something I'm missing.

**Comment by sgalles** [comment]
Man, I was going to anwser about this and I accidentally stumbled upon this one :
https://github.com/ceylon/ceylon-compiler/issues/2032

Now, as for this issue, I agree that it can be kept as is. There's a minor usuability issue related to quick fixes in the IDE though. 
I leave it to you :

Basically you can enter a *quick fix loop*. If you blindly apply the quick fix advised by the IDE, you end up with something like this :
```ceylon
void run(){
    object foo1 satisfies Foo1{
        shared actual class Bar1()
                 extends super.Bar1() {
            shared actual class Bar2()
                     extends super.Bar2() {
                shared actual class Bar1()
                         extends super.Bar1() {
                    shared actual class Bar2()
                             extends super.Bar2() {}
                    // and so on .... ans so on ...
            }   
            }
            
        }
    }
}
```

**Comment by gavinking** [comment]
Hahahaha thats the best IDE bug ever! I'm inclined to leave it in, just cos it's so much fun :) but I guess you should open an IDE issue :)

**Comment by sgalles** [comment]
Done
https://github.com/ceylon/ceylon-ide-eclipse/issues/1234

**Comment by gavinking** [comment]
Thanks :)
