### ISSUE TITLE
prevent code that depends on order of members of Java annotation

### ISSUE THREAD

**Issue by gavinking** [ceylon/ceylon-spec#1123]
We should disallow invocations of Java annotations that depend on the ordering of annotation members.

**Comment by gavinking** [comment]
@tombentley How can I detect that an annotation is a Java annotation?

**Comment by tombentley** [comment]
The annotation class is synthesized by the model loader and will have a name ending with `$Proxy`.

**Comment by gavinking** [comment]
@tombentley there is no way for me to get access to the actual annotation class from the model. Indeed, AFAICT, there is absolutely no way for the typechecker to distinguish a Java annotation. Moving to 1.2.

**Comment by gavinking** [comment]
Done, finally.
