### ISSUE TITLE
reified constructors

### ISSUE THREAD

**Issue by gavinking** [ceylon/ceylon-spec#1125]
While working on ~~#796~~, now #1129, it became clear that the simplest way to implement constructors in the typechecker was to treat a constructor as a sort of subtype of the class. I then have hacks to hide this from the actual programmer though it still kinda leaks through a bit in the IDE in the same way that `object` classes sometimes leak through.

This got me asking whether we should just embrace this and say that a constructor is a type! We've already proposed in ~~#796~~, now #1129, that we have singleton constructors that give as a streamlined syntax for Java-style enums, but if we also reified constructors, then this would be a bit more powerful. Of course we would have to somehow tag instances of a class with the constructor that produced the instance but that doesn't sound very hard. Then you could write stuff like:

```ceylon
    class Point {
        ...
        shared case origin { ... }
        shared new Polar(Float x, Float y) { ... }
        shared new Cartesian(Float r, Float theta) { ... }
    }

    ...

    switch (point)
    case (is Point.Polar) { ... }
    case (is Point.Cartesian) { ... }
    case (Point.origin) { ... }
```

Or whatever. Constructor refs like `Point.Polar` and `Point.Cartesian` would be legitimate types within the language.

Counterintuitively, this would _simplify_ the typechecker.

Thoughts?

**Comment by gavinking** [comment]
An interesting suggestion from @sadmac7000 is to let you pattern-match on the constructor within the initializer section:

```ceylon
class Point { 
    switch (this)
    case (is Cartesian(x,y)) { ..... } 
    case (is Polar(r,t)) { ... } 

    shared new Cartesian(Float x, Float y) { ... } 
    shared new Polar(Float r, Float t) { ... } 
}
```

**Comment by davidfestal** [comment]
I like this very much !

**Comment by sadmac7000** [comment]
That syntax is, at least in the example, redundant. My suggestion was that the switch at the top do /the same thing/ as the constructors at the bottom. I.e. that constructors /are/ just flow control within the class body.

**Comment by davidfestal** [comment]
but then where would the constructors be declared as types ?

**Comment by sadmac7000** [comment]
Same place.

To be clear, I prefer the second syntax.

**Comment by sadmac7000** [comment]
Let me put it this way: what I'm suggesting is that the following should compile:

```ceylon
class Foo {
	shared Integer a;
	shared Integer c;
	shared Integer b = 6;

	shared new Foo(Integer val) {
		a = val;
	}

	c = 3;
	shared Integer d = 5;
	shared Integer e;

	shared new Bar(Integer val) {
		a = val;
	}

	e = 24;
	shared Integer f = 7;
}
```

**Comment by gavinking** [comment]
@sadmac7000 Hrm, that would probably not be very hard to support, I suppose. Though the error messages are likely to be less helpful than they are with constructors today.

**Comment by gavinking** [comment]
@sadmac7000 In fact, that would be _very_ easy for the _typechecker_ to support. The problem is that it would be really quite difficult to implement for the Java backend! In the JVM, instance initializers always run after constructors, so you would need to package up bits of the initializer into methods that knew how to correctly delegate to each other, and I bet @tombentley would be upset.

**Comment by jvasileff** [comment]
Isn't the initialization code just completely duplicated in each Java constructor anyway?

But I still think it's worth looking into moving all of this into methods in order to support Swift-style freedom with `this` leakage.

**Comment by sadmac7000** [comment]
@gavinking just duplicate the outside-the-constructor-body code inside of each constructor.

**Comment by gavinking** [comment]
@jvasileff, oh, ooops, you're right, it is. I'll let @tombentley weigh in on this then.

> But I still think it's worth looking into moving all of this into methods in order to support Swift-style freedom with `this` leakage.

What, and throw exceptions at runtime when the code accesses an uninitialized attribute?!

**Comment by jvasileff** [comment]
Oh, no, definitely not. Only allow `this` to escape after initializing everything, but give every constructor a shot at that. I left a straw man impl around here somewhere, I'll try to find it. I did stop short of thinking/working through interop concerns.

**Comment by jvasileff** [comment]
Ok, it's at the end of #1149. I'm sure it needs some work, but at least in theory, Java's flexibility in allowing `this` to be leaked provides an opportunity to fix its upside down initialization scheme.

**Comment by tombentley** [comment]
I *guess* we could make this work by copying the bits from the initializer into each of the Java constructors (and that's indeed what we already do).

**Comment by gavinking** [comment]
@jvasileff I don't understand. How does Swift guarantee that the _subclass_ is fully initialized when the `this` reference leaks?

**Comment by gavinking** [comment]
Oh wait, I see: you can't initialize state after the call to `super.init()`.

**Comment by gavinking** [comment]
I mean, honestly, I don't really get the point of that. Initialization is supposed to initialize stuff. Constructors aren't supposed to have fucking side effects beyond allocation of an object! And they certainly can't compute and return any values other than the instance itself. So the code after `super.init()` is either (a) useless, or (b) doing stuff it shouldn't be doing.

So what the hell is the point of Swift's model? It's just essentially the exact same thing just backwards compared to other languages!

**Comment by sadmac7000** [comment]
We've been over this: there are classes for which mutual awareness is part of initialization. Tree nodes with a parent for example.

**Comment by gavinking** [comment]
I can't imagine how this design solves that. The parent in a tree node is not related t the child by inheritance.

**Comment by gavinking** [comment]
@sadmac7000 Oh wait, right I see your point.

**Comment by gavinking** [comment]
@sadmac7000 But the thing is that you guys have kinda gradually changed the topic here. What we've been discussing here in this issue simply doesn't do anything at all to address the problem of leakage of `this`, and nor do any of the code examples which have been proposed here.

Now, it's true that Swift's initialization model does appear to offer something in that area, and so perhaps I was too quick to dismiss it. However, the thing it offers doesn't appear to be easily mappable to the JVM. The thing you're talking about is the ability to have some initialization code that runs after both the subclass and superclass have fully initialized all their fields. But that _simply can't be implemented on the JVM_ unless you start polluting the instantiation site with stuff like:

```java
Foo foo = new Foo(args).postConstruct();
```

It is _not possible_ using the implementation techniques we've been discussing here!

**Comment by gavinking** [comment]
However, not that in the special case of a `final` class, we _can_ relax the restriction, but that is #806, not this issue.

**Comment by sadmac7000** [comment]
We are drifting off topic, I'll grant.

**Comment by gavinking** [comment]
Actually the discussion about leaking about post-construct and `this` belongs in #1149.

_This issue_ is about more freely mixing constructors with initializer code, and the two problems are quite distinct.

**Comment by gavinking** [comment]
Well, actually this issue was really originally about reifying constructor types. Actually I will open a separate issue for the question of relaxing the ordering rules on constructors.

**Comment by gavinking** [comment]
I have split the discussion about ordering into #1254.

**Comment by RossTate** [comment]
Going back to the original topic, if you're matching on which constructor was used to create the instance, aren't you just manually implementing dynamic dispatch?

**Comment by gavinking** [comment]
After dicussions in #1129, this proposal is now dead. We're not going to reify the types of constructors.

**Comment by davidfestal** [comment]
too bad : it would have been a cool way to implement pattern matching :-)
