### ISSUE TITLE
singleton constructors

### ISSUE THREAD

**Issue by gavinking** [ceylon/ceylon-spec#1129]
In #796 the notion of singleton constructors arose. That is, the ability of a class with constructors (i.e. without an initializer parameter list) to declare singleton instances whose bodies work like a constructor and initialize the state of the instance. For example:

```ceylon
class Point {
    shared Float x;
    shared Float y;
    shared new Point(Float x, Float y) {
        this.x = x;
        this.y = y;
    }
    shared case origin {
        x = 0.0;
        y = 0.0;
    }
}
```

A singleton instance reference would look like `Point.origin`. One motivation for this feature is that in conjunction with #1125 it would give us an alternative, streamlined way to do Java-style enums.

Issue: the interpretation as an enum value is what's motivating the use of `case` as the keyword here. Even though `case` doesn't feel quite perfect to me, `value` and `object` would both be ambiguous here, and `new` doesn't read right.

**Comment by gavinking** [comment]
Today I made a start on this and it's basically working. Missing things include:

1. Delegation to constructors e.g. `new origin extends Point(0.0,0.0) {}`
2. Restrictions around classes with explicit `of` clauses and singleton constructors.
3. Addition of a constructor makes singleton instances non-exhaustive.

I've done this in a way that should make it really very easy for the backend to start supporting (singleton instances are just nested `object`s.)

**Comment by jvasileff** [comment]
Java enums allow you to override methods (possibly abstract in the parent class), which I think is a pretty nice feature.

So it might be nice to allow `case`s to be defined outside of the body of the class, and extend it.

**Comment by gavinking** [comment]
@jvasileff we've been through this. Java's system overcompensates for the lack of first-class functions in the language (prior to Java 8). In Ceylon we can write the same thing using assignment:

```ceylon
class Foo {
    shared void accept();
    shared new New1() {
        accept() => noop();
    }
    shared new New2(void accept()) {
        this.accept = accept;
    }
}
```

Or, with a singleton constructor:

```ceylon
class Foo {
    shared void accept();
    shared new instance {
        accept() => noop();
    }
}
```

**Comment by gavinking** [comment]
> So it might be nice to allow `case`s to be defined outside of the body of the class, and extend it.

Note: we already have that possibility with what exists in Ceylon today. We don't need a second way to do it.

**Comment by gavinking** [comment]
Well, OK, fine, I admit it might be nice to let you write:

```ceylon
class Foo {
    void accept(Float x);
    shared new New() {
        void accept(Float x) {
            print(x);
        }
    }
}```

It's not overriding precisely, since `New` is not a subclass, it's just an alternative syntax for assignment. But it's quite regular. (Notice that `accept()` doesn't need to be `shared` for this.)

**Comment by jvasileff** [comment]
Ok, yes, those look like nice options.

**Comment by gavinking** [comment]
OK, I now have a much cleaner implementation of this in the `1129` branch. Basically, a singleton constructor is now represented in the model as a `Constructor` + a `Value`.

If anyone has time to work on backend support for this, go ahead, it should be straightforward, you just need to treat it like a regular `Constructor`, but in addition generating a `static` accessor for a singleton instance. Should be very easy to get it working.

For now, we don't need to support delegation to constructors.

**Comment by gavinking** [comment]
So this has worked out nicely, but there is one thing which bothers me a bit. Previously, with `of`, defining an enumerated type was a totally explicit thing. The client knew for sure that you intended for the list of things in the `of` clause to be exhaustive.

With what I have right now for singleton constructors that's not true. Perhaps I plan to add a new instance, or think I might. How do I indicate that clients?

One option would be to abuse `final` and allow `switch`es on the enumerated instances of a class explicitly marked `final`. That's not really precisely what `final` means, but it's quite close. In practice I think it would work out fairly well, but still, it makes me uncomfortable.

A second option would be to introduce an `enumerated` annotation for classes which can be `switch`ed. I don't like that this is so irregular compared to the current mechanism.

A third, much more regular option would be to make you use the `of` clause to list the constructors explicitly:

```ceylon
shared class Bool of true | false {
    shared new true {}
    shared new false {}
}
```

I think I prefer this since it makes the connection to what we already have today. It's just much more regular.

**Comment by gavinking** [comment]
Perhaps let you abbreviate it like this:

```ceylon
shared class Bool of ... {
    shared new true {}
    shared new false {}
}
```

Hurmph.

**Comment by lucaswerkmeister** [comment]
I like the third, explicit option (without the `...`, which look really weird).

**Comment by quintesse** [comment]
The last part seems unnecessary to me, it's isn't *that* much work to repeat the names.

**Comment by tombentley** [comment]
>  it's isn't *that* much work to repeat the names.

Well it depends how many there are and how long they are. Look at `ceylon.unicode::Directionality` for an example where the repetition would be annoying.

**Comment by quintesse** [comment]
> Look at ceylon.unicode::Directionality for an example where the repetition would be annoying.

Not sure, as I see it we are *already* repeating those names there right now as well and personally I don't find them annoying. And like @lucaswerkmeister I find the `of ..` option weird looking.

**Comment by gavinking** [comment]
Yes Tom is right I'm bothered by what ceylon.unicode looks like.

**Comment by quintesse** [comment]
Also to me the `of ...` option seems just like a cryptic version of the `enumerated` annotation.

**Comment by gavinking** [comment]
So the broader question is: how useful are singleton constructors outside of the context of defining enums?

If we were to say a class can have either singleton or parameterized constructors but not both, then I would be OK with dropping the need to make it explicit. Because I think in that case we can just position this as being for enums and nothing else.

But if you can mix singletons and constructors in the same class, which feels quite useful to me, then I feel like it needs to be explicit because singletons no longer carry the expectation that they are for enums and nothing else.

**Comment by quintesse** [comment]
And why exactly does the option of making the class `final` make you uncomfortable? It does seem like a simple solution.

**Comment by gavinking** [comment]
Well final doesn't mean it can't have parameterized constructors. And it doesn't, strictly speaking, mean I'm not going to add any new constructors.

**Comment by quintesse** [comment]
> Well final doesn't mean it can't have parameterized constructors

Sure, but I thought you found that useful so you wanted to keep that.

> And it doesn't, strictly speaking, mean I'm not going to add any new constructors.

Well... right. But I'm not confident that people will use `of` because they are sure they'll never ever cross-my-heart-hope-to-die add new items either. In many cases it will probably be added because you want nice switching behaviour.

**Comment by gavinking** [comment]
Right the point is that if you want to let your clients switch on your constructors, I want you to explicitly indicate that by doing something that you would not do for any other motivation.

Because people, and it doesn't matter what I think of this practice, _will_ start using this to just stick a list of values inside a wrapping namespace, without considering whether this is a closed list of values or not.

So I think it's gotta be explicit.

**Comment by FroMage** [comment]
Whatever syntax we add, remember to compare it against:

```java
public enum Foo {
 Bar, Gee;
}
```

And:

```java
public enum FamousNumbers {
 Answer(42), Beast(666);

 public final int number;

 FamousNumbers(int number){ this.number = number; }
}
```

For brevity. I know I _will_ compare them ;)

**Comment by quintesse** [comment]
> without considering whether this is a closed list of values or not.

Ok, so you want to make sure they know they're going to make a breaking change (with respect to backward compatibility). Well then I'd vote for being explicit without weird `of ...` shorthands.

**Comment by FroMage** [comment]
I mean, I'm not at all opposed to a new grammar for enum classes.

**Comment by gavinking** [comment]
Well I think we're doing that and that's what this discussion is about. But brevity is not the only value at play here.

**Comment by gavinking** [comment]
Well I am against that. For the two enum classes I write every year, I don't need a whole new keyword.

The only reason I'm even considering this whole idea really is that it offers the potential to make several things easier all at once. A specialised enum syntax would be crippled in the sense that it addresses just one problem and doesn't compose together with other language constructs the way this proposal does.

**Comment by gavinking** [comment]
And I'm not exaggerating here: in the past year I recall writing one enum in Java, that's 1 i.e. the additive identity. It was SiteVariance, FTR.

And for that I need a whole special language construct whose syntax I barely remember?

**Comment by FroMage** [comment]
It is well known that you never write enums yourself, but we do. We have more than twenty enums in the compiler alone, and would have a lot more if we weren't so damn lazy with calls like `foo(true, false, false, true)` where we have a really high threshold of switching to sanity.

**Comment by tombentley** [comment]
>  that's 1 i.e. the additive identity.

I think you mean the multiplicative identity, the additive identity is zero.

**Comment by FroMage** [comment]
Remember you're not designing a language just for yourself ;)

**Comment by gavinking** [comment]
Hahahah yes I do believe that's what I mean haha

**Comment by FroMage** [comment]
The problem is that Java's enums allow brevity, multiple constructors and anonymous subtyping. Brevity (even with multiple constructors) could be greatly improved using this syntax (provided we can _get_ at the case values from outside, which is not obvious):

```ceylon
class FamousNumbers(shared Integer number)
 of beast(666) | answer(42) {}

class UsesConstructors
 of first(1) | second(34, 12) {
 shared Integer prop;
 new Foo(Integer x){
  prop = x;
 }
 new Bar(Integer x, Integer y){
  prop = x * y;
 }
}
```

As for anonymous subtyping (which I frequently do in enums), we _could_ do it like this too:

```ceylon
class FamousNumbers(shared Integer number)
 of answer(42) 
  | beast(666) { bow() => throw Exception("I bow to no one"); }  
{
 shared default bow(){
  print("I am number ``number``);
 }
}
```

It isn't pretty, but it works, and is even less verbose than Java's equivalent:

```java
public enum FamousNumbers {
 Answer(42),
 Beast(666) { 
  @Override
  public void bow() {
   throw new Exception("I bow to no one");
  }
 };
public final int number;
FamousNumbers(int number) { this.number = number; }
public void bow(){
  System.err.println("I am number "+number);
 }
}
```

**Comment by FroMage** [comment]
And if we're worried that the case values would default to `shared` (because that's the most useful thing to have) when it's not explicit (and so we can't turn it off) we could make `enum` be an annotation for the class that just means "make case values be shared by default", so we can turn it off by leaving the `enum` annotation out.

**Comment by gavinking** [comment]
So I think a reasonable solution might be to let you abbreviate the common case where the values don't have any interesting initialisation logic:


```ceylon
class Bool of true | false {}
```

This isn't ambiguous at all, it can't be confused with anything we have today.

Then, if one of your enumerated cases needs dedicated init logic, you add a singleton constructor with that name.

**Comment by FroMage** [comment]
Can you give me the current proposal's equivalent to the examples I posted (taken straight off the compiler code, though simplified. they are not hand-waving but real use-cases)? It's a bit hard to judge the current proposal without samples…

**Comment by gavinking** [comment]
Wait, wat, this is just a dog's breakfast:

> ```ceylon
class UsesConstructors
    of first(1) | second(34, 12) {
  shared Integer prop;
  new Foo(Integer x){
    prop = x;
  }
  new Bar(Integer x, Integer y){
    prop = x * y;
  }
}
```

So `first(1)`, what is that&mdash;looks like a function call, where is the function named `first()`. Hrm, can't find it. Oooh OK, it's a _constructor invocation_ ... but, which constructor, I have `Foo` and `Bar` here, oh, wait, you're matching argument lists to constructors _based on the arity of the parameter list_?! What happens if that's ambiguous?

Nononononono. What I am proposing lets me write:

```ceylon
class UsesConstructors
      of first | second {
  shared Integer prop;
  shared new first {
    prop = 1;
  }
  shared new second {
    prop = 34*12;
  }
}
```

That's _clearly_ much cleaner.

Now the second example, given as:

> ```ceylon
class FamousNumbers
      (shared Integer number)
    of answer(42) 
      | beast(666) { 
        bow() => throw Exception("I bow to no one"); 
      }  
{
  shared default void bow() {
     print("I am number");
  }
}
```

(Note I had to reformat this over a bunch more lines to even begin to make sense of this.)

Well there's several problems with this:

1. The syntax is ambiguous, we don't know whether `{` is the start of the class or the start of a case.
2. It seems to break definite initialization checking since it refers to `bow()` before `bow()` is defined.

OTOH, with the current proposal, it could look like something like this:

```ceylon
class FamousNumbers
    of answer | beast
{
  shared Integer number;
  shared void bow();
  shared new answer { 
    number=42; 
    bow() => print("I am number");
  }
  shared new beast {
    number = 666;
    bow = () { throw Exception("I bow to no one"); }
  }
}
```

There's absolutely no debate in my mind about which of these is cleaner, more readable, more easy to format, and keeps implementation and API more separate.

**Comment by gavinking** [comment]
By the way, @FroMage one comparison you can just take home right now is the comparison to Java `enum`s, which is totally inapt, _since they are not exhaustive_. The following _does not compile_:

```java
String toString(SiteVariance var) {
    switch (var) {
    case IN: return "out" 
    case OUT: return "out";
    case NONE: return "";
    }
}
```

I am forced to write:

```java
String toString(SiteVariance var) {
    switch (var) {
    case IN: return "out" 
    case OUT: return "out";
    case NONE: return "";
    default: throw Error("the universe is about to end!");
    }
}
```

So to compare my proposal, _fairly_ to Java, you have a class with no `of` clause and just:

```ceylon
class SiteVariance {
    shared new in {}
    shared new out {}
    shared new none {}
}
```

**Comment by FroMage** [comment]
Except you're conveniently skipping over the issue of constructor reuse. What if I have more values that need the same constructors?

**Comment by lucaswerkmeister** [comment]
(for future reference, and the benefit of others interested in this issue: the discussion has for some reason moved – temporarily? permanently? who knows – [to Gitter](https://gitter.im/ceylon/user?at=556c6eca463d0c7c066d9820))

**Comment by gavinking** [comment]
> Except you're conveniently skipping over the issue of constructor reuse. What if I have more values that need the same constructors?

Then write a partial constructor and delegate to it. That was part of the original proposal that you apparently didn't bother to read.

**Comment by gavinking** [comment]
So by thinking through the usecases for Java-style enums I've concluded that the distinction between "open-ended" enums, which all Java `enum`s are, implicitly, and "closed-ended" enums, which let you exhaustively `switch` over, is a real one. Consider a list of error types, for example. That's almost certainly an open-ended enum. But people want to be able to write `Error.missingClosingParen` or whatever.

I'm honestly not sure about the case of `Directionality` in `ceylon.unicode`, is that exhaustive or not? I'm a bit suspicious that any enum with that many cases can _possibly_ be exhaustive&mdash;especially when one of its cases is the rather suspicious looking "undefined"&mdash;but given that this is defined by a spec that changes slowly, I guess we could treat it that way.

So, assuming that we _do_ need it to be closed-ended, what would this look like using singleton constructors?

```ceylon
"Enumerates the *Directionalities* defined by the Unicode 
 specification."
shared class Directionality
        of arabicNumber 
        | boundaryNeutral
        | commonNumberSeparator
        | europeanNumber
        | europeanNumberSeparator
        | europeanNumberTerminator
        | leftToRight
        | leftToRightEmbedding
        | leftToRightOverride
        | nonspacingMark
        | otherNeutrals
        | paragraphSeparator
        | popDirectionalFormat
        | rightToLeft
        | rightToLeftArabic
        | rightToLeftEmbedding
        | rightToLeftOverride
        | segmentSeparator
        | undefined
        | whitespace {
    
    "The two character code assigned to this directionality 
     by the Unicode specification."
    shared String code;
    
    shared new arabicNumber { code=>"AN"; }
    shared new boundaryNeutral { code=>"BN"; }
    shared new commonNumberSeparator { code=>"CS"; }
    shared new europeanNumber { code=>"EN"; }
    shared new europeanNumberSeparator { code=>"ES"; }
    shared new europeanNumberTerminator { code=>"ET"; }
    shared new leftToRight { code=>"L"; }
    shared new leftToRightEmbedding { code=>"LRE"; }
    shared new leftToRightOverride { code=>"LRO"; }
    shared new nonspacingMark { code=>"NSM"; }
    shared new otherNeutrals { code=>"ON"; }
    shared new paragraphSeparator { code=>"B"; }
    shared new popDirectionalFormat { code=>"PDF"; }
    shared new rightToLeft { code=>"R"; }
    shared new rightToLeftArabic { code=>"AL"; }
    shared new rightToLeftEmbedding { code=>"RLE"; }
    shared new rightToLeftOverride { code=>"RLO"; }
    shared new segmentSeparator { code=>"S"; }
    shared new undefined { code=>""; }
    shared new whitespace { code=>"WS"; }
    
}
```

Is that perfect? Perhaps not. Is it better than what we have today? Well, yes, I think it's clear that it's somewhat cleaner. 

OTOH, if we don't think we need to make this closed-ended, which is the fair comparison to Java `enum`s, we would have just this:

```ceylon
"Enumerates the *Directionalities* defined by the Unicode 
 specification."
shared class Directionality {
    
    "The two character code assigned to this directionality 
     by the Unicode specification."
    shared String code;
    
    shared new arabicNumber { code=>"AN"; }
    shared new boundaryNeutral { code=>"BN"; }
    shared new commonNumberSeparator { code=>"CS"; }
    shared new europeanNumber { code=>"EN"; }
    shared new europeanNumberSeparator { code=>"ES"; }
    shared new europeanNumberTerminator { code=>"ET"; }
    shared new leftToRight { code=>"L"; }
    shared new leftToRightEmbedding { code=>"LRE"; }
    shared new leftToRightOverride { code=>"LRO"; }
    shared new nonspacingMark { code=>"NSM"; }
    shared new otherNeutrals { code=>"ON"; }
    shared new paragraphSeparator { code=>"B"; }
    shared new popDirectionalFormat { code=>"PDF"; }
    shared new rightToLeft { code=>"R"; }
    shared new rightToLeftArabic { code=>"AL"; }
    shared new rightToLeftEmbedding { code=>"RLE"; }
    shared new rightToLeftOverride { code=>"RLO"; }
    shared new segmentSeparator { code=>"S"; }
    shared new undefined { code=>""; }
    shared new whitespace { code=>"WS"; }
    
}
```

**Comment by gavinking** [comment]
Well one solution to this quandary would be to use a different keyword to declare the singleton constructors when they represent enumerated cases. We would keep using `new` when it's an "open-ended" enumeration, and use `of` when it's "closed":

```ceylon
"Enumerates the *Directionalities* defined by the Unicode 
 specification."
shared class Directionality {
    
    "The two character code assigned to this directionality 
     by the Unicode specification."
    shared String code;
    
    of arabicNumber { code=>"AN"; }
    of boundaryNeutral { code=>"BN"; }
    of commonNumberSeparator { code=>"CS"; }
    of europeanNumber { code=>"EN"; }
    of europeanNumberSeparator { code=>"ES"; }
    of europeanNumberTerminator { code=>"ET"; }
    of leftToRight { code=>"L"; }
    of leftToRightEmbedding { code=>"LRE"; }
    of leftToRightOverride { code=>"LRO"; }
    of nonspacingMark { code=>"NSM"; }
    of otherNeutrals { code=>"ON"; }
    of paragraphSeparator { code=>"B"; }
    of popDirectionalFormat { code=>"PDF"; }
    of rightToLeft { code=>"R"; }
    of rightToLeftArabic { code=>"AL"; }
    of rightToLeftEmbedding { code=>"RLE"; }
    of rightToLeftOverride { code=>"RLO"; }
    of segmentSeparator { code=>"S"; }
    of undefined { code=>""; }
    of whitespace { code=>"WS"; }
    
}
```

That's not bad at all.

**Comment by gavinking** [comment]
So perhaps what we could say is that:

```ceylon
class Bool {
    of false {}
    of true {}
}
```

Would be an abbreviation for:

```ceylon
class Bool 
       of false | true
       satisfies Enumerated {
    shared actual String string;
    shared actual Integer integer;
    shared new false { string=>"false"; integer=0; }
    shared new true { string=>"true"; integer=1; }
}
```

Thus member `of`s would just be a syntax sugar to cut down on the boilerplate.

None of that would conflict with what is proposed in #1125. We could still support this in future:

```ceylon
class Point {
    ...
    of origin { ... }
    of Polar(Float x, Float y) { ... }
    of Cartesian(Float r, Float theta) { ... }
}
```

**Comment by gavinking** [comment]
Hell, if this is just an abbreviation, I suppose we could even make the `enumerated` annotation have that effect.

```ceylon
enumerated class Bool {
    new false {}
    new true {}
}
```

**Comment by jvasileff** [comment]
Can the case types be made denotable to do things like work with [type safe subsets](https://github.com/ceylon/ceylon-sdk/blob/master/source/ceylon/interop/java/JavaComparator.ceylon#L17)?

**Comment by gavinking** [comment]
@jvasileff perhaps in conjunction with #1125.

**Comment by gavinking** [comment]
So the more I think about it, the more I'm inclined to think that an `enumerated` annotation does almost no work. It _is_ quite analogous to `final`, in fact, much more than I thought at first, in the sense that having that annotation there lets the client do some stuff that they would not otherwise be allowed to. (In the case of `final`, types become disjoint, in the case of `enumerated`, types become exhaustive.)

_But_ there is a big difference which shows why `enumerated` is pretty lame. If I "break" `final`ity, and attempt to add a new subclass, the compiler forces me to remove the `final` annotation, thus unambiguously telling me that I've made a significant breaking change. But if I "break" clients of an `enumerated` class, by adding a new constructor, the compiler does not complain until I try to recompile clients.

An `of` clause list is quite different: if I add a new subtype of the enumerated class, I have to go back to the enumerated class and explicitly add that subtype to the list.

So I'm kinda left torn between two options:

1. Just treat every `switch` as exhaustive if it covers all constructors. If you want to prevent clients from `switching` on your class, because you think you might add new constructors, add a private constructor. In practice there's really no way to be sure that an enumerated type won't add new cases in the future. The future is unknowable.
2. Require the explicit `of` list, even though it's really unDRY.

I lean toward option 1. The original design before I had a crisis of confidence yesterday.

**Comment by gavinking** [comment]
P.S. Who else here prefers `of` to `new` for defining singleton constructors?

**Comment by tombentley** [comment]
> P.S. Who else here prefers `of` instead of `new` for defining singleton constructors?

I did quite like that, actually.

**Comment by gavinking** [comment]
No, wait, the [above reasoning](https://github.com/ceylon/ceylon-spec/issues/1129#issuecomment-107931634) just can't be correct. People add new constructors for convenience to classes _all the time_, without wanting to bother themselves with the possibility that this is a change that breaks clients. We make constructors far less useful if we make it problematic to add new constructors.

P.S. There's also an issue with delegation here, but I think that's solvable by saying that:

1. constructor aliases #1130 aren't reified, so don't need to be treated as cases,
2. partial constructors #1212 also aren't reified, so aren't treated as case, and
3. all other constructors are reified as individual cases.

So I'm pretty much back to where I was yesterday:

1. an explicit `of` list for enumerated classes,
2. use `of` instead of `new` when writing the constructors of an enumerated class, or
3. kick the can down the road on the issue of exhaustive `switch`es and just require you to write an `else` clause when switching on constructors.

**Comment by quintesse** [comment]
I'm still in favor of `#1` , I like it being explicit, I like that you'll be forced to think about it a bit more when you want an exhaustive switch and I don't mind at all that you have to repeat the name, not even when there's 2 dozen of them.

**Comment by davidfestal** [comment]
I also like the option 2 ( use `of` instead of `new` ...), but then will the `Tree.TypeDeclaration` have its `caseTypes` set to the list of constructors (like I assume it would be with option 1) ?

**Comment by gavinking** [comment]
So I just chatted this over with @tombentley and we went back to basics. Where did this come from?

Well, it came from wanting to have a constructor with no parameters, _that always returns the same object_. That feels useful to everyone, I think. And it isn't a source of any deep philosophical debate.

Then, I realized that we can switch on such constructors. Since value references like `Bool.true` and `Bool.false` are guaranteed to be disjoint, unlike regular value references, we can use them in a _value_ `case`. (Not a _type_ `case`, mind you.) This is analogous to switching on literal values of `String` or `Integer`, which we already support.

But _then_, says @tombentley:

> But you added the reification/subclass idea 
> And that's where it seems to get messy

True. I started adding what is effectively a whole "shadow" system of subclassing underneath _constructors_. And started duplicating functionality we already have with enumerated subclasses, and _of course_ started to run into philosophical crises when the two systems didn't quite meet up in the middle. Worse, I then started trying to repurpose it all to satisfy @FroMage's complaints about verbosity of writing Java-style enums, and that's really where I ran into problems, because it turns out that what he wants is something that can only be satisfied by a totally special-purpose syntax sugary thing and there was no way that I can make him happy starting from where I'm starting.

So let's simply drop those additional grown-on goals, and consider them nongoals, or at least unattainable goals. Then we're left with the ability to write singleton constructors, and use them as value cases. There's not, I don't think, anything very debatable about that. We gain the ability to do something with user-written classes that we can already do with built-in classes, and we don't break anything.

Finally, the only open question in this is: given that I have a class with only singleton constructors, should we _let_ you list them in the `of` clause to get an exhaustive value (not type) `switch`. This would not be any kind of attempt to address concerns about verbosity of Java-style enums! Nor would it be any kind of attempt to compete with our current system of enumerated types, nor will it evolve into one. It would just be reusing a syntactic construct we already have in the language to do something completely unharmful.

Tom says we don't need it. Tako says he likes it. I'm a bit ambivalent, but since it's what I've already implemented and is sitting on the 1129 branch, and simply doesn't require any extra work AFAICT, I'm probably inclined to support it. It seems like a useful thing, even if it doesn't help achieve any of the dropped unattainable goals.

Any objections?

**Comment by quintesse** [comment]
Well to be honest I'm not sure what's left of the proposal? What's the final syntax exactly? What can we do and what can't we do? (especially given @FroMage 's examples)

**Comment by gavinking** [comment]
@quintesse You can write:

```ceylon
class Bool {
    shared actual String string;
    shared new true { string=>"true"; }
    shared new false { string=>"false"; }
}
```

And then do:

```ceylon
Bool bool = Bool.true;
switch (bool)
case (Bool.true) { ... }
case (Bool.false) { ... }
else {}
```

Probably, you can also write:

```ceylon
class Bool of true | false {
    shared actual String string;
    shared new true { string=>"true"; }
    shared new false { string=>"false"; }
}
```

And then do:

```ceylon
Bool bool = Bool.true;
switch (bool)
case (Bool.true) { ... }
case (Bool.false) { ... }
```

> especially given @FroMage 's examples

As stated above, what is proposed here does not purport to address Stef's examples because he has made clear that it's impossible to address his concerns within this framework. Therefore they've been classified "nongoals".

**Comment by gavinking** [comment]
To be clear, you can also write:

```ceylon
class Point {
    shared Float x;
    shared Float y;
    shared new Point(Float x, Float y) {
        this.x = x;
        this.y = y;
    }
    shared case origin {
        x = 0.0;
        y = 0.0;
    }
}
```

In this case, you can't have an `of` clause. You can still match against `origin` in a `switch`, but that's inexhaustive, of course.

**Comment by jvasileff** [comment]
@gavinking I have to say that without a clear path to having a separate type for each singleton, I'm not a fan of this feature.

1. When writing an enum, I'm given the frustrating choice between a streamlined syntax and encapsulating namespace vs. typed values.
2. When using someone else's enum, I have to live with whatever decision they made.

This wouldn't be a concern for a language without union types. But for Ceylon, I think the lack of "type granularity" comes up short.

**Comment by tombentley** [comment]
Two fairly random observations:

1. In a `switch` match cases against singleton instances are done using identity (i.e. java `==`) not equality. But continuing using your `Point` example, and assuming it refined `equals()` in the obvious way that would mean `switch(Point(0,0))` would not match `case(origin)`, which would be pretty confusing, imo. It has to be that way in order to preserve the disjointness of cases, but I can imagine people finding that confusing. Obviously it's only a problem for classes with non-singleton constructors.

2. I assume that initialization of singleton's of member classes is lazy, i.e. given

```ceylon
class ClassMemberSingletonCtors() {
    shared class MemberClass {
        shared actual String string;
        shared new one {
            string="one";
        }
    }
}
```

we would  only instantiate `one` when it was first accessed from its containing `ClassMemberSingletonCtors` instance. I think that semantic is perfectly fine, but implementation-wise it does require a field (in ClassMemberSingletonCtors) per member class singleton constructor, which is not obvious.

**Comment by tombentley** [comment]
And another thing, I think @gavinking's tc changes broke interop support for java enums. Was that accidental @gavinking, or do I need to fix it?

**Comment by gavinking** [comment]
@tombentley Well that's a situation that already exists today:

```ceylon
object xxx {
    equals(Object that) => true;
}
object yyy {
    equals(Object that) => false;
}

\Ixxx|\Iyyy objs = ... ;
switch(objs)
case (yyy) {}
case (xxx) {}
```

The typechecker accepts that.

**Comment by gavinking** [comment]
> Was that accidental @gavinking, or do I need to fix it?

Well, surely, but how? What did I do and what broke?

**Comment by tombentley** [comment]
@gavinking when I have a member class with singleton constructors in an interface... isn't that equivalent to the interface having state?

**Comment by gavinking** [comment]
Um. Well we disallow `object` declarations in the body of an `interface` so I guess we should do the same thing.

**Comment by gavinking** [comment]
We need to decide what is the metatype of these things. Perhaps they could just be `Value`s for now? WDYT, @tombentley?

**Comment by gavinking** [comment]
Note that if they're just `Value`s, that would mean you can't put constructor annotations on them. But I guess I doubt that would be a problem.

**Comment by tombentley** [comment]
Well, I was sold a singleton *constructor*, so I might have to take it back to the shop... I guess they are "more like" values though, from a metamodel POV (you're not going to have to or be able to invoke them, and you're likely to just want the value). In fact I can't think of a reason why we'd need to know about their constructor nature at all (well, I guess we'd need some predicate on `Value` to know it *was* a constructor).

**Comment by gavinking** [comment]
Right, that's my thinking.

**Comment by gavinking** [comment]
TODO:

- [ ] non-`Identifiable` classes can't have singletons in the `of` clause
- [ ] check that the `of` actually covers all the constructors!

**Comment by gavinking** [comment]
This is done now, at least from the typechecker side. I still need to write a spec for it.

**Comment by gavinking** [comment]
TODO: static references! In this code:

```ceylon
class Outer() {
    shared class Inner {
        shared String name => "Gavin";
        shared new instance {}
        shared new New() {}
    }
}

value i = Outer.Inner.instance;
``

The value `i` should have the type `Outer.Inner(Outer)`.

**Comment by gavinking** [comment]
This is now done, and ready to merge!

**Comment by gavinking** [comment]
Oh, wait, no, I still have to spec the `of` clause stuff, and `switch`ing.

**Comment by gavinking** [comment]
_Now_ done :-)

**Comment by jvasileff** [comment]
Surely using https://github.com/ceylon/ceylon-spec/issues/899 as a starting point for this and https://github.com/ceylon/ceylon-spec/issues/1344 must have been considered. But there are no examples for that. So I'm going to add a couple:

```ceylon
class Point {
    shared static object origin
            extends Private(0.0, 0.0) {}

    shared static Point point(Float x, Float y) {
        if (x==0.0 && y==0.0) {
            return origin;
        }
        else {
            return Private(x, y);
        }
    }

    shared Float x;
    shared Float y;
    new Private(Float x, Float y) {
        this.x = x;
        this.y = y;
    }
}
```
and
```ceylon
interface Boolean of true | false {
    shared static object true satisfies Boolean {}
    shared static object false satisfies Boolean {}
}
```

Clearly this offers more power/flexibility for case declarations, and it avoids inventing a new pseudo type.

I guess the downside would be perceived ugliness of extending a type within its own declaration. But that *is* something that is allowed today.

**Comment by gavinking** [comment]
This is now done.

**Comment by sgalles** [comment]
@gavinking you asked for some feedback about value constructors. Here is mine.
Actually I won't talk about the `object`s VS value constructor overlap, as it seems that you found a way out. Cool. 
Actually I wanted to say that I really like value constructors because I'm huge fan of Java enums (I know, I know, nobody's perfect ;) ) and I will use value constructors in Ceylon.
And even though I can't use method overriding I can still do things like this and it's enough for me
```ceylon
shared class Foo of foo|bar|baz{
	shared Integer() fun;
	abstract new default(){
		fun = ()=>0;
	}
	shared new foo extends default(){}
	shared new bar extends default(){}
	shared new baz{
		fun = ()=>42;
	}
}
```
Now it's almost a detail here : but I'd like to talk about the `enumeration` annotation.

I must say that I would find it useful as syntaxic sugar for the `of foo|bar|baz` expression.
Now, I know that it was already discussed, and it was killed because it would be *too dangerous* for depending modules. Problem is, IMHO your comparaison of `enumeration` VS `final` is not fair I think.

you compared 
*I add a new subclass of a final class in a module and the compiler warns me*
VS
*I add a new value constructor in an enumeration and the compiler does not warn me*

Problem is, you didn't modify the constraint that affect the client for `final`, but you did change the constraint for the value constructor.

I think it should be instead :
*I add a `final` annotation to an existing class and the compiler does not warn me*
VS
*I add a new value constructor in an enumeration and the compiler does not warn me*

I mean in both cases I will get a runtime error in a client module. In that sense, I do think that the `enumeration` annotation is not less safe than `final`. 

Plus, I don't think that to have to duplicate the information in the `of` clause makes this safer. 
uhm...Do you really *type* you email adresse twice in the forms that request you address twice, or do you just copy and paste grumbling....;)
Even in Java *I know*  that I can break a client that rely on my enum when I add a new entry. We all know that 
Just my two cents, but I believe that's a pity if this simple sugar is not added because of this reason only (but maybe other reasons were discussed, sorry if I'm missing something here)

**Comment by gavinking** [comment]
@sgalles OK thanks. FTR I'm much more comfortable with this stuff now I discovered the natural relationship between value constructors and `object`s.

(Give me a chance to think about and respond to the point about `enumerated` later.)
