### ISSUE TITLE
Code with missing parameter inference is accepted

### ISSUE THREAD

**Issue by sgalles** [ceylon/ceylon-spec#1176]
This code is accepted by the typechecker and craches both backends
```ceylon
void foo<Bar>(void func(Bar b)){} 
foo(void(b){});
```
I guess it should be rejected.

**Comment by gavinking** [comment]
@sgalles I have improved the error message. I hope you're finally happy! ;-)

**Comment by sgalles** [comment]
I'm filled with joy ! :) Thanks, that's helpful.
