### ISSUE TITLE
Attribute initialized twice by two constructors

### ISSUE THREAD

**Issue by sgalles** [ceylon/ceylon-spec#1189]
I guess that this should not compile (currently it compiles)
```ceylon
class Foo { 
    shared Integer i;
    shared new Foo(){
        i = 42;
    }
    shared new Bar(){
        Foo();
        i = 43;
    }
}
```

**Comment by gavinking** [comment]
This is perfectly correct. Your call to `Foo()` simply instantiates a different `Foo`, it does not delegate to the other constructor.

**Comment by sgalles** [comment]
Oh...Of course, yes. Thanks.
