### ISSUE TITLE
Type identifier of class w/o default constructor accepted as instance of that type

### ISSUE THREAD

**Issue by sgalles** [ceylon/ceylon-spec#1191]
If I'm not mistaken this should be rejected by the typechecker (and is currently accepted)
```ceylon
class Foo{ shared new Bar(){} }
Foo f = Foo;
```
FTR it blows up the Java backend, and blows up the JS runtime

**Comment by gavinking** [comment]
Thanks, @sgalles, _finally_ fixed.
