### ISSUE TITLE
StackOverflowError for broken `satisfies`+ default constructor declaration

### ISSUE THREAD

**Issue by sgalles** [ceylon/ceylon-spec#1193]
OK, this is an edge case. This broken code
```ceylon
    class Bar satisfies Bar{
        shared new Bar() {}  
    }
```
causes a StackOverflowError (CLI or IDE)

**Comment by gavinking** [comment]
Thanks, fixed.

**Comment by akberc** [comment]
Fixed, thanks.  However, I am now thoroughly confused about the namespace rules.  Apologies if I have missed them elsewhere, but don't seem to be intuitive.

Now, with a constructor of the same name as the satisfied interface of the class, there is the error:
``` 
Inheritance is circular: definition of Cosmo is recursive, involving Another, Cosmo
```
There are a few questions:
1. Is a constructor a part of type inheritance hierarchy?
2. Why would the typechecker not distinguish between `Another` and `Cosmo.Another`?
3. Testing further, a 'regular' inner type of the same name as the satisfied interface, I get the really stupefying error:
```ceylon
shared interface Another {}

shared class Cosmo() satisfies Another {
    shared interface Another {
    }
}
```
```
Qualifying type Cosmo of supertype Cosmo.Another is not an outer type or supertype of any outer type of Cosmo
```

Now, this may not be so uncommon in the business world. Similar to the example I cited for constructors - https://github.com/ceylon/ceylon-spec/issues/796#issuecomment-33912173

the following may be entirely plausible:
```
interface Order
class PurchaseOrder satisfies Order
-- constructor Requisition
-- constructor Order
```
resulting in being instantiated as `PurchaseOrder.Order`

**Comment by gavinking** [comment]
@akberc The `extends` clause of a class occurs within the namespace of the class itself, so a member of the class will hide any toplevel declaration with the same name.

What we need to do is let you write:

```ceylon
shared interface Another {}

shared class Cosmo() satisfies package.Another {
    shared interface Another {
    }
}
```

But that's not currently supported.

**Comment by gavinking** [comment]
Workaround: use an alias:

```ceylon
import pack { A=Another }

shared interface Another {}

shared class Cosmo() satisfies A {
    shared interface Another {
    }
}
```
