### ISSUE TITLE
Ambiguous member declaration when importing toplevel object member

### ISSUE THREAD

**Issue by tombentley** [ceylon/ceylon-spec#1197]
As mentioned in https://github.com/ceylon/ceylon-compiler/issues/1941#issuecomment-70098132, if I have a toplevel object which itself has a member object

    shared object toplevel {
        shared object inner {
        }
    }

and then I try to import the inner member:

    import pkg{toplevel{inner}}

I get a typechecker error about an ambiguous member declaration 'inner' of 'toplevel'.

**Comment by gavinking** [comment]
Fixed.
