### ISSUE TITLE
Non-matching destructuring accepted

### ISSUE THREAD

**Issue by sgalles** [ceylon/ceylon-spec#1201]
This should be rejected by the typechecker
```ceylon
shared void run(){
   value [a,b,*c] = [1]; 
}
```

**Comment by gavinking** [comment]
Fixed, thanks again!

**Comment by lucaswerkmeister** [comment]
I feel like
```ceylon
value [a, *e] = [1];
value [*e] = [];
```
should be allowed (with `e` being `Empty`), in analogy to `[1, *[]]` being allowed. (I. e. `value [a, *e] = [1, *[]];` is totally symmetric.)

**Comment by gavinking** [comment]
@lucaswerkmeister Well, I wondered that, but it's not actually _useful_, and would make the spec more complicated...

**Comment by lucaswerkmeister** [comment]
Okay, sure.
