### ISSUE TITLE
Irrelevant type parameter required when referencing static method

### ISSUE THREAD

**Issue by jvasileff** [ceylon/ceylon-spec#1207]
With a generic Java class and static method:

```java
public class GSJava<T> {
    public static void foo() {}
}
```

an error occurs when referencing the static method when qualified by the class without specifying a type parameter:

```ceylon
import com.my.package {
    GSJava { fooImported = foo }
}

shared void bar() {
    GSJava.foo(); // error on "GSJava"
    // missing type arguments to generic declaration: 'GSJava' declares type parameters 'T'

    GSJava<Nothing>.foo(); // works

    fooImported(); // works
}
```

**Comment by gavinking** [comment]
@jvasileff convince me I care.

Note that this _only_ arises for static methods of Java generic classes. I don't think they are common.

**Comment by jvasileff** [comment]
Ha! I thought that might be your reaction.

This will come up for anyone attempting to use a static factory method to create an instance of a container class, which I don't think is that *that* uncommon in Java. In fact, Joshua Bloch recommends the technique in Effective Java as a means to work around Java's poor type inference:

>A fourth advantage of static factory methods is that they reduce the verbosity
of creating parameterized type instances.
...
This is known as type inference. For example, suppose that HashMap provided
this generic static factory (Item 27):
`public static <K, V> HashMap<K, V> newInstance() {`


The issue can be particularly confusing since *both* the class and the factory method will likely be generic, so the error may be mistaken for failed type inference. I felt "lucky" to notice that the IDE underlined just the class in red, which led me to the correct conclusion fairly quickly, but I could also imagine struggling with this for a while.

And, of the two workarounds, one is ugly and the other is inconvenient.

A specific use case is Guava's [ImmutableList](http://docs.guava-libraries.googlecode.com/git/javadoc/com/google/common/collect/ImmutableList.html) where you might write:

```ceylon
value x = ImmutableList<Nothing>.\iof<String>("a", "b", "c");
```

Obviously the second type parameter will often be left off.

**Comment by jvasileff** [comment]
There's probably a few of these in the JDK, but a popular one I just need to use is `EnumSet` which has static methods `noneOf`, `allOf`, `of`, etc.

**Comment by gavinking** [comment]
@jvasileff Not for 1.2. Sorry!

**Comment by gavinking** [comment]
P.S. FTR, The workaround is:

```ceylon
import java.util { EnumSet { ... } }
```

**Comment by gavinking** [comment]
@jvasileff Should be fixed now. I tested it with Guava imported from Maven.

```ceylon
import com.google.common.collect {
    ImmutableList
}

 
shared void run() {
   ImmutableList<String> list = 
            ImmutableList.\iof("1", "2", "#");
    print(list);
}
```

It worked.

**Comment by jvasileff** [comment]
Thanks Gavin, my codes will look *much* cleaner now
