### ISSUE TITLE
sealed (and unshared) default constructors

### ISSUE THREAD

**Issue by gavinking** [ceylon/ceylon-spec#1210]
Should a default constructor be allowed to be `sealed`? If so, the typechecker needs to know what to do with that.

**Comment by gavinking** [comment]
A second question: the spec says that default constructors must be annotated `shared`. Is that still the right thing? If so, the typechecker needs to enforce it. It might make sense when we start supporting delegation to partial constructors.

**Comment by lukedegruchy** [comment]
I have a sealed default constructor in one module:

```ceylon
shared class MyThingee {
    shared Integer mNumber;

    sealed shared new(Integer number) {
        mNumber = number;
    }
}
```
Now I try to call the constructor from another module, it compiles:

```ceylon
import constructors {
    MyThingee
}
void another() {
    value myThingee = MyThingee(1);
}
```

The sealed annotation currently states that any sealed constructor cannot be accessed in another module.

Is the intention eventually to:

1) Allow a sealed shared default constructor?
2) Allow an unshared unsealed constructor?
3) Something else

My personal opinion (for what it's worth) is anything that allows one not to expose any constructor to another module and only its associated "factory" function would be desirable in terms of implementing the private constructor pattern.   The use case for the private constructor pattern is to allow refactoring if the initial contract for constructing a published class is wrong, and can be altered without affecting the associated "factory" function.

**Comment by gavinking** [comment]
@lukedegruchy Well, that's one of the things this issue is asking.

**Comment by lukedegruchy** [comment]
My preference would then be to allow an unshared default constructor that can only be called from a top level function in the same package or another constructor in the same class.  The only downside that I can see is that it can't be called from a unit test in another source folder.  Then again, I think the proposed new feature that allows a parameterized shared annotation (can't remember the exact terminology) should resolve that use case.

Perhaps my opinion is due to my Java bias, but the private constructor plus public factory method pattern feels more natural to me than using sealed, which even though it exists in Scala and Ceylon doesn't exist in Java.   The sealed annotation only seems to restrict interfaces or classes (and non default constructors) in how they're used in other modules, which may not be restrictive enough.

**Comment by jvasileff** [comment]
I agree with @lukedegruchy that the various constructor and factory scenarios are useful.

Regarding `sealed`, I think it would be more straight forward if it were (made to be) strictly limited to restricting inheritance and conformance, with an enhanced `shared` annotation handling visibility. So `sealed` would only apply to classes and interfaces.

**Comment by gavinking** [comment]
> My preference would then be to allow an unshared default constructor that can only be called from a top level function in the same package or another constructor in the same class.

Two comments:

1. This isn't for constructor delegation. I have a separate proposal for `abstract` (partial) constructors and delegation that I'm completely happy with.
2. To say that an un-`shared` constructor nested inside the body of a class is visible to a toplevel function defined outside the class would be highly irregular with the interpretation of `shared` in all other contexts in the language. That's why I'm using `sealed` for that instead.

> Then again, I think the proposed new feature that allows a parameterized shared annotation (can't remember the exact terminology) should resolve that use case.

Right. That proposal is still very much alive, and is a very strong candidate for inclusion in Ceylon 1.3.

**Comment by lukedegruchy** [comment]
@gavinking Would the proposal you mentioned at the tail end of your message support defining a constructor that is only shared to its package, or is this also in conflict with your intention of use for shared?

Also, is sealed intended strictly to apply to a course-grained inter-module publication, or do you see it evolving into a more finer-grained mechanism, similar to the parametrized shared enhancement that you mentioned?

**Comment by gavinking** [comment]
> Would the proposal you mentioned at the tail end of your message support defining a constructor that is only shared to its package

No.

> Also, is sealed intended strictly to apply to a course-grained inter-module publication, or do you see it evolving into a more finer-grained mechanism

No. I would enhance `shared` for that purpose.

I agree that the annotations overlap, much more than I would like.

**Comment by gavinking** [comment]
Indeed, perhaps `sealed` should have been a member of `shared`, now that I think about it like that. I guess I screwed up.

**Comment by jvasileff** [comment]
Isn't the *only* current overlap the visibility limit on class level (1.1) constructors?

My thought was that this can be avoided:

```ceylon
shared sealed class Foo {
    shared new () {}
    shared sealed new ModuleOnlyCtor() {}
    shared("*MOD_ONLY*") void moduleOnlyFunc() {}
}
```
in favor of this (eventually):
```ceylon
shared sealed class Foo {
    shared new () {}
    shared("*MOD_ONLY*") new ModuleOnlyCtor() {}
    shared("*MOD_ONLY*") void moduleOnlyFunc() {}
}
```

**Comment by luolong** [comment]
So if, `sealed` is essentially alias to `shared("module")`, can not we just redefine it in next version of Ceylon as such -- once we have more granular visibility controls?

**Comment by gavinking** [comment]
@luolong well, it's not the same as `shared(module)` because it doesn't limit the visibility of a _declaration_.

But sure, in principle I suppose we could in future make it an alias for `shared(instantiableScope=module)` or something.

**Comment by gavinking** [comment]
> Isn't the *only* current overlap the visibility limit on class level (1.1) constructors?

Yes.

> in favor of this (eventually):

Well, sure, but in 1.2 we don't have suppert for `shared(module)` or `shared((package)`.

**Comment by gavinking** [comment]
I have resolved this issue by saying:

- Default constructors must be `shared`.
- Classes with constructors may not be `sealed`.
- Any constructor may be `sealed`.

**Comment by gavinking** [comment]
Closing.

**Comment by lukedegruchy** [comment]
This doesn't compile:

class without parameter list may not be annotated sealed	

The compile error shows at the class definition line.

```ceylon
shared class Thing{
    String name;

    sealed shared new(String name) {
        this.name = name;
    }
   
    sealed shared new Another(String name) {
        this.name = name;
    }
}
```

If I remove sealed from the default constructor, it compiles.

Is this the intended behaviour with this fix, or did I find a bug?   I double-checked that this is with the latest code from github.

**Comment by gavinking** [comment]
Yeah, I screwed up.

**Comment by gavinking** [comment]
@lukedegruchy is that better?

**Comment by gavinking** [comment]
Yeah, that seems to have fixed it. Re-closing.

**Comment by lukedegruchy** [comment]
Confirmed.   The compile error no longer appears with the latest code.  Also, attempting to invoke the sealed default constructor from another module fails, as expected.
