### ISSUE TITLE
partial (abstract) constructors

### ISSUE THREAD

**Issue by gavinking** [ceylon/ceylon-spec#1212]
Issue #1130 proposes a limited form of constructor delegation which adds little additional expressiveness to the language. This proposal is a rethinking the notion of delegation, that adds much more, and recaptures most of what is possible with constructors in Java and other similar languages.

The idea is to allow a "partial" constructor, annotated `abstract`, which leaves some members of the class uninitialized, and allow other constructors to delegate to the partial constructor using `extends`, and then fill in the uninitialized members. For example:

```ceylon
class Foo {
    Bar bar;
    Baz baz;
    abstract new Partial(Bar bar) {
        this.bar = bar;
    }
    shared new Foo(Bar bar, Baz baz) 
            extends Partial(bar) {
        this.baz = baz;
    }
}
```

A partial constructor must occur before the constructors that delegate to it. It may, in turn, delegate to another partial constructor, or to a constructor of the superclass.

By taking into account the whole chain of constructors, the typechecker would still be able to enforce the usual rules of initialization in Ceylon:

- `variable` attributes must be initialized at least once, and
- non-`variable` attributes must be initialized _exactly_ once.

Just like an `abstract` class, an `abstract` constructor may not be invoked except from an `extends` clause. An `abstract` constructor may not be `shared`.

**Comment by tombentley** [comment]
From your description something like this would be allowed:

    class C {
      exectuableStatement();
      abstract new Constructor() {}
      exectuableStatement();
      new C() extends Constructor() {}
    }

That could prove interesting from an implementation PoV, but I guess it could be done.

**Comment by gavinking** [comment]
@tombentley No. The current rule is that constructors _must_ come right at the end of the initialization section. You can't mix statements with constructor declarations.

**Comment by RossTate** [comment]
It'd probably be useful for subclasses to use superclasses' partial constructors as well.

**Comment by lukedegruchy** [comment]
Would it be possible to support another constructor that takes a completely different parameter list, convert it, and then call the abstract constructor?

This is the best way I can think of to illustrate what I'm trying to do, even though I'm sure it's grossly incorrect from a compilation perspective:

```ceylon
class Foo {
    Bar bar;
    Baz baz;

    abstract new(Bar bar, Baz baz) {
        this.bar = bar;
        this.baz = baz;
    }
    shared new FooShared(String barBazEncoded) 
            extends Partial(bar,baz) {
            super(convertBarBazEncodedToBarAndBaz(barBazEncoded));
    }
}
```

**Comment by gavinking** [comment]
@lukedegruchy well, sadly, we're extremely limited in terms of what the JVM itself will let us do. Perhaps if we compiled partial constructors as methods rather than as constructors, then we might be able to allow a bit more flexibility, but we also need to fit things into the current syntax....

**Comment by gavinking** [comment]
This is now supported on the `1212` branch, and on `spec1212` branch of `ceylon.language`.

**Comment by gavinking** [comment]
Done, including tests and spec!

**Comment by jvasileff** [comment]
This blows up both backends, but I'm not certain it is correct (the other option being `new Alt() extends ("")`)

```ceylon
class Ec {
    shared new (String _) {
        print("In Default");
    }

    shared new Alt() extends Ec("") {
        print("In Alt");
    }
}
```

This works as I would expect on both backends (at least for `Ec.Alt()`), but noting it here to make sure the shadowing should be allowed:

```ceylon
class Ec {
    shared new (Integer _) {
        print("In Default");
    }

    shared new Ec(String _) {
        print("In Ec.Ec");
    }

    shared new Alt() extends Ec("") {
        print("In Alt");
    }
}
```

**Comment by gavinking** [comment]
@jvasileff both those code examples look correct to me, and I think the typechecker does the right thing. So that would be the backends that are broken.

**Comment by jvasileff** [comment]
@gavinking ok, thanks, I'll create issues for the backends.
