### ISSUE TITLE
Proposal: Backslash at end of line in a multiline string literal escapes the EOL sequence

### ISSUE THREAD

**Issue by PhiLhoSoft** [ceylon/ceylon-spec#1215]
Reference discussion: https://groups.google.com/forum/#!topic/ceylon-users/N3idC2CZQxI

Sometime we need to split a long line of string for readability reasons or to comply with coding style rules. Using Ceylon's multiline string for that is an obvious move, but the EOL sequence (\n or \r\n (or even \r for Mac nostalgics!) is then encoded in the string.

If we split on a space, we can just use the `normalized` attribute to replace it with the wanted space.
Otherwise, we have to concatenate strings ourselves, the Java way, or to use other unsatisfying workarounds.

I propose we see a dangling backslash, ie. one at the end of the line, as an escape of the EOL sequence, nullifying it. A bit like in the C templates, for example.

So
```
"Fizz\
 Buzz"
```
would be the same as `"FizzBuzz"`
and
```
"Hello \
 World!"
```
or
```
"Hello\
  World!"
```
would become `"Hello World!"`

**Comment by jvasileff** [comment]
This would be very useful for String literals in annotations where concatenation is not an option.

**Comment by gavinking** [comment]
I find myself in favor of this proposal&mdash;and it would even be easy enough to implement completely within the typechecker for 1.2. Does anyone think I _shouldn't_ implement it?

**Comment by sadmac7000** [comment]
Sounds fine to me.

**Comment by quintesse** [comment]
Fine with me.

**Comment by tombentley** [comment]
I suppose this is OK. It does mean that a verbatim string isn't entirely verbatim anymore, and I have to scroll to find out what's going on, but that's not the end of the world.

**Comment by gavinking** [comment]
@tombentley I don't propose to do this for verbatim strings.

**Comment by gavinking** [comment]
Done.
