### ISSUE TITLE
Need some easy way to get indices for typeArguments

### ISSUE THREAD

**Issue by sadmac7000** [ceylon/ceylon-spec#1217]
The metamodel's Generic interface exposes a typeArguments element for getting type arguments. These are indexed on TypeParameter objects, which are rather hard to acquire. You actually have to go to the declaration object at the moment and get a TypeParameter by index from there.

We discussed possibly adding a syntax like this:
```ceylon
`given List.Element`
```

To fetch the Element type parameter from the list class.

**Comment by gavinking** [comment]
@sadmac7000 This is mis-filed. It belongs [here](https://github.com/ceylon/ceylon.language/issues/new).

**Comment by sadmac7000** [comment]
https://github.com/ceylon/ceylon.language/issues/640
