### ISSUE TITLE
method refinement via specifier and annotations

### ISSUE THREAD

**Issue by FroMage** [ceylon/ceylon-spec#1219]
Does the spec say what happens to annotations in the following case:

```ceylon
interface Foo {
 shared formal Integer f1(Object param);
 shared formal Integer f2(Object param);
}
class Impl() satisfies Foo {
 f1 = function(myAnnotation Object param) => 2;
 f2(myAnnotation Object param) => 2;
}
```

For `f2` currently (and it seems obvious that's right) `myAnnotation` is set on the parameter. For `f1` currently it does not, but should it? I think not, but we could do it in some trivial cases.

**Comment by gavinking** [comment]
Is `f2` accessible via the metamodel?

**Comment by FroMage** [comment]
Yes, both `f1` and `f2` since they are implicitly `shared actual`.

**Comment by gavinking** [comment]
Well then I guess I think the annotation should be accessible too.

**Comment by FroMage** [comment]
For both or just `f2`? `f1` is the problematic case. It looks more like an assignment rather than a declaration, so it's not clear that `f1` should get the annotations of the lambda.

**Comment by gavinking** [comment]
Oh I see. No, it definitely should not. The anon function is an expression not a declaration of `f1`.

**Comment by FroMage** [comment]
OK, so we're good then, that's what the compiler does. Just checking if the spec specifies this or not.
