### ISSUE TITLE
Improve initialisation flow

### ISSUE THREAD

**Issue by FroMage** [ceylon/ceylon-spec#1220]
This is issue number inflation I'm telling you ;)

I want to be able to write the following:

```ceylon
Exception x;
try{
 foo();
 assert(false);
}catch(AssertException x1){
 x = x1;
}
try{
 foo();
 assert(false);
}catch(AssertException x2){
 assert(x == x2);
}
```

We can only exit the first `try` block via the `catch` due to `assert(false)` (or exit the entire function if `foo` throws something which is not an `AssertException`), so `x` _must_ be initialised exactly once.

**Comment by gavinking** [comment]
After fixing the 2 bugs in the above code, it passed the typechecker. I don't think you ever tested it.

**Comment by FroMage** [comment]
OK I see what happened. I did try it, and I got an error, which I didn't read and assumed it was about initialisation and refactored it. You're right it works, great!
