### ISSUE TITLE
Allow dynamic expression A.B()

### ISSUE THREAD

**Issue by chochos** [ceylon/ceylon-spec#1221]
Right now you can do `a.B()` in a dynamic block and it's considered a qualified type expression, but `A.B()` gives an error because the typechecker can't find type `B` in type `unknown`.

`A.B()` inside a dynamic block should also be considered a qualified type expression with unknown types/no declarations and the (JS) backend can simply generate that as `new A.B()`.

See ceylon/ceylon-js#441

**Comment by gavinking** [comment]
Done, apologies for taking so long on this (easy) one.

**Comment by chochos** [comment]
Cool, this closes 2 js issues.
