### ISSUE TITLE
`Parameter.isDefaulted()` depends on order of declaration

### ISSUE THREAD

**Issue by FroMage** [ceylon/ceylon-spec#1222]
If you have a shortcut-refinement of a method with a defaulted param that happens before the declaration of its overridden method, then the parameter will not have its `defaulted` boolean set:

```ceylon
class C() satisfies L2 {
    // i.defaulted == false
    m(Integer i) => print("");
}

interface L {
    shared formal void m(Integer i= 1);
}

interface L2 satisfies L {
    shared actual formal void m(Integer i);
}
```

This happens because although `L.m.i.defaulted` is set in an earlier phase, `L2.m.i.defaulted` and `C.m.i.defaulted` are set in the same phase.

Found while debugging ceylon/ceylon-compiler#2033

**Comment by gavinking** [comment]
Fixed!

**Comment by FroMage** [comment]
Thanks!
