### ISSUE TITLE
Named constructor masks class within class's implementation

### ISSUE THREAD

**Issue by jvasileff** [ceylon/ceylon-spec#1223]
It doesn't appear possible to invoke a named constructor of a generic class from within the class's implementation with different type parameter values than those of the future instance *when* the class has a named constructor with the same name as the class.

```ceylon
shared class MutableBox<Element> {
    shared variable Element element;

    shared new MutableBox(Element element) {
        this.element = element;
    }

    shared new Of(Element element) {
        this.element = element;
    }

    shared void misc() {
        MutableBox<String> bs1 = MutableBox("a");
        // Argument must be assignable to parameter element of MutableBox in MutableBox<Element>:
        //      String is not assignable to Element
        // Specified expression must be assignable to declared type of bo:
        //      MutableBox<Element>.MutableBox is not assignable to MutableBox<String>

        MutableBox<String> bs2 = outer.MutableBox("a");
        // Outer appears outside a nested class or interface definition
        
        MutableBox<String> bs3 = MutableBox<String>.Of("b");
        // Does not accept type arguments: MutableBox

        MutableBox<String> bs4 = boxFactory("c");
        // ok (the workaround *so long as the constructor is shared!*)
    }
}

shared MutableBox<Element> boxFactory<Element>(Element element)
    =>  MutableBox(element);
```

This makes it difficult to implement, for example:

```ceylon
    Set<Element|Other> exclusiveUnion<Other>(Set<Other> set)
            given Other satisfies Object { }
```

**Comment by gavinking** [comment]
@jvasileff Did you try:

```ceylon
MutableBox<String> bs1 = MutableBox<String>.MutableBox("a");
```

**Comment by jvasileff** [comment]
Yes, I did

**Comment by jvasileff** [comment]
Ah, actually, `package.MutableBox<String>.MutableBox("b");` works. Not sure how I feel about this.

**Comment by jvasileff** [comment]
Hmm, so type inferencing isn't available for named constructors? `package.MutableBox.MutableBox("b");` -> "Missing type arguments to generic declaration: MutableBox declares type parameters Element"

**Comment by gavinking** [comment]
> Ah, actually, `package.MutableBox<String>.MutableBox("b");` works.

Yes, sorry, that's what I meant.

>  Not sure how I feel about this.

Well, it's the only thing that really works from the point of view of what are our scoping rules...

**Comment by gavinking** [comment]
> Hmm, so type inferencing isn't available for named constructors?

Ah. Ooops. I need to fix that. Please open an issue against ceylon-spec.

**Comment by jvasileff** [comment]
> Well, it's the only thing that really works from the point of view of what are our scoping rules...

Ok, fair enough. But from a naive perspective, it would seem this should work then:

```ceylon
SomeType<String>.Of x = SomeType<String>.Of("a");
```

since this is correct:

```ceylon
SomeType<String> bs1 = SomeType<String>("a");
```

The nuance of a class name serving as either a type or shorthand for a reference to its default constructor depending on context can be missed. Without context, is `SomeType` a constructor? Is `Of` a type?

Simpler cases are more clear:

```ceylon
shared class C() {}
C() factory = nothing; // C ≠ C() in this usage

value c = factory(); // "c" is actually a "C"
```

it's not too hard to understand that `factory` produces instances of `C`, rather than something like  `C(C(C(...)))`.

But within a class definition, there may be a *perceived* inconsistency that helps lead to confusion, in that *internal* to the class, correct usage of the class's identifier is dependent on whether or not named constructors are in use. IOW, classes without named constructors do not behave as if they have an implicit named constructor of the same name as the class.

```ceylon
shared class MutableBox1<T>() {
    value x => MutableBox1; // error
    // Missing type arguments to generic declaration:
    //  MutableBox declares type parameters T
}

shared class MutableBox2<T> {
    shared new MutableBox2() {}
    value x => MutableBox2; // ok! same as "package.MutableBox2"
}
```

I think shadowing is much more clear here:

```ceylon
shared class MutableBox3<T>() {
    shared class MutableBox3() {}
    value x => MutableBox3; // x is MutableBox3<T>.MutableBox3()
```

since `package.MutableBox3` (or even just `MutableBox3` from outside the class definition) is never used as shorthand for `package.MutableBox3.MutableBox3`.

I guess lowercase identifiers for named constructors would sidestep this issue, but perhaps would cause other problems.

**Comment by jvasileff** [comment]
Closing since my original problem is solved and the rest is just discussion/musings.
