### ISSUE TITLE
Support type inference for named constructors

### ISSUE THREAD

**Issue by jvasileff** [ceylon/ceylon-spec#1224]
For example:

```ceylon
shared class Box<Element> {
    shared new Of(Element e) {}
}

Box<String> bs = Box.Of("");
// Missing type arguments to generic declaration:
//  Box declares type parameters Element
```

**Comment by gavinking** [comment]
I have implemented this on a branch. It was most natural to also support inference for qualifying types in static method references, for example, `List.get([1,2,3])(0)`.

But that means I still have to really think this through and see if I can poke holes in it.

**Comment by gavinking** [comment]
OK, so this is now fully implemented, and the branch merged. I'm leaving the issue open for now, because this needs to be documented in the spec.

**Comment by gavinking** [comment]
Spec done.
