### ISSUE TITLE
Case coverage analysis erroneously giving error?

### ISSUE THREAD

**Issue by AnhNhan** [ceylon/ceylon-spec#1228]
https://gist.github.com/686ade97f4491adb9b7e

Ceylon 1.1 vanilla, not tested on master

```
source\caseCoverageAnalysisError.ceylon:36: error: case types must cover all cases of the switch type or an else clause must appear: 'Left<Bar>|Left<Baz>' does not cover 'Left<Foo>'
    switch (f2)
   ^
source\caseCoverageAnalysisError.ceylon:40: error: cases are not disjoint: 'Left<Baz>' and 'Left<Bar>'
    case (is Left<Baz>)
         ^
2 errors
```

Given the types `Foo of Bar|Baz` and `Left<out Element>`, does the type `Left<Bar>` in the switch case get erased / generalized to `Left<Foo>` (or an even super-er type)? That would be my explanation for the typechecker rejecting it, since it would cause it into thinking `Left<Foo>` appearing twice.

**Comment by gavinking** [comment]
@AnhNhan in fact this is not a bug. You can have an instance of `Left<Foo>` that is not a `Left<Bar>` or a `Left<Baz>`. For example, a concrete `Left<Foo>` or a concrete `Left<Bar|Baz>` are examples of such instances.

Hope that helps explain the behavior.
