### ISSUE TITLE
Let expressions not explained in the spec. 

### ISSUE THREAD

**Issue by tkaitchuck** [ceylon/ceylon-spec#1231]
They are explained fairly well in issue #747  however the spec does not cover them much. Neither does the language reference.

**Comment by gavinking** [comment]
Well `let` expressions are specified in §6.7.3 of the spec in git. Perhaps there's something missing there, but if so, could you be more specific about what more it needs to cover?

**Comment by gavinking** [comment]
@tkaitchuck Do you have some additional specifics on this issue?

**Comment by gavinking** [comment]
No response, so I'm closing. @tkaitchuck if you have some further feedback, please reopen.
