### ISSUE TITLE
NPE for partial switch expression in IDE

### ISSUE THREAD

**Issue by sgalles** [ceylon/ceylon-spec#1237]
This code
```ceylon
value foo = switch(true) case(true)
```
in the IDE
`ExpressionVisitor caused an exception visiting SwitchExpression node: java.lang.NullPointerException at com.redhat.ceylon.compiler.typechecker.analyzer.ExpressionVisitor.visit(ExpressionVisitor.java:279)`

**Comment by gavinking** [comment]
Thanks, fixed!
