### ISSUE TITLE
Inconvenient <Object | null> type inference

### ISSUE THREAD

**Issue by jvasileff** [ceylon/ceylon-spec#1238]
Narrowing via flow sensitive typing can result in `<Element&Object|Element&null>` instead of simply `Element`.

```Ceylon
object eof {}

alias Input<Element> => Element | \Ieof;

class InvBox<Element>(shared Element el) {}

InvBox<Element>? switchOnInput<Element>(Input<Element> input) {
    switch(input)
    case (eof) {
        return null;
    }
    else {
        return InvBox(input); // error
        // InvBox<Element&Object|Element&null> is not assignable to InvBox<Element>?
    }
}
```

Workarounds include `return InvBox<Element>(input);` and `return InvBox(input of Element);`.

The same happens for the less interesting case `alias Input<Element> => Element | String;`, and also with `if`, as in `if (!is \Ieof item) { ... }`.

This only affects generic types, so `switchOnInput(Input<Foo> input) { ... }` does not exhibit this behavior.

**Comment by gavinking** [comment]
Well, sadly, due to concerns about decidability, `Element&Object|Element&null` is not the same type as `Element` in our type system. (Coverage is not the same as subtyping.)

**Comment by jvasileff** [comment]
Ok. I guess what was confusing to me is that I didn't ask (have a need) for the fact that `Anything` is an enumerated type to be taken into account. So in the catch-all `else` block, the extra information available to the type checker turned into a liability for me, given that none of the prior `case`s "peeled off" any of the enumerated types.

But what is happening is more clear to me after experimenting with:

```ceylon
abstract class C() {} //of C1 | C2 {}
class C1() extends C() {}
class C2() extends C() {}

alias Input<Element> given Element satisfies C => Element | String;
...
```

I'll go ahead and close this since I'm guessing it doesn't serve much use as a separate feature request.

**Comment by RossTate** [comment]
@gavinking, we've been researching this. One thing we found is that the normalization strategy y'all are doing can only work correctly if `normalize(t1|t2)` evaluates to `normalize(t1)|normalize(t2)` syntactically. In this case, `normalize(Object|null)` evaluates to `Anything` (i.e. top), which is not `normalize(Object)|normalize(null)`, which is `Object|null` syntactically. That fact is causing the problem and this is unavoidable with a normalization strategy.

**Comment by gavinking** [comment]
@RossTate I don't quite follow. We don't normalize `Object|null` to `Anything`.

We *do* replace `null` in the type `Object|null` with `Null`, resulting in `Object|Null`, but that's for quite different reasons, and doesn't have an impact upon the algorithms.

**Comment by RossTate** [comment]
Oh, I may have lost track of things. I thought y'all had `Anything` being a subtype of `Object|null` or `Object|Null`.

**Comment by gavinking** [comment]
Nope, not for years. At the time I took your advice and backed that out.

**Comment by RossTate** [comment]
Woot!

**Comment by RossTate** [comment]
Actually, we may be able to fix this, though it's costly. Each time you check a subtyping, you'd have to intersect the subtype with `Object|null` and DNF the result. If that subtyping recurses, you'd have to repeat this process each time you recurse.

**Comment by jvasileff** [comment]
It looks like my concern, particularly WRT:

> I didn't ask (have a need) for the fact that Anything is an enumerated type to be taken into account

was addressed in https://github.com/ceylon/ceylon-spec/commit/a45448cc2f38aff460ce5da974db692a93151d94. So, now, the original example works!

**Comment by gavinking** [comment]
@jvasileff Ah, I guess I never really properly understood the nature of your objection to the previous behavior. Well, good that it's fixed now :)
