### ISSUE TITLE
package qualifier in meta references

### ISSUE THREAD

**Issue by tombentley** [ceylon/ceylon-spec#1245]
While I'm allowed to use `package` in normal expressions as a qualifier to access a toplevel declaration which is shadowed by another declaration, it seems this isn't supported in meta expressions:

```
class C() {
    shared void f(){}
}
void m<C>() {
    //value fm = `C.f`;// method or attribute does not exists: 'f' in type 'C'
    value fm = `package.C.f`;//syntax error
}
```

**Comment by gavinking** [comment]
And you want this in 1.2?

**Comment by tombentley** [comment]
No, not especially, I just noticed the irregularity while adding support for #1243.

**Comment by gavinking** [comment]
I have finished implementing this. Though I still need to add tests and a spec.

Note that I've also allowed the syntax `package.Type` in ordinary type expressions.

**Comment by tombentley** [comment]
It seems I can use the package qualifier in `satisfies` clause, but not in the `extends` clause, which is a bit irregular.

**Comment by gavinking** [comment]
All done.

**Comment by tombentley** [comment]
Thanks!
