### ISSUE TITLE
Double error for self-extending class

### ISSUE THREAD

**Issue by lucaswerkmeister** [ceylon/ceylon-spec#1247]
```ceylon
class C() extends C() {}
```
> source/tmp/run.ceylon:1: error: inheritance is circular: definition of 'C' is recursive, involving 'C'
```ceylon
class C() extends C() {}
         ^
```
source/tmp/run.ceylon:1: error: directly extends itself: 'C'
```ceylon
class C() extends C() {}
                 ^
```
2 errors

The “directly extends itself” error makes the “inheritance is circular” one redundant.

**Comment by gavinking** [comment]
Fixed.

**Comment by lucaswerkmeister** [comment]
Thanks!
