### ISSUE TITLE
MemberClassConstructor.Type can be a Constructor

### ISSUE THREAD

**Issue by tombentley** [ceylon/ceylon-spec#1248]
```ceylon
class ClassContainer(){
    shared object memberObject {
        shared class Ctor {
            shared new Ctor() {}
            shared new Other() {}
        }
    }
    shared void test(ClassContainer other){
        MemberClassConstructor<\ImemberObject,\ImemberObject.Ctor.Ctor,[]> ctorCtor = `\ImemberObject.Ctor.Ctor`;
        print(ctorCtor(other.memberObject)());
        MemberClassConstructor<\ImemberObject,\ImemberObject.Ctor,[]> ctorOther= 
                `\ImemberObject.Ctor.Other`;
    }
}
```

When I reference the constructor `Ctor` the `Type` of the `MemberClassConstructor` (i.e. it's second type argument) is allowed to be `\ImemberObject.Ctor.Ctor`, but it should simply be `\ImemberObject.Ctor` I think. Certainly in the case of a non-default constructor the type argument must be `\ImemberObject.Ctor` and `\ImemberObject.Ctor.Other` is rejected because "constructor is not a type: Other".

**Comment by gavinking** [comment]
This is fixed, but I'm going to open a new issue which questions the whole underlying design that led to this bug!
