### ISSUE TITLE
Method refines Value

### ISSUE THREAD

**Issue by tombentley** [ceylon/ceylon-spec#1249]
As discussed in ceylon/ceylon-compiler#2074 in the presence of some errors it's possible for the refined declaration of a `Method` to be a `Value` even when the method declaration concerned doesn't have any errors attached to its `Tree`.

**Comment by gavinking** [comment]
@tombentley @FroMage I have fixed this, I believe, at least your `StackOverflowError` is gone. However, it seems that the compiler now generates an invalid class file.
