### ISSUE TITLE
reconsider approach to default constructors

### ISSUE THREAD

**Issue by gavinking** [ceylon/ceylon-spec#1250]
The current approach to default constructors involved engineering a couple of hacks into the typechecker so that _within the body of the class which declares the default constructor_, the class name can refer to _either the class or the constructor_, depending on context. This is the design that underlies issues #1195 and which also resulted in the fixed bug #1248.

Upon reflection, that approach is simply a bit lame and ad hoc!

I wonder if it might be better to express the default constructor as a constructor with _no name_, for example:

```ceylon
class Point {
    shared Float x;
    shared Float y;
    shared new (Float xx, Float yy) {
        x = xx;
        y = yy;
    }
    shared new Diagonal(Float d) {
        x = d;
        y = d;
    }
}
```

There's two objections I could see to this:

1. it's slightly irregular compared to the usual syntax for Ceylon declarations, but I can live with that, and
2. it doesn't give us an obvious way to get a meta _model_ expression that refers to the default constructor.

I think we need to all think this through properly before we go making a mistake and baking it into the language and maybe regretting it later!

**Comment by jvasileff** [comment]
I like it. It looks like this would eliminate namespace problems when converting to named constructor style from standard. And it also helps answer my concerns in #1223.

**Comment by gavinking** [comment]
Another possibility would be to use an annotation to identify the default constructor. Sadly, the word `default` is already taken, so it would be `primary`, or something like that:

```ceylon
class Point {
    shared Float x;
    shared Float y;
    shared primary new New(Float xx, Float yy) {
        x = xx;
        y = yy;
    }
    shared new Diagonal(Float d) {
        x = d;
        y = d;
    }
}
```

**Comment by gavinking** [comment]
Hrm, I guess another way we could solve this problem would be to use something inspired by the syntax for class aliases:

```ceylon
class Point(Float xx, Float yy) 
        => New(xx,yy) {
    shared Float x;
    shared Float y;
    shared new New(Float xx, Float yy) {
        x = xx;
        y = yy;
    }
    shared new Diagonal(Float d) {
        x = d;
        y = d;
    }
}
```

But that's getting even _more_ verbose.

**Comment by gavinking** [comment]
Ah, no, I don't like that because it looks like the parameters `xx` and `yy` are in scope in the body of `Point`, but in fact they're not. So the syntax should be something like this instead:

```ceylon
class Point = New {
    shared Float x;
    shared Float y;
    shared new New(Float xx, Float yy) {
        x = xx;
        y = yy;
    }
    shared new Diagonal(Float d) {
        x = d;
        y = d;
    }
}
```

I really don't much like the look of that, however.

**Comment by quintesse** [comment]
I guess the need for a default constructor has to do with being able to add a second (third, etc) constructor to an existing (single constructor) class without breaking existing code, right? Because otherwise we could have done away perhaps with the entire idea of a default constructor.

**Comment by DiegoCoronel** [comment]
I agree with @quintesse , all those suggestions changing the language to support default constructors dont look to fit nicely (my opnion, of course), the best one for me is the annotation way, I think default constructors could be postponed.

**Comment by gavinking** [comment]
@quintesse Right, it is needed for API evolution.

**Comment by quintesse** [comment]
So maybe we could use the annotation but make it optional? Meaning that you'll only encounter it in cases of API evolution from single to multi constructor?
Still it's a pity we couldn't use `default` for this, having to introduce e new annotation is the main issue I have with the annotation proposal.

And what possibilities would there be for the meta model access in case of the nameless proposal?

**Comment by gavinking** [comment]
> And what possibilities would there be for the meta model access in case of the nameless proposal?

Well, the question is whether it's even needed. The relevant info is all available via the class' metamodel. But sure, you could have an attribute of `Class` holding the default constructor.

**Comment by gavinking** [comment]
> So maybe we could use the annotation but make it optional? Meaning that you'll only encounter it in cases of API evolution from single to multi constructor?

I don't understand. Default constructors are _always_ optional.

**Comment by gavinking** [comment]
So the "constructor with no name" idea is now mostly implemented in [this branch](https://github.com/ceylon/ceylon-spec/compare/new_def_constr). It was very easy to implement, as you can see in @e0c95c6d855dacfc409a0b4d46bbfbf8a1a6f53c. And honestly I seem to be quickly getting used to the syntax.

**Comment by sadmac7000** [comment]
I'm in to it.

**Comment by tombentley** [comment]
>> And what possibilities would there be for the meta model access in case of the nameless proposal?

>Well, the question is whether it's even needed. The relevant info is all available via the class' metamodel. But sure, you could have an attribute of `Class` holding the default constructor.

This is slightly less ergonomic than I initially expect because (assuming for a moment we keep the existing API) we have to `assert` the existence of the default constructor when this is known at compile time:

    assert(exists ctor = `C`.getConstructor("")); 
    // was value ctor = `C.C`;

The same situation exists for constructor declarations:

    assert(exists ctorDecl = `class C`.getConstructorDeclaration("");
    //value ctorDecl = `new C.C`;

In the case of constructor declarations I suppose we could support `new C` (this is currently a type error).

**Comment by tombentley** [comment]
Sorry, it's slightly worse than that in the case of constructor models, because you have to pass the argument list type:

    assert(exists ctor = `C`.getConstructor<[String]>(""));

**Comment by gavinking** [comment]
The thing is that for classes with a default constructor you can use the `Class` metamodel for almost everything, just like you would for a regular class with an initializer parameter list.

The only thing missing is the ability to read annotations, but that is something you do via the `ClassDeclaration`, usually.

**Comment by gavinking** [comment]
> In the case of constructor declarations I suppose we could support `new C`

I will implement that.

**Comment by tombentley** [comment]
Another area of dissatisfaction with the metamodel are the `name` and `qualifiedName` or `ConstructorDeclaration`s of default constructors, all of which are now a bit rubbish, but it's not like we have a choice.

**Comment by gavinking** [comment]
:-(

**Comment by gavinking** [comment]
I still have to update the spec!

**Comment by gavinking** [comment]
Done. Closing!
