### ISSUE TITLE
ordering rules for constructors.

### ISSUE THREAD

**Issue by gavinking** [ceylon/ceylon-spec#1254]
In #1125, @sadmac7000 advocated relaxing the rule that a constructor must occur at the very end of the initializer section. It is proposed to support this:

```ceylon
class Foo {
    shared Integer foo;
    shared Integer bar;
    shared new Bar(Integer foo) {
        this.foo = foo;
    }
    bar = 1;
}
```

I don't see a problem with this from a typechecker/spec point of view. And it seems that it's at least in principle consistent with how we currently implement constructors (which is _not_ how I originally intended them to be implemented).

So, @tombentley, WDYT? Should we do this for 1.2?

**Comment by ncorai** [comment]
Is the purpose to allow initialization such as `bar = foo + 1;` when there are for instance two different constructors initializing `foo`? Because, for `bar = 1;` I don't see the point.

**Comment by sadmac7000** [comment]
Restrictions are always strictly less intuitive to have than not. The point is to not bother the programmer with conforming to a restriction needlessly.

I lost a good bit of time just meaninglessly shunting statements around to meet these requirements when I ported a class from a basic constructor to advanced constructors.

**Comment by gavinking** [comment]
I have implemented the typechecker side of this in the [1245 branch](https://github.com/ceylon/ceylon-spec/compare/1254). My bet is that it's not super-difficult to support this change in the backends. WDYT, @tombentley @chochos?

**Comment by gavinking** [comment]
Well, I have updated the spec, and opened issues for the backend implementation, so I think I can close this.

**Comment by chochos** [comment]
But what should the behavior be? If it is to run the initializer code before the constructor code, then this already works in JS.

**Comment by sadmac7000** [comment]
@chochos That sounds correct to me FWIW. Unless that can result in an error (assuming the initial code already passed the type checker).

**Comment by gavinking** [comment]
@chochos Nope. You are supposed to run the initializer code the occurs *before* the constructor at the beginning of the constructor invocation, and the initializer code that occurs *after* the constructor at the end of the constructor invocation.

@tombentley I hope that's what you implemented, right?

**Comment by sadmac7000** [comment]
Ah. I overinterpreted. @gavinking is correct.

**Comment by chochos** [comment]
OK what about this?

```ceylon
class Foo {
  print("a");
  shared new Bar() {
    print("b");
  }
  print("c");
  shared new Baz() {
    print("d");
  }
  print("e");
}
```

What should `Foo.Bar()` print, and what should `Foo.Baz()` print? Is it `a,b,c,e` and `a,c,d,e`?

**Comment by gavinking** [comment]
Exactly.

**Comment by tombentley** [comment]
> @tombentley I hope that's what you implemented, right?

Right

**Comment by chochos** [comment]
done for JS

**Comment by gavinking** [comment]
Thanks guys. Merged!
