### ISSUE TITLE
`undecidable canonicalization` for recursive alias definition 

### ISSUE THREAD

**Issue by sgalles** [ceylon/ceylon-spec#1257]
When this (broken) code is compiled
```ceylon
alias Foo => Foo();
```
the type checker prints out two errors
* expected : `type alias is circular: definition of 'Foo' is recursive, involving 'Foo'`
* not expected : `AliasVisitor caused an exception visiting FunctionType node: java.lang.RuntimeException: undecidable canonicalization at com.redhat.ceylon.compiler.typechecker.model.ProducedType.resolveAliases(ProducedType.java:2276)`

**Comment by gavinking** [comment]
Fixed, thanks @sgalles.
