### ISSUE TITLE
make Foo and [Foo+] disjoint as a special case

### ISSUE THREAD

**Issue by sgalles** [ceylon/ceylon-spec#1258]
Basically, this code could be analyzed as correct by the type checker :

```ceylon

shared class Foo(){}

void func(Foo|[Foo+] path){
    value a = switch(path)
              case(is Foo) 42
              case(is [Foo+]) 43; // ERROR : cases are not disjoint: '[Foo+]' and 'Foo'
             
}

```

**Comment by gavinking** [comment]
OK, so first I need a list of all types with which aren't subtypes of `Sequential`, but with which `Sequential` _does_ intersect: `Anything`, `Object`, `Iterable`, `Category`, `Correspondence`, `Ranged`, `List`, `Collection`. Am I missing any?

**Comment by gavinking** [comment]
Oh wait, in fact those are just the types that `Sequential` inherits. That makes it easy :-)

**Comment by gavinking** [comment]
Done!

**Comment by sgalles** [comment]
Cool, that was fast. And BTW, I was wondering : in issue https://github.com/ceylon/ceylon.language/issues/643 @lucaswerkmeister was suggesting to make `Singleton`final. Then, If `Sequence` was satisfied only by sealed or final classes, couldn't we also have the Foo/[Foo+] feature for **any Foo interface** that is not one of the interfaces satified by the classes that satify `Sequence` ?

**Comment by lucaswerkmeister** [comment]
Oh hey, I just discovered that I had worked around this issue previously :D see [here](https://github.com/ceylon/ceylon.ast/blob/7769a123716c511f62e2baba202ba8aa9770889d/source/ceylon/ast/core/CeylonExpressionTransformer.ceylon#L28)

**Comment by gavinking** [comment]
> If `Sequence` was satisfied only by sealed or final classes, couldn't we also have the Foo/[Foo+] feature for **any Foo interface** that is not one of the interfaces satisfied by the classes that satisfy `Sequence` ?

I think that's what I already implemented, isn't it. I guess I just forgot that `Singleton` was non-`final`.

**Comment by sgalles** [comment]
@gavinking It seems that this impl has broken the SDK build :
`[spread type must be a sequence type: 'Value|[Throwable]' is not assignable to 'Anything[]']  at 23:16-23:32 of Completable.ceylon `
https://gist.github.com/sgalles/53d6d224b691ea74df22

**Comment by gavinking** [comment]
Oh shit, I forgot about type parameters :-(

**Comment by sgalles** [comment]
> I think that's what I already implemented, isn't it? I guess I just forgot that Singleton was non-final

Ha ! OK :) Indeed, given that `Singleton` was still non-final I concluded that the feature did not yet encompass the interfaces. Cool.

**Comment by gavinking** [comment]
Now fixed.
