### ISSUE TITLE
Spec does not support package-qualified members

### ISSUE THREAD

**Issue by lucaswerkmeister** [ceylon/ceylon-spec#1259]
The parser and typechecker, quite reasonably IMO, accept this:
```ceylon
class C() {
    shared Null n = null;
}
Anything a = `package.C.n`;
```
However, the specification strictly speaking doesn’t allow this:
```antlr
MemberMeta: "`" PrimaryType "." MemberName TypeArguments? "`"
```
The same goes for `ConstructorMeta`.

**Comment by gavinking** [comment]
@lucaswerkmeister the `PrimaryType` can be qualified by `package.`. Closing.

**Comment by lucaswerkmeister** [comment]
Ah, right, this was before I learned that `package.Type` was supported too. Sorry.
