### ISSUE TITLE
CCE for metamodel of incomplete class def in IDE

### ISSUE THREAD

**Issue by sgalles** [ceylon/ceylon-spec#1265]
This top level (incomplete) code :
```ceylon
Foo f = `Foo`;

class Foo
```
in the IDE
`ExpressionVisitor caused an exception visiting TypeLiteral node: java.lang.ClassCastException: com.redhat.ceylon.compiler.typechecker.model.UnknownType cannot be cast to com.redhat.ceylon.compiler.typechecker.model.Class at com.redhat.ceylon.compiler.typechecker.model.Unit.getClassMetatype(Unit.java:1447)`

**Comment by gavinking** [comment]
Fixed, thanks.
