### ISSUE TITLE
Incorrect generic types for Java inner classes

### ISSUE THREAD

**Issue by jvasileff** [ceylon/ceylon-spec#1266]
Type inference for inner classes of generic Java classes can fail or be incorrect.

Using the following Java classes for testing:

```java
package sandbox.ceylon.snap.base;

import java.util.Date;

public class GenericOuter<T> {

    private T item;
    
    public GenericOuter(T item) {
        this.item = item;
    }

    public class Inner {
        public T item() {
            return item;
        }
    }

    public static GenericOuter<Date>.Inner dateInner() {
        return new GenericOuter<Date>(new Date()).new Inner();
    }
}
```

and

```java
package sandbox.ceylon.snap.base;

import java.util.Date;

public class DateInnerFactory {

    public GenericOuter<Date>.Inner dateInner() {
        return new GenericOuter<Date>(new Date()).new Inner();
    }

}
```

**Case 1: Using the Inner() constructor on an instance of GenericOuter**

This works as expected:

```ceylon
    GenericOuter<JDate> dateOuter1 = GenericOuter<JDate>(JDate()); // ok
    GenericOuter<JDate>.Inner dateInner1 = dateOuter1.Inner(); // ok
```

**Case 2: Using the static method dateInner()**

This works, but for the wrong reason:

```ceylon
    GenericOuter<JDate>.Inner dateInner2 = GenericOuter<JDate>.dateInner();
```

The generic parameter on the rhs *should be* irrelevant; `dateInner` is a static method.

**Case 3: Using the static method dateInner(), alternate**

Similar to case 2, but fails. This demonstrates the incorrect application of the type parameter.

```ceylon
    GenericOuter<JDate>.Inner dateInner3 = GenericOuter<Object>.dateInner();
    // error: GenericOuter<Object>.Inner is not assignable to GenericOuter<JDate>.Inner
```

**Case 4: Using a factory method in an unrelated class**

The Java method `DateInnerFactory.dateInner()`'s return type is incorrectly inferred (the type argument `Date` is lost):

```ceylon
    GenericOuter<JDate>.Inner dateInner4 = DateInnerFactory().dateInner();
    // error: GenericOuter<T>.Inner is not assignable to GenericOuter<JDate>.Inner
```

adding a type hint doesn't help:

```ceylon
    GenericOuter<JDate>.Inner dateInner5 = DateInnerFactory().dateInner() of GenericOuter<JDate>.Inner;
    // GenericOuter<JDate>.Inner does not cover GenericOuter<T>.Inner
```

**Comment by gavinking** [comment]
So I'm going to have to dig a but further, but it's not clear that this is the fault of the typechecker.

Because if I write the `dateInner()` function as a toplevel function in _Ceylon_, it works correctly.

**Comment by gavinking** [comment]
Indeed, this does appear to be a bug in the model loader, which is not setting the type argument of the qualifying type.

**Comment by gavinking** [comment]
Closing, now ceylon/ceylon-compiler#2132.

**Comment by FroMage** [comment]
Which qualifying type? Of what declaration? Can you be clearer?

**Comment by gavinking** [comment]
Well of the nested class that the function returns.

**Comment by FroMage** [comment]
So the return type of `GenericOuter.dateInner`?

**Comment by gavinking** [comment]
Yes.

**Comment by FroMage** [comment]
OK indeed you're right, I see it now, thanks.
