### ISSUE TITLE
support let and conditional expressions as interpolated expressions

### ISSUE THREAD

**Issue by jvasileff** [ceylon/ceylon-spec#1270]
Seems like the following should be supported w/o extra parens:

```ceylon
value one = "``if (true) then 1 else 2``";
```

I suppose this works just as well:

```ceylon
value two = "``false then 1 else 2``";
```

but I often prefer the former.

**Comment by gavinking** [comment]
OK, good idea.

@lucaswerkmeister this might impact you.

**Comment by lucaswerkmeister** [comment]
It does, thanks a lot for the heads-up.
