### ISSUE TITLE
StackOverflowError when compiling generics with defaults

### ISSUE THREAD

**Issue by jpragey** [ceylon/ceylon-spec#1281]
From [Compiler#2138](https://github.com/ceylon/ceylon-compiler/issues/2138)
StackOverflowError is thrown when compiling:
```ceylon
interface A<ActualB = B> {}
interface B<ActualB = B> {}
```

**Comment by gavinking** [comment]
Fixed, a little crudely...

**Comment by RossTate** [comment]
I thought we didn't allow B-like signatures because they lead to infinite types.

**Comment by gavinking** [comment]
Well, we don't. The trouble was it was blowing up the algorithm that _detects_ that problem.

**Comment by RossTate** [comment]
Ah, makes sense.
