### ISSUE TITLE
use of parameter before it is declared

### ISSUE THREAD

**Issue by gavinking** [ceylon/ceylon-spec#1287]
@jvasileff noticed that the typechecker accepts:

```ceylon
void testing(foo) {
    print(foo.size);
    String foo;
}
```

According to §5.1.5, it should not.

**Comment by gavinking** [comment]
So this was something I deliberately allowed in this commit from exactly 3 years ago today https://github.com/ceylon/ceylon-spec/commit/3ec0cee6ce21e96cc1cc6349bbca87602c48cef9. There's even a test for it. (Though the spec doesn't support it.)

It looks like the important usecase I had in mind was this one:

```ceylon
class Vector(Float x, Float y) {}
class Point(x, y) 
        extends Vector(x,y) {
    Float x; Float y;
}
```

Which, I have to admit, still looks good to me.

So the question is, what do I do now:

- change the spec to say that this is allowed, or
- carve out a smaller exception just for the `extends` clause of a class or constructor?

It's not totally clear to me.

**Comment by gavinking** [comment]
So I have pushed a proposed solution to this problem, which accepts a forward reference to a parameter with a split declaration _only_ in an `extends` clause, making `extends` a very special (irregular) case.

Does anyone object to this solution?

**Comment by lucaswerkmeister** [comment]
+1

**Comment by gavinking** [comment]
I'm going to close this issue, since I think the resolution is reasonable. But if anyone wants to object, I'm happy to continue the discussion here.
