### ISSUE TITLE
NPE for undefined type

### ISSUE THREAD

**Issue by sgalles** [ceylon/ceylon-spec#1289]
This (broken) code
```ceylon
class Foo() {
    Bar bar;
    this.bar = nothing;
}
```
compiled
`ExpressionVisitor caused an exception visiting QualifiedMemberExpression node: java.lang.NullPointerException at com.redhat.ceylon.compiler.typechecker.analyzer.ExpressionVisitor.visitQualifiedMemberExpression(ExpressionVisitor.java:6322)`

**Comment by gavinking** [comment]
This is a result of @d17c218cc0427769ba5e82c68236d6bc4327940d, which I don't really know the history behind. I discovered this stuff recently and wondered what it was about. @FroMage care to explain?
