### ISSUE TITLE
NPE for partial constructor def + undefined inherited type

### ISSUE THREAD

**Issue by sgalles** [ceylon/ceylon-spec#1290]
This (super broken) code
```ceylon
class Foo extends Bar{
    shared new (){}
}
```
compiled
`ExpressionVisitor caused an exception visiting Constructor node: java.lang.NullPointerException at com.redhat.ceylon.compiler.typechecker.analyzer.ExpressionVisitor.visit(ExpressionVisitor.java:8024)`

**Comment by gavinking** [comment]
Thanks, fixed.
