### ISSUE TITLE
Allow constructor annotations on init param classes

### ISSUE THREAD

**Issue by jvasileff** [ceylon/ceylon-spec#1294]
It would be nice to be able to apply constructor annotations on classes that have an initialization parameter list (rather than explicit constructors) for annotation types that would unambiguously apply to a constructor.

According to https://github.com/ceylon/ceylon-compiler/issues/2153, this request belongs here.

**Comment by gavinking** [comment]
This change is blocked by https://github.com/ceylon/ceylon.language/issues/680.

**Comment by gavinking** [comment]
OK, I have implemented typechecker support for this, that depends on https://github.com/ceylon/ceylon.language/issues/680, where we're still waiting for an implementation for JS.

**Comment by gavinking** [comment]
This is now a problem for the backend #2160. Closing.
