### ISSUE TITLE
NPE in IDE for malformed constructor declaration

### ISSUE THREAD

**Issue by sgalles** [ceylon/ceylon-spec#1305]
This (broken) code
```ceylon
class Foo{
    shared new Bar<>(){} 
}
```
in the IDE
`the 'ExpressionVisitor' caused an exception visiting a 'InvocationExpression' node: '"java.lang.NullPointerException"' at 'com.redhat.ceylon.compiler.typechecker.analyzer.ExpressionVisitor.visitInvocationPrimary(ExpressionVisitor.java:3411)'`

**Comment by gavinking** [comment]
Thanks.
