### ISSUE TITLE
StackOverflow in IDE for class alias + default type def

### ISSUE THREAD

**Issue by sgalles** [ceylon/ceylon-spec#1311]
This (broken) code example causes a stackoverflow in the IDE
```ceylon
class Foo<F>(){}
class Bar<B=Baz<>>() => Foo<B>();
class Baz<B=Baz<>>() => Foo<B>();
```

**Comment by gavinking** [comment]
It is looping at `ProducedType.involvesDeclaration(ProducedType.java:2304)`. That should be really easy to fix.

**Comment by gavinking** [comment]
Fixed. Thanks.
