### ISSUE TITLE
NPE in IDE for misplaced `use default parameter type` notation

### ISSUE THREAD

**Issue by sgalles** [ceylon/ceylon-spec#1312]
this (broken) code
```ceylon
shared class Foo<>(){}
```
in the IDE
`the 'ExpressionVisitor' caused an exception visiting a 'ClassDefinition' node: '"java.lang.NullPointerException"' at 'com.redhat.ceylon.model.typechecker.model.TypeParameter.hashCodeForCache(TypeParameter.java:180)'`

**Comment by gavinking** [comment]
Fixed, thanks.
