### ISSUE TITLE
type parameter variance inference for overloaded Java methods & constructors

### ISSUE THREAD

**Issue by jvasileff** [ceylon/ceylon-spec#1315]
For the Java class:
```java
import java.util.Comparator;

public class VarianceTesting<T> {
	public VarianceTesting(Comparator<? super T> comp) {}
//	public VarianceTesting() {}
}
```
type inference works well (T is inferred to be contravariant for purposes of type inference):
```ceylon
VarianceTesting<String> vt = VarianceTesting(nothing of JComparator<String>);
```
but if the second constructor is uncommented, T is inferred to be covariant:
```ceylon
VarianceTesting<Nothing> vt = VarianceTesting(nothing of JComparator<String>);    
```
The same happens with overloaded methods.

**Comment by gavinking** [comment]
@jvasileff so I clearly see what's going on here. At the point where we visit the arguments of the invocation, we have not yet resolved the overloaded version of the constructor that is being called. We know we are calling _some_ overloaded version of the constructor of `VarianceTesting`, but that's all we know. To resolve _which_ version, we first need to assign types to all the arguments.

Let's see if there's perhaps a point in the cycle a bit later where I could re-visit the arguments, but this might be really tricky.

**Comment by gavinking** [comment]
Nope, not doable. The point at which type arguments are inferred is earlier than the point at which overloads are resolved. And IIRC, it has to be this way.

**Comment by gavinking** [comment]
Wait, I lie; that's not true. 

Which means it should be doable.

**Comment by gavinking** [comment]
There, does that work for you @jvasileff ?

**Comment by jvasileff** [comment]
@gavinking looks great! It fixed my original issue, and I tested extends and super with overloaded constructors, instance methods, and static methods.

**Comment by gavinking** [comment]
Great, thanks! But I feel uncomfortable closing this issue without any kind of tests for it. And I still have no way to test overloading in the typechecker :-/

**Comment by gavinking** [comment]
We need to add a test for this to either `ceylon.language` or `ceylon.compiler`. I think these kinds of tests currently reside in `ceylon.compiler`. WDYT, @FroMage @quintesse, should we put it there?

**Comment by gavinking** [comment]
Moved to the compiler.

<https://github.com/ceylon/ceylon-compiler/issues/2310>
