### ISSUE TITLE
Make Set<Object> cover Set<Anything>

### ISSUE THREAD

**Issue by lucaswerkmeister** [ceylon/ceylon-spec#1319]
With #535, `Set<Anything>` (`Set` constraints its type argument to satisfy `Object`) is a legal type (though the type argument remains illegal when *instantiating* a `Set`). This means that declarations can have the type `Set<Anything>`, which to users is less useful than `Set<Object>` because knowledge about the type was lost.

However, we know that no `Set<Null>` actually exists, and can therefore say that `Set<Anything>` covers `Set<Object>`. More generally: For a covariantly parameterized type `X<T>`, `X<T1>` covers `X<T2>` if `T2` is the most general type argument allowed (intersection of `satisfies` constraints with union of `of` constraints?) and `T2 satisfies T1`.

**Comment by gavinking** [comment]
... and ye shall receive, @lucaswerkmeister. :-)

**Comment by gavinking** [comment]
Note that #1319, #1318, and #1314 are all waiting for me to decide precisely what to do about upper bounds involving type parameters. Which is now solvable thanks to #535. Yay!

**Comment by lucaswerkmeister** [comment]
Shouldn’t this be accepted now?
```ceylon
Set<Anything> s1 = nothing;
Set<Object> s2 = s1 of Set<Object>;
```
> error: specified type does not cover the cases of the operand expression: `Set<Object>` does not cover `Set<Anything>`
```ceylon
Set<Object> s2 = s1 of Set<Object>;
                 ^
```
1 error

**Comment by gavinking** [comment]
Shit. I got the hard case, but missed the easy case.

**Comment by RossTate** [comment]
Note that making this part of subtyping makes subtype-checking not always terminate. Maybe it's fine for coverage though?

**Comment by gavinking** [comment]
@RossTate that's what I'm hoping, yes. Though I have not quite managed to convince myself of it yet...

**Comment by gavinking** [comment]
@lucaswerkmeister fixed. I missed one exit point from the method :-)

**Comment by RossTate** [comment]
I think this is fine so long as you only do it shallowly. As an example of things that cause problems, consider `Foo<out X> given X satisfies Foo<X>` and `Foo<Object>`. So what "shallowly" means precisely, I'm not sure yet.

**Comment by gavinking** [comment]
@RossTate well that's all I've specified, I think.

**Comment by RossTate** [comment]
I'm not sure how to interpret your spec for my example. Also, is there a practical need for this yet? Wildcards have this feature, but when I did my analysis I found that it was used only a handful of times in millions of lines of generic Java code. Ceylon has a different user base, so things might be different, but I thought you only liked adding things if you found practical need for them. Also, if you let me know the practical needs, I can help you come up with a well-behaved spec that properly serves the actual needs.

**Comment by gavinking** [comment]
Well I guess you're thinking about the issue of upper bounds involving the type parameter, which is the issue I mentioned [above](https://github.com/ceylon/ceylon-spec/issues/1319#issuecomment-106943134). As I say, this is already a problem that is causing two other bugs, and I need a consistent solution in all three cases. But I have a sketch of what that would look like already.

**Comment by RossTate** [comment]
Okay. And what about whether this feature is actually useful at all, including the non-recursive bounds?

**Comment by gavinking** [comment]
Done. Closing.
