### ISSUE TITLE
Variable assigned in an if expression not visible in the else clause

### ISSUE THREAD

**Issue by renatoathaydes** [ceylon/ceylon-spec#1320]
This code does not compile:

```ceylon
value list = { 1, "2" };
value firstInteger =
        if (is String first = list.first)
        then 0 else first;
```

Error:

```
Missing type arguments to generic declaration: first declares type parameters Item
```

But given that `list.first` may only produce `Integer|String` in the above code, that should work.

The reason I was trying to test for one type, but actually be interested in the other type of the union, was that to check for the actual type was too expensive (not in this example, but in my case the type was a generic type, and as discussed in the forum it can be very slow to test for generic types).

**Comment by gavinking** [comment]
Huh, surely you mean:

```ceylon
    value list = { 1, "2" };
    value firstInteger =
            if (is String first = list.first)
            then first else 0;
```

Which compiles perfectly fine for me. I think you have some other `first()` function floating around...

**Comment by renatoathaydes** [comment]
No... I meant what I had written. I want an Integer, not a String.

**Comment by gavinking** [comment]
What you wrote originally doesn't compile because `first` is not in scope in the `else` clause.

**Comment by renatoathaydes** [comment]
I know. But I disagree that should be the case.

**Comment by gavinking** [comment]
I get the message: `Function or value does not exist: first`

**Comment by gavinking** [comment]
> But I disagree that should be the case.

Well that's always been the case with variables defined in `if` clause conditions. You can use `!is` if you like:

```ceylon
    value firstInteger =
            if (!is String first = list.first)
            then first else 0;
```

Or you can use `let`:

```
    value firstInteger =
            let (first = list.first)
            if (is String first)
            then 0 else first;
```

**Comment by renatoathaydes** [comment]
Wow, you're right, I was writing the sample code inside another class :( which had another first in scope.... that just changes the error message....

Thanks for the alternatives....

But this scoping without `{}`, which is the usual scoping marker in my mind, seems weird to me....

**Comment by gavinking** [comment]
@renatoathaydes I guess I can see that, but since it's the same rule as for an ordinary `if` I would _much_ prefer to keep it this way.

**Comment by pthariensflame** [comment]
@gavinking @renatoathaydes I'm not necessarily advocating that the following is a *good* idea, but it is at least *possible* to make every `if`, regardless of whether they are expressions or statements, keep track of declared variables in every branch.  They would just end up with different (and mutually disjoint) types in different branches.  *E.g.*,

``` ceylon
Integer|Float|String x = makeAnAmbiguousValueSomehow();
if (is String y = x) {
    doSomethingWithStrings(y); // `y` has the type `String`
} else {
    doSomethingWithIntegersOrFloats(y); // `y` has the type `Integer|Float`
}
```

**Comment by gavinking** [comment]
Sure but the thing is that I just _don't like that_. You're defining a variable `y` saying explicitly that it's a `String` .... except where it's not. To me that's pretty confusing.

If that's what you want, it's _so_ much clearer to write:

```ceylon
Integer|Float|String x = makeAnAmbiguousValueSomehow();
value y = x;
if (is String y) {
    doSomethingWithStrings(y); // `y` has the type `String`
} else {
    doSomethingWithIntegersOrFloats(y); // `y` has the type `Integer|Float`
}
```

At least that's how I've always viewed this.

**Comment by pthariensflame** [comment]
I agree; I just felt like I should point out that the possibility existed.

**Comment by quintesse** [comment]
> At least that's how I've always viewed this.

Although I understand where you're coming from I'm not sure I'd always appreciate it in practise. The short-hand form of test + assignment in one is a really nice construct. That you suddenly have to forgo it and switch to a more verbose form when you want to use `y` in the else block is a shame. That `y` is a different type in the else block might seem strange but is very useful, on the other hand not being able to do so at all might also confuse people ("why does it work when I use this syntax but not when I use this very similar looking syntax?").

**Comment by gavinking** [comment]
OK then, what about:

```ceylon
    if (List<Object> list = getList(), 
        exists first = list.first, 
        is String first) {
        //...
    }
    else {
        //...
    }
```

Clearly `first` isn't available in `else`.

What about:

```ceylon
    if (exists k->v = maybeEntry) { .... } else { ... }
```

Clearly `k` and `v` aren't available in `else`. Well, not unless you want to set the _both_ to null. But that's a can of worms.

I say we keep this simple and don't make the suggested change.

**Comment by quintesse** [comment]
I'm not necessarily advocating this change but why would what you suggest be a can of worms? It's not particularly useful to have `first`, `k` and `v` to be `null` but it would indeed be the logical thing to do and I don't immediately see what kind of problems it could cause.

**Comment by gavinking** [comment]
I'm closing the issue.
