### ISSUE TITLE
Harmonize implementation of native and java overloads

### ISSUE THREAD

**Issue by quintesse** [ceylon/ceylon-spec#1321]
See https://github.com/ceylon/ceylon-model/commit/4e70212b7620123848cdc3900fffcc270d546722

Basically boils down to the fact that the implementation for native declarations abuses the overloads system meant for Java overloading but it does so in a very inconsistent way. The implementations will never have any code in common but at least the models for native declarations should be as similar as possible as the ones generated for Java overloading.

**Comment by gavinking** [comment]
@quintesse is this done?

**Comment by quintesse** [comment]
AS far as I'm concerned it is.
