### ISSUE TITLE
Subtyping broken for local types

### ISSUE THREAD

**Issue by FroMage** [ceylon/ceylon-spec#1323]
In the metamodel we use pretend interface types as containers for local types so we can put their type arguments there, and this got broken by a recent commit to `Type.getSupertypeInternal`:

```java
                    Type stqt =
                            supertype.trueQualifyingType();
                    Type tqt =
                            type.trueQualifyingType();
                    if (stqt==null) {
                        if (tqt!=null) {
                            //probably extraneous!
                            return false;
                        }
                    }
```

Where `supertype.trueQualifyingType()` is null but not `tqt` (which does contain the pretend interface).

I can only give you runtime metamodel code to reproduce this behaviour.

**Comment by FroMage** [comment]
The commit is ceylon/ceylon-model@cacb1fd914e22ab0c8213d0b24ab89874daf68a7

**Comment by gavinking** [comment]
@FroMage well nothing actually changed in those lines, which are from `isSubtypeOfInternal()`, not `getSupertypeInternal()`. All I did was extract a couple of methods without changing anything else.

Without knowing a little bit more about precisely what broke it's hard for me to know what to do here.

**Comment by FroMage** [comment]
Try the `StructureTest.testKlsInlineObject()` test.

**Comment by gavinking** [comment]
I have no clue. That doesn't give me any clue about what might be wrong.

**Comment by gavinking** [comment]
So it appears that this is actually a result of the optimized path in `getSupertype()`. Because I guess I throw away the qualifying type.

**Comment by gavinking** [comment]
Fixed.

**Comment by FroMage** [comment]
Yes thanks.
