### ISSUE TITLE
Type of tuple elements in `for` loop

### ISSUE THREAD

**Issue by FroMage** [ceylon/ceylon-spec#1324]
This used to work:

```ceylon
    void tupleOfIntegers([Integer, Integer, Integer] seq) {
        for (element in seq) {
            print(element + 5);
        }
    }
```

But now fails with `left operand must be of summable type: 'Integer|Integer|Integer|Nothing' ('Integer') is not a subtype of 'Summable'` on `print(element + 5)`.

Is this normal?

**Comment by gavinking** [comment]
This is fixed now.

**Comment by FroMage** [comment]
Thanks.
