### ISSUE TITLE
`UnknownType` error missing from supertype subtyping checks

### ISSUE THREAD

**Issue by FroMage** [ceylon/ceylon-spec#1325]
I have a test for a class `Foo` whose supertype is missing, and so the model loader fills in an `UnknownType` for its supertype, and when trying to use this class as an instance of `Bar` (a supertype of the missing supertype of `Foo`, which is not missing here), the typechecker properly declares that it's not assignable, but fails to give me the error reported on the `UnknownType` because it gets lost in `Class.getExtendedType()` because `et` is not a `Class`, it's an `UnknownType` and so `AnalyzerUtil.typingMessage` can't use the error that should be returned by `type.getFirstUnknownTypeError(true)` as was previously the case.

This should be fixed somehow, because the resulting error is confusing, since it does not make any sense unless we can explain that the supertype of `Foo` is missing, because we _known_ that it is a subtype of `Bar` and the code would typecheck if the supertype was not missing.

**Comment by gavinking** [comment]
So wait, what you have is:

```ceylon
interface Foo {}
class Baz() satisfies Bar {}

Foo foo = Baz();
```

And you don't like the message:

    Specified expression must be assignable to declared type of foo: 'Baz' is not assignable to 'Foo'

Because it doesn't let you know that `Baz` has missing supertypes?

**Comment by gavinking** [comment]
So what you would like to see is:

    Specified expression must be assignable to declared type of foo: 'Baz' is not assignable to 'Foo' ('Baz' has missing supertypes)

Is that right?

**Comment by FroMage** [comment]
Not at all, the extra error message comes from the `UnknownType` itself, it's set by the model loader when a jar is missing in `AnalyzerUtil.typingMessage` at `String unknownTypeError = type.getFirstUnknownTypeError(true);`

**Comment by gavinking** [comment]
I dunno, I have no idea, I didn't work on that stuff, and there are no tests for it AFAIK.

**Comment by FroMage** [comment]
`CMRTests.testMdlAetherMissingDependencies()`

**Comment by FroMage** [comment]
This change in `Class.getExtendedType()` fixes it and does not break any typechecker tests:

```
            return et;
//            return unit.getAnythingType();
```

Shall I commit this?

**Comment by gavinking** [comment]
> Shall I commit this?

No. Not like that, since `Class` would no longer be protected against circularities in its inheritance hierarchy.

What is `et` if it is not a class? An `UnknownType`? I'll let you return that if you want.

**Comment by gavinking** [comment]
i.e. _only_ in the case that it's an `UnknownType`.

**Comment by FroMage** [comment]
Yes it's that. Thanks.

**Comment by gavinking** [comment]
Done.

**Comment by FroMage** [comment]
Fixed, thanks.
