### ISSUE TITLE
make generic type arg inference work on a very indirected generic function ref

### ISSUE THREAD

**Issue by gavinking** [ceylon/ceylon-spec#1328]
From @jvasileff, it doesn't look like there's any good reason why this is not accepted:

```ceylon
alias Wrapper<Box> given Box<E>
    =>  <Element>
        =>  Box<Element>(Element);

{Box<A>|Box<B>*} wrapConcat2<Box, A, B>(
        Wrapper<Box> wrap,
        {A*} as, {B*} bs)
        given Box<E>
    =>  as.map(wrap).chain(bs.map(wrap));
```

**Comment by jvasileff** [comment]
To be clear, I didn't really have an opinion on whether the alias should be allowed in the first place.

Originally, I was trying to make sense of:
```ceylon
alias AdditionLikeOperation
        => <Number> given Number satisfies Summable<Number>
                => Number(Number,Number);
```
which sort of looks like a reference to a type function, but also looks like a type function that returns a type function, with an absent parameter list on `AdditionLikeOperation`. The first interpretation doesn't seem to add value, so I experimented with the second.

Now if currying (or anonymous type functions?) were fully supported, then it seems like this would be possible:

```ceylon
alias CurriedMapTypeFunction
    =>  <Key> given Key satisfies Object
    =>  <Item>
    =>  Map<Key, Item>;
```
or the currently allowed:
```ceylon
alias CurriedMapTypeFunction<Key>
        given Key satisfies Object
    =>  <Item>
    =>  Map<Key, Item>;
```
or:
```ceylon
alias CurriedMapTypeFunction<Key><Item>
        given Key Satisfies Object
    =>  Map<Key, Item>;
```
It seems like all of this might be useful, but unnecessary.

Is there a different or better way to interpret `AdditionLikeOperation` and `Wrapper` that I'm missing, and that supports them being valid?

**Comment by gavinking** [comment]
@jvasileff stick `<....>` in the right places and you can write all those types.

**Comment by jvasileff** [comment]
Ok, that helps, until you try to use it:

```ceylon
alias CurriedMapTypeFunction
    =>  <Key> given Key satisfies Object
    =>  <<Item> => Map<Key, Item>>;

alias StringKeyedMap => CurriedMapTypeFunction<String>;
// Does not accept type arguments: CurriedMapTypeFunction is not a generic type
```
likewise, you cannot take a reference to the `Map` type constructor:
```ceylon
alias MyMapFunction => Map;
// Implicit use of default type arguments is deprecated (change to Map<>)
```
you can of course do:
```ceylon
alias MyMapFunction2<Key, Value> given Key satisfies Object => Map<Key,Value>;
```
But now I realize that `AdditionLikeOperation` doesn't really work right now either:
```ceylon
alias AdditionLikeOperation
        => <Number> given Number satisfies Summable<Number>
                => Number(Number,Number);

AdditionLikeOperation<Integer> addIntegers = nothing;
 //Does not accept type arguments: AdditionLikeOperation is not a generic type

void doSomething(AdditionLikeOperation addOp) {}

void testDoSomething() {
    doSomething(plus); // error
}
```

**Comment by gavinking** [comment]
Hrm. OK, I thought all that worked. Anyway it would probably explain why the original example did not work. So we can't apply references to type constructors. Well that sounds like it's fixable.

**Comment by gavinking** [comment]
Alright, @jvasileff I think this is about done and I have caught most of the cases where aliases can come into play. Can you find anything else that doesn't work?

**Comment by jvasileff** [comment]
It looks like defining, applying, and passing around type functions that return type functions that return... works pretty well.

But the original case of applying a type function (that returns a type function) to a higher order generic argument still causes problems:

```ceylon
alias Wrapper<Box> given Box<E>
    =>  <Element>
        =>  Box<Element>(Element);

{Box<A>|Box<B>*} wrapConcat2<Box, A, B>(
        Wrapper<Box> wrap,
        {A*} as, {B*} bs)
        given Box<E> {

    // not good #1
    {Nothing*} parta = as.map(wrap<A>);
    {Nothing*} partb = bs.map(wrap<B>);

    // not good #2
    <E> => Box<E>(E) badWrap2 = wrap;
    {Nothing*} parta2 = as.map(badWrap2<A>);
    {Nothing*} partb2 = bs.map(badWrap2<B>);

    // good
    value goodWrapA = wrap<A>; // Inferred type  Box<A>(A)
    value goodWrapB = wrap<B>; // Inferred type  Box<B>(B)
    {Box<A>*} parta3 = as.map(goodWrapA);
    {Box<B>*} partb3 = bs.map(goodWrapB);
    return parta3.chain(partb3);
}
```

**Comment by gavinking** [comment]
OK, so I just missed one spot. Fixed, and test added. Closing now!

**Comment by jvasileff** [comment]
@gavinking when the type argument to `wrap` is inferred, we now get the correct:
```ceylon
Box<A> collecting(A element)
```
but if the type argument is explicitly provided while constructing an argument to a function (i.e. `map(wrap<A>`), `wrap<A>` becomes:
```ceylon
Nothing collecting(A element)
```
The `wrapConcat2` example above still compiles, but it should produce errors in the 'not good' sections.

**Comment by gavinking** [comment]
@jvasileff I don't follow, when I write in:

    as.map<Box<A>>(wrap).chain(bs.map<Box<B>>(wrap))

The code is accepted (which I think is correct). And when I write in:

    as.map<A>(wrap).chain(bs.map<B>(wrap))

it's rejected, which I again think is correct, with the messages:

    Argument must be assignable to parameter collecting of map in {A*}: Box<A>(A) is not assignable to A(A)
    Argument must be assignable to parameter collecting of map in {B*}: Box<B>(B) is not assignable to B(B)
    Specified expression type must be assignable to declared return type: {A|B*} is not assignable to {Box<A>|Box<B>*}

Is there something wrong there?

**Comment by jvasileff** [comment]
This should be rejected, but isn't:
```ceylon
{Nothing*} parta = as.map(wrap<A>);
```
These are both properly rejected:
```ceylon
{Nothing*} partab = as.map(wrap);
{Nothing*} partaa = as.map<Box<A>>(wrap<A>);
```
since the return `{Box<A>*}` is not assignable to `{Nothing*}`.

**Comment by gavinking** [comment]
OK, so there is a big diff b/w:

    as.map(wrap<A>)

And:

    as.map(let (f=wrap<A>) f)

Which clearly should be the same. In the first one it looks like the expression `wrap<A>` is not being assigned a type.

**Comment by jvasileff** [comment]
Exactly. I wish I would have thought to write it out that way

**Comment by gavinking** [comment]
OK, cool, that one was easy (and a bit silly).
