### ISSUE TITLE
NPE for incomplete inlined anonymous class used as default value 

### ISSUE THREAD

**Issue by sgalles** [ceylon/ceylon-spec#1336]
This (broken) code in the IDE or with the JS compiler :
```ceylon
shared class Foo(){}
shared class Bar(shared Foo b = object extends Foo()){}
```
`the 'InheritanceVisitor' caused an exception visiting a 'ObjectExpression' node: '"java.lang.NullPointerException"'`

**Comment by gavinking** [comment]
Fixed, thanks @sgalles!
