### ISSUE TITLE
forbid empty `let`

### ISSUE THREAD

**Issue by sgalles** [ceylon/ceylon-spec#1339]
This should not compile
```ceylon
value a = let() 42;
```

**Comment by gavinking** [comment]
Fixed, thanks.

**Comment by sgalles** [comment]
@gavinking  I'm asking just in case : you really did want to commit it on branch 1129 ?

**Comment by gavinking** [comment]
Ooops.

On Sun, Jun 7, 2015 at 12:16 AM, Stephane Gallès <notifications@github.com>
wrote:

> @gavinking <https://github.com/gavinking> I'm asking just in case : you
> really did want to commit it on branch 1129 ?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ceylon/ceylon-spec/issues/1339#issuecomment-109654293>
> .
>



-- 
Gavin King
gavin@ceylon-lang.org
http://profiles.google.com/gavin.king
http://ceylon-lang.org
http://hibernate.org
http://seamframework.org
