### ISSUE TITLE
NPE for undefined enumerated instance

### ISSUE THREAD

**Issue by sgalles** [ceylon/ceylon-spec#1342]
With this code  :
```ceylon
abstract class Foo() of bar{}
```
`the 'InheritanceVisitor' caused an exception visiting a 'CaseTypes' node: '"java.lang.NullPointerException"' at 'com.redhat.ceylon.compiler.typechecker.analyzer.InheritanceVisitor.collectCaseValues(InheritanceVisitor.java:497)'`

**Comment by gavinking** [comment]
It looks like this is already fixed, at least on the `1129` branch.

**Comment by gavinking** [comment]
After merge, this is fixed.
