### ISSUE TITLE
Type arg inference bug

### ISSUE THREAD

**Issue by FroMage** [ceylon/ceylon-spec#1346]
This used to work:

```ceylon
    Class<MemoryMXBean> klass = nothing;
    value on = ManagementFactory.getPlatformMXBean(klass).objectName;
```

Where `getPlatformMXBean` is of type `function ManagementFactory.getPlatformMXBean<T>(Class<T>? arg0) => T`

**Comment by gavinking** [comment]
@FroMage is that better now?

**Comment by FroMage** [comment]
Yes thanks!
