### ISSUE TITLE
Abbreviation Boolean(String->String) not allowed according to spec

### ISSUE THREAD

**Issue by tombentley** [ceylon/ceylon-spec#1349]
As I read the type abbreviation productions in the spec (§3.2.8.), a `CallableType` can have a `TypeList` between the parens which goes via `VariadicType` to `UnionType`, thus precluding the possibility of having a callable type with a `EntryType` argument. However, the typechecker accepts `Boolean(String->String)` just fine.

**Comment by gavinking** [comment]
No, you misread it. It's only if the last element is variadic that you can't have an `EntryType` there. that's because in the language generally, `->` has a lower precedence than `*`. The non-variadic elements of a `TypeList` are `(UnionType | EntryType) "="?`.

**Comment by tombentley** [comment]
Ah, yes you're right. Sorry.
