### ISSUE TITLE
NPE for partial constructor delegation

### ISSUE THREAD

**Issue by sgalles** [ceylon/ceylon-spec#1350]
This (incomplete) code
```ceylon
class Foo{
    shared new () extends {}
}
Foo f = Foo();
```
compiled
`the 'MethodOrValueReferenceVisitor' caused an exception visiting a 'ClassDefinition' node: '"java.lang.NullPointerException"' at 'com.redhat.ceylon.compiler.java.loader.MethodOrValueReferenceVisitor.visit(MethodOrValueReferenceVisitor.java:230)'`

**Comment by gavinking** [comment]
This isn't actually a typechecker issue since `MethodOrValueReferenceVisitor` isn't part of the typechecker, but sure, I'll take a look at it anyway I guess.

**Comment by sgalles** [comment]
Oops ! Yes, of course. Just let me know if you prefer to move this issue in `ceylon-compiler` eventually.

**Comment by gavinking** [comment]
@sgalles looks like it was already fixed by ceylon/ceylon-compiler@5d4783d122696c6db2df24926cba08e15e4f86dc.
