### ISSUE TITLE
"No native implementation for backend" error for Integer, String, etc when both backends disabled

### ISSUE THREAD

**Issue by gavinking** [ceylon/ceylon-spec#1358]
When I disable both backends in the IDE, I get bogus `No native implementation for backend` errors on usages of `native` language module classes.

**Comment by davidfestal** [comment]
@gavinking : this works for now.

**Comment by gavinking** [comment]
Excellent, thanks!!

**Comment by gavinking** [comment]
Confirmed. Closing.
