### ISSUE TITLE
NPE in IDE for incomplete code in conjunction with member interface and type param

### ISSUE THREAD

**Issue by sgalles** [ceylon/ceylon-spec#1361]
This incomplete and broken code in the IDE
```ceylon
interface Bar<A>{
		shared interface Baz{}
	}
	
	class Foo() satisfies Bar<Integer>{
		Baz{}
	}
```
`the 'ExpressionVisitor' caused an exception visiting a 'InvocationExpression' node: '"java.lang.NullPointerException"' at 'com.redhat.ceylon.model.typechecker.model.ModelUtil.aggregateTypeArguments(ModelUtil.java:1005)'`

**Comment by gavinking** [comment]
Fixed, thanks.
