### ISSUE TITLE
class without parameters must declare at least one shared constructor

### ISSUE THREAD

**Issue by sgalles** [ceylon/ceylon-spec#1363]
This should be rejected
```ceylon
class Foo{
    abstract new abs(){}
}
```

**Comment by gavinking** [comment]
Spec say:

> If a class does not specify an initializer parameter list, it must have at least one constructor

But indeed, I agree that the rule should be something more like:

> If a class does not specify an initializer parameter list, it must have at least one **shared** constructor

Agreed?

**Comment by sgalles** [comment]
Ah, yes indeed, I was actually trying to figure out if the issue was actually about the visibilty of the constructor when I was your message. So, yes, definitly *shared*. I renamed the issue.

**Comment by gavinking** [comment]
Fixed AFAICT, but I'm not sure how this impacts @quintesse's code that handles `native`. He needs to review this change.
