### ISSUE TITLE
disallow qualifying constructors with *instances*

### ISSUE THREAD

**Issue by jvasileff** [ceylon/ceylon-spec#1366]
This is currently allowed:
```ceylon
myPoint.withCartesian(1.0, 2.0);
```
where `withCartesian` is a constructor. I suggest that this be disallowed, requiring:
```
Point.withCartesian(1.0, 2.0);
```
for two reasons:

1. Constructors are not polymorphic
1. The first can be confusing, since it implies that the instance matters, as it does with immutable builder methods that look similar.

**Comment by lucaswerkmeister** [comment]
:+1:

**Comment by sgalles** [comment]
Yes indeed, and BTW, it also makes the current behavior regarding name collision somewhat suprising. A constructor can *hide* a member of its class
This compiles.
```ceylon

interface Bar{
	shared Integer foo() => nothing;
}

class Foo satisfies Bar{
	shared new (){}
	shared new foo(){}
}

shared void run(){
	Foo a = Foo().foo();
}
```

**Comment by sgalles** [comment]
Ah, an interesting variation of the same problem. This should not compile but curently is accepted.
```ceylon
class Foo {
	shared new (){}
	shared new foo{}
}

class Bar() extends Foo(){
}

shared void run(){
	print(Bar.foo.hash); // should be rejected	 by the typechecker
}
```

**Comment by quintesse** [comment]
This makes the following test fail: ceylon/ceylon-compiler#2234

Specifically this line:

    bug2234_check(oi.foo.name=="foo", "spec#1129.3");

But I guess this isn't allowed anymore then?

**Comment by quintesse** [comment]
I commented out some tests in the language module related to this so I can continue testing, please re-enable or change them when it's apparent what has to be done: ceylon/ceylon.language@99801f65f9f2512b2d9adbbd3a4d7fa74cd39120

**Comment by gavinking** [comment]
@quintesse that change looks right to me.

**Comment by quintesse** [comment]
@gavinking I'm afraid I don't know what it is you are referring to. What change looks right?

**Comment by gavinking** [comment]
@quintesse your commit to the language module tests

**Comment by quintesse** [comment]
Well I'm just commenting out some tests that don't work anymore, that can't be right can it? :)
Or do you mean they should just be removed?
But I guess the person that added them wanted to test *something*

**Comment by gavinking** [comment]
Well the whole point of this issue is to disallow something we used to allow!

**Comment by gavinking** [comment]
I'm closing this issue and opening #1431 for the separate problem noticed by @sgalles.
