### ISSUE TITLE
type checking on higher ranked references to generic class methods

### ISSUE THREAD

**Issue by jvasileff** [ceylon/ceylon-spec#1371]
This is allowed:

```ceylon
<WhateverIWant> => WhateverIWant valueFactory = String.map;
Nothing isNothing = valueFactory<Nothing>;
```

**Comment by jvasileff** [comment]
I'm guessing this is related:

```ceylon
Iterable.map({1,2,3});
// The ExpressionVisitor caused an exception visiting a InvocationExpression node: "java.lang.ClassCastException"
```

**Comment by gavinking** [comment]
This problem isn't even limited to code using type constructors. I can reproduce the problem like this:

    String valueFactory = String.map;

**Comment by gavinking** [comment]
I have fixed the `Iterable.map({1,2,3})` example. Still working on the version where there is not parameter list.

**Comment by gavinking** [comment]
Done. @jvasileff could you verify this for me, and make sure I didn't break anything? Thanks.

**Comment by jvasileff** [comment]
Looks good to me - all of my test code that type-checked before still does. I can't actually run code that I thought I could at some point in the past, but that appears totally unrelated.

**Comment by gavinking** [comment]
Excellent, thanks.
