### ISSUE TITLE
Type problem with natives

### ISSUE THREAD

**Issue by davidfestal** [ceylon/ceylon-spec#1372]
the following code : 
``` Ceylon
shared native class C() {
    shared native C returnMe();
}

shared native("jvm") class C() {
    shared native("jvm") C returnMe() => nothing;
}
```

produces the following error on the `jvm` overload of `returnMe()` : 
`Native implementation must have the same return type as native header: returnMe in C must have the type C`

Since both types contain declarations that are seen non-equal, they are seen non-equal.

This produces many subtyping-algorithm errors

**Comment by quintesse** [comment]
Done

**Comment by quintesse** [comment]
Btw @davidfestal , this might have repercussions for the IDE, you might need to check that.
