### ISSUE TITLE
bug in refinement validation

### ISSUE THREAD

**Issue by gavinking** [ceylon/ceylon-spec#1377]
Noticed by @jvasileff this is accepted by the typechecker:

```ceylon
class Options(shared default String abc) {}

class OptionsExt(String abc0) extends Options(abc0) {}

class OptionsExtExt() extends OptionsExt("initial") {
    shared actual variable String abc = "initial";
}
```

But this is not:

```ceylon
class Options(shared default String abc) {}

class OptionsExt(String abc) extends Options(abc) {}

class OptionsExtExt() extends OptionsExt("initial") {
    // May not inherit two declarations with the same name
    // that do not share a common supertype: abc is defined
    // by supertypes OptionsExtExt and Options
    shared actual variable String abc = "initial";
}
```

That's wrong; it should be accepted.

**Comment by Zambonifofex** [comment]
@gavinking Except for the commented lines, the two blocks of code are literally the same...

**Comment by sgalles** [comment]
@Zambonifofex yes indeed, it must be
```ceylon
class Options(shared default String abc) {}
	
	class OptionsExt(String abc) extends Options(abc) {}
	
	class OptionsExtExt() extends OptionsExt("initial") {
		// May not inherit two declarations with the same name
		// that do not share a common supertype: abc is defined
		// by supertypes OptionsExtExt and Options
		shared actual variable String abc = "initial";
	}
```

**Comment by Zambonifofex** [comment]
@sgalles I'm confused. @gavinking seem to have indeed renamed `abc0` to `abc`, but in the opposite block of code to the one you are suggesting...

**Comment by sgalles** [comment]
@Zambonifofex I'm confused too :)
@gavinking I guess that `abc0` should be in the example that **is** accepted by the typechecker. Not the other way around, right ?

**Comment by jvasileff** [comment]
@sgalles I think you have it right. For the definitive version of what should work per this issue but doesn't, see the test case. That is, both should work, but the `abc` version doesn't.

It's still a bit odd (but convenient) I think to allow declarations of a supertype to be shadowed, but I guess that's for a separate issue.

**Comment by gavinking** [comment]
Fixed.
