### ISSUE TITLE
defaulted type parameter strangeness

### ISSUE THREAD

**Issue by jvasileff** [ceylon/ceylon-spec#1380]
With `util.ceylon`:

```ceylon
import ceylon.language.meta.declaration {
    Declaration
}
interface DList<Element=Declaration> satisfies List<Element> {}
```

and `run.ceylon`:

```ceylon
void food(DList<> dlist) => dlist.getFromFirst(0);
```

compiling with the CLI produces errors. In some cases, but not here, the errors go away if the import is also made in `run.ceylon`. It works with everything in one file.

This happens in Eclipse too, but less reliably and seems dependent on caching and possibly ordering. The example above *does* compile in Eclipse for me, in the project I tested it with. But others don't.

The errors:

```
$ ceylon compile simple
source/simple/run.ceylon:1: error: could not determine type of method or attribute reference: 'getFromFirst' of 'DList'
void food(DList<> dlist) => dlist.getFromFirst(0);
                                  ^
source/simple/run.ceylon:1: error: could not determine type of function or value reference: 'dlist'
void food(DList<> dlist) => dlist.getFromFirst(0);
                            ^
source/simple/run.ceylon:1: error: could not determine type of function or value reference: 'dlist'
void food(DList<> dlist) => dlist.getFromFirst(0);
                            ^
3 errors
Note: Created module simple/1.0.0
ceylon compile: There were 3 errors
```

and for JS:

```
$ ceylon compile-js
Error: Errors found. Compilation stopped.
Note: Created module simple/1.0.0
error encountered [could not determine type of method or attribute reference: 'getFromFirst' of 'DList'] at 1:34-1:45 of run.ceylon
ceylon compile-js: 1 errors.
```

**Comment by gavinking** [comment]
So I can reproduce this in a single file:

```ceylon
import ceylon.language.meta.declaration {
    Declaration
}
void food(DList<> dlist) => dlist.getFromFirst(0);
interface DList<Element=Declaration> satisfies List<Element> {}
```

The key seems to be that `Declaration` is a type imported from a different package. (Doesn't need to be in a different module.)

**Comment by gavinking** [comment]
This is fixed, but it looks like the fix impacts other new stuff I didn't know about. @davidfestal @quintesse ?

**Comment by quintesse** [comment]
All backend tests complete without problems including those for everything native so I don't think you broke anything with this change there.
