### ISSUE TITLE
Error message uses "Concrete type" to refer to an interface

### ISSUE THREAD

**Issue by tombentley** [ceylon/ceylon-spec#1384]
```ceylon
interface A of X | Y {}
interface X satisfies A {}
interface Y satisfies A {}
interface Z satisfies X&Y {}
```

error: concrete type is a subtype of multiple cases of enumerated supertype 'A': 'Z' inherits 'X' and 'Y'
[ceylon-compile] interface Z satisfies X&Y {}
[ceylon-compile]           ^

I always understood that a "concrete type" was any type that was not abstract, and that interfaces are abstract, so I find the error message confusing. I don't see why the type's concreteness is relevant to the error.

**Comment by gavinking** [comment]
Fixed, thanks.
