### ISSUE TITLE
getToken is null for Tree.SequencedArgument

### ISSUE THREAD

**Issue by jvasileff** [ceylon/ceylon-spec#1385]
Given:

```ceylon
void run([String] args) {
    print(*args);
}
```
and `seqArg` being the `Tree.SequencedArgument` for the print statement, we have:

`seqArg.location.string` = unknown location
`seqArg.token exists` = false

and

`seqArg.positionalArguments.get(0).location` = 2:10-2:14
`seqArg.positionalArguments.get(0).token exists` = true

**Comment by jvasileff** [comment]
When type checking the language module, and testing for `null` `getToken()`s when converting to Ceylon AST, there are null tokens for two `AnnotationList`s, and a couple dozen `SequencedArgument`s. No others.

**Comment by jvasileff** [comment]
Those counts are off dramatically. Here are the correct numbers:

```
$ ceylon compile-dart | sort | uniq -c
1134 Null token for: AnnotationList
 986 Null token for: SequencedArgument
```

**Comment by gavinking** [comment]
@jvasileff I don't understand. When I parse that code I don't get any `SequencedArgument` node. It's a `SpreadArgument`!

**Comment by jvasileff** [comment]
Oh, crap, same here. Sorry for the wild goose chase!

What's actually happening is @lucaswerkmeister's Ceylon AST is creating a synthetic `SequencedArgument`:

https://github.com/ceylon/ceylon.ast/blob/master/source/ceylon/ast/redhat/PositionalArguments.ceylon#L23

So that's something I need to watch out for.

**Comment by lucaswerkmeister** [comment]
The parser actually creates a `SequencedArgument` too, it just doesn’t record it (instead copying the individual arguments directly into the `PositionalArgumentList`).
