### ISSUE TITLE
Spec grammar for ClassSpecifier (class aliases) is unclear

### ISSUE THREAD

**Issue by lucaswerkmeister** [ceylon/ceylon-spec#1388]
```antlr
ClassSpecifier: "=>" (Extension | SuperclassExtension) PositionalArguments
```
1. `Extension` already includes optional `PositionalArguments`. Does this mean that `=> C()()` is a legal `ClassSpecifier`? (The prose – especially the “treated as a value expression” thing – probably forbids this.)
2. The rest of the specification never mentions any `SuperclassExtension`. Do you mean `SuperExtension`? But that’s already included in

 ```antlr
 Extension: (BaseExtension | SuperExtension) PositionalArguments?
 ```

To resolve both these questions, I suspect the intended and correct grammar is
```antlr
ClassSpecifier: "=>" (BaseExtension | SuperExtension) PositionalArguments
```
that is, the same as `"=>" Extension`, except that the `PositionalArguments` aren’t optional.

**Comment by gavinking** [comment]
Thanks. What happened here is that I changed the grammar  for `extends` when adding constructors, but didn't propagate the change to class aliases.

**Comment by lucaswerkmeister** [comment]
Alright, thanks for the fix.
