### ISSUE TITLE
move error for dynamic unsupported into typechecker

### ISSUE THREAD

**Issue by gavinking** [ceylon/ceylon-spec#1393]
Currently it is the JVM backend that is responsible for complaining it does not support `dynamic`. That's legacy, it can now be done in the typechecker itself.

**Comment by gavinking** [comment]
Done.

**Comment by quintesse** [comment]
Improved the implementation to not only look at the source (which is what `getScopedBackends()` does) but also at the backend(s) that are supported by the available compilers themselves (which we can retrieve using `Unit.getSupportedBackends()`). Remember that the IDE can have several backends active at the same time but the CLI compilers only support a single backend each.
