### ISSUE TITLE
NPE for import wildcard on class with default constructor

### ISSUE THREAD

**Issue by sgalles** [ceylon/ceylon-spec#1395]
This code in a package 
```ceylon
shared class Bar {
		
	shared new () {}
	
}
```
and this code in an other package
```ceylon
import foo {
	Bar {...}
}
```
results in
`the 'ImportVisitor' caused an exception visiting a 'Import' node: '"java.lang.NullPointerException"' at 'com.redhat.ceylon.compiler.typechecker.analyzer.ImportVisitor.hidesToplevel(ImportVisitor.java:192)'`

**Comment by gavinking** [comment]
Should be fixed now.
