### ISSUE TITLE
make void optional in anonymous functions

### ISSUE THREAD

**Issue by gavinking** [ceylon/ceylon-spec#1396]
Currently we let you drop the `function` keyword for anonymous functions that return a value, but we don't let you drop `void` for anonymous functions which don't return anything. It seems to me that this is too heavy-handed, and isn't very friendly for use with methods like `Iterable.each()`. I don't see why we couldn't relax this, letting you write:

```ceylon
stream.each((x) {
    print(x);
});
```

**Comment by FroMage** [comment]
+1

**Comment by quintesse** [comment]
Indeed +1

**Comment by lukedegruchy** [comment]
I can already do this in Ceylon:

    value list = ["1","2","3"];
    list.each(print);

I'm guessing this proposal applies to more complex anonymous void functions?

**Comment by quintesse** [comment]
@lukedegruchy pretty sure that's the case yes

**Comment by gavinking** [comment]
@lukedegruchy your example is a _function reference_. I'm taking about anonymous functions, particularly multi-line anon functions.

**Comment by lukedegruchy** [comment]
So, in other words, you want to do this:

    list.each((x) { 
        y = x + x;
        print(y); 
    });

But need to do this instead:

    list.each(void (String x) { 
        value y = x + x;
        print(y); 
    });

**Comment by gavinking** [comment]
This is done, but I need to document it in the spec.

**Comment by gavinking** [comment]
Done.

**Comment by gavinking** [comment]
OK, I've found one minor issue here that I'm not sure what to make of. This anonymous function:

    () { throw; }

Used to be assigned the type `Nothing`, but now it's assigned the type `Anything`. I'm not sure that's a good thing,

**Comment by gavinking** [comment]
I think this is all good. Closing.
