### ISSUE TITLE
Have language modules enforce that sequence types' have the highest specificity possible

### ISSUE THREAD

**Issue by Zambonifofex** [ceylon/ceylon-spec#1398]
Currently, a tuple that contains, for example, only a string might not be an instance of type `[String]`. I think this is wrong. If `Tuple` was made sealed, the language modules could enforce that all sequences are of the most specific type they can be.

**Comment by lucaswerkmeister** [comment]
I think I disagree with this. If I explicitly instantiate a `Tuple<Anything,Anything,Empty>("string", empty)`, I want that to be a tuple of `[Anything]`, not of `[String]`.

**Comment by Zambonifofex** [comment]
Also, another problem with `Tuple` not being sealed, is that `Tuple<String, String>` is not an subtype of `Tuple<Anything, String>` even though they mean the same thing (a tuple that contains exactly one `String`).

**Comment by Zambonifofex** [comment]
I mean, even if `Tuple` was sealed, that would still be a problem, but at least you wouldn't have instances of `Tuple<Anything, String>`...

**Comment by lucaswerkmeister** [comment]
What? No, `Tuple<String,String>` is definitely a subtype of `Tuple<Anything,Anything>` – the type parameters are all covariant (`out`). And what does this have to do with sealedness?

**Comment by Zambonifofex** [comment]
@lucaswerkmeister I have miswritten. I meant "supertype", and not "subtype". And I said `Tuple<String, String>` and **`Tuple<Anything, String`**.

Sure that have nothing to do with sealedness, but if the language module asserted the specificity of the types, we wouldn't have instances of `Tuple<Anything, String> `...

**Comment by lucaswerkmeister** [comment]
Oh, I see. But this only applies if `Rest` is `Empty`, or more generally, you want to prevent any `Tuple<All,First,Others[]>` where `All` is any more general than `Others|First`.

**Comment by gavinking** [comment]
@Zambonifofex well, in fact this already works due to how the `native` implementation of `Tuple` is written, at least on the JVM.

Try running the following code:

```ceylon
[Object] tuple = Tuple<Object,String,[]>("hello",[]);
print(type(tuple));
assert (is [String] tuple);
```

**Comment by lucaswerkmeister** [comment]
Ah… because in the native implementation, there’s no difference between
```ceylon
Tuple<Anything,Anything,Tuple<Anything,Anything,Empty>>
Tuple<Anything,Anything,Tuple<String,String,Empty>>
```
right? Because the inner tuple is moved into the outer tuple’s array, and its reified types are lost. Is that why `computeType()` is necessary?

**Comment by Zambonifofex** [comment]
@gavinking Well, that's weird. Is this mentioned in the spec? I'll have to agree with @lucaswerkmeister that if I instantiate a `Tuple<Anything, String>`, I don't want it to "decide on its own" that it wants to be a `Tuple<String, String>` instead...

**Comment by RossTate** [comment]
@gavinking, that behavior seems inconsistent.

@Zambonifofex, I'm confused about what you want. Can you give some toy example that doesn't work now but that you want to work?

**Comment by lucaswerkmeister** [comment]
@RossTate this came up [on Gitter](https://gitter.im/ceylon/user?at=55c926b2aac97ada66dd63b3):

```ceylon
Anything string => "Hello, World!";
assert({string}.sequence() is {String*});
```

the reified element type of `{string}` and `{string}.sequence()` is just `Anything`, not `String`.

**Comment by gavinking** [comment]
@Zambonifofex @RossTate yes, it's a little weird/inconsistent, but it's perfectly _sound_, and sometimes performance concerns have to win.

**Comment by gavinking** [comment]
> @RossTate this came up [on Gitter](https://gitter.im/ceylon/user?at=55c926b2aac97ada66dd63b3):
>
> ```ceylon
Anything string => "Hello, World!";
assert({string}.sequence() is {String*});
```
>
> The reified element type of `{string}` and `{string}.sequence()` is just `Anything`, not `String`.

Well that isn't really what's described in the issue description. There's no `Tuple`s produced in that code. And to have `{string}.sequence()` a `native` implementation of `ArraySequence`. It's currently not `native`. 

Anyway, I guess I still don't see really what concrete problem you're trying to solve.

**Comment by Zambonifofex** [comment]
@gavinking, the idea is that all sequences would be either `Empty` or `Tuple`, and that `foos.first is Foo` will be true only if `foos is [Foo+]`...

**Comment by gavinking** [comment]
OK well that's a much bigger change and the issue description doesn't really capture that at all.

Currently we have several things that implement `Sequence` that aren't `Tuple`s. The most important ones are:

- `ArraySequence` which _perhaps_ could be replaced by tuple without much loss of performance but I would have to check that.
- `Range`, which is useful, and we could not get rid of without breaking stuff. Now, if I had my time again, I would maybe not make ranges sequences, but it seems a bit late to change that now.

**Comment by Zambonifofex** [comment]
@gavinking
Couldn't you make ranges extend tuples? You could use some "magic" to make it more performant, if that's a problem, right?

**Comment by gavinking** [comment]
Well no, the whole point about a range is that it doesn't eagerly materialize its elements. So it's much more efficient than other sorts of sequences.

**Comment by Zambonifofex** [comment]
Really? For me sequences in ceylon were always synonymous of eagerness... Are there any more lazy ranges besides ranges?

**Comment by jvasileff** [comment]
@Zambonifofex ranges *are* eager; for `first..last`, `first` and `last` are immediately evaluated. It's just that for, e.g., `0..2^63`, an impossibly large array is not created and populated; elements other than `first` and `last` are created "on-demand". With `Enumerable` elements, this "laziness" shouldn't cause a problem.

**Comment by gavinking** [comment]
@Zambonifofex Well, you're sort-of right. It _is_ possible to write a misbehaving implementation of `Enumerable` that breaks the contract of `Enumerable` and results in ranges that don't contain the exaxt same elements every time you iterate them. Which is why I said above:

> Now, if I had my time again, I would maybe not make ranges sequences

But really, a misbehaving implementation of  `Enumerable` is in the same category of problem as a misbehaving implementation of `equals()` that makes it _appear_ that a `Tuple` or `ArraySequence` is mutable. It's basically the same category of error. So I don't think that's really a problem that is very much worth worrying about.

As long as your implementation of  `Enumerable` is sensible and adheres to the documented contract, then ranges of the enumerable type will be immutable, even though their elements are materialized lazily.

**Comment by gavinking** [comment]
I'm inclined to close this issue, since I don't really see much scope for improving on what we have currently without breaking useful functionality. @Zambonifofex?

**Comment by Zambonifofex** [comment]
@gavinking couldn't at least tuples have the most specific type? I feel like this is one considerably big advantage of laziness, and it's just not being taken advantage of...

**Comment by gavinking** [comment]
@Zambonifofex Well that's what I said [here](https://github.com/ceylon/ceylon-spec/issues/1398#issuecomment-129732868). They already do!

**Comment by Zambonifofex** [comment]
@gavinking I see. I thought you meant only `Element` would be changed.

Also, `Enumerable`s may be mutable, *and* calling `predecessor` or `successor` could have side effects. As far as I can tell, the documentation does not say anything against that, and in this case, ranges could show unexpected behavior... I feel like the syntax `[1..100]` to represent eager ranges, and `{1..100}` to represent lazy ones, to be quite intuitive! I don't understand why you think it's too late to change it. Ceylon isn't *very* popular yet, and ranges aren't at all its most feature, and in the couple programs I've seem that use ranges, I don't think I've seem any that take advantage of the fact that they are sequences. I think that it's the perfect time to make changes like this, before it gets popular. It's definitely better to make changes like this now, than to regret not doing in the future, when you won't be able to do it because the language got more popular... But since this isn't what this thread is about, I think it will be better if I close it...
