### ISSUE TITLE
Bogus syntax error message

### ISSUE THREAD

**Issue by lucaswerkmeister** [ceylon/ceylon-spec#1412]
```ceylon
String s = identity { "My string"; ;
```
> error: incorrect syntax: no viable alternative at token ';' expecting statement-ending ';'

That error message is [slightly confusing](https://i.imgur.com/2e2yaYZ.jpg). I’m not sure if the parser can be improved (I think it happens [around here](https://github.com/ceylon/ceylon-spec/blob/bde06b5d1cd44c75644866ae3b259ac89380c661/Ceylon.g#L1609)), but I think it would be a good idea to adjust `ParseError.getMessage()` so that the “expecting” part isn’t printed if it’s identical to the “actual” part.

**Comment by gavinking** [comment]
Should be fixed now.

**Comment by lucaswerkmeister** [comment]
Thanks.
