### ISSUE TITLE
rethink restrictions on variable default attributes

### ISSUE THREAD

**Issue by gavinking** [ceylon/ceylon-spec#1413]
I remember at one stage I relaxed a restriction on setting the value of a `variable default` attribute, allowing this:

```ceylon
 class C() {
     shared default variable String name = "";
     name = "foo";
 }
 ```

I don't think I meant to also allow this:

```ceylon
 class C() {
     shared default String name => "";
     assign name {}
     name = "foo";
 }
```

But I guess I need to find/review the original discussion of this and re-think it through.

**Comment by gavinking** [comment]
Note that even the first example is currently broken:

```ceylon
shared class Foo()
{
    shared default variable String bar = "woo";
    bar = "waa";
}

shared class Baz()
extends Foo()
{
    String s = "wuh";
    shared actual String bar => "wee";
    assign bar
    {
        print(s);
    }
}

shared void run() => Baz();
```

@Zambinofex noticed that this prints `null`.

**Comment by lucaswerkmeister** [comment]
> @Zambinofex noticed that this prints null.

Also known as @Zambonifofex :)

Regarding the broken example… is there a way to un-break this without making `bar = "waa";` erroneous with “default member may not be used in initializer”?

**Comment by Zambonifofex** [comment]
> > @Zambinofex noticed that this prints null.
>
> Also know as @Zambonifofex :)

Haha... xP

Also, this prints "`<null>`" as well:
```Ceylon
shared class Foo()
{
    shared default variable String woo;
    woo = "waa";
}

shared class Bar()
extends Foo()
{
    String wii = "wuh";
    shared actual String woo => "wee";
    assign woo
    {
        print(wii);
    }
}

shared void run() => Bar();
```

Which isn't what I would expect, since, neither of this do:
```Ceylon
shared class Foo()
{
    shared default variable String woo = "waa";
}
```
```Ceylon
shared class Foo()
{
    shared default String woo;
    woo = "waa";
}
```

**Comment by gavinking** [comment]
OK, so in fact this bug was caused by the proposed change #1379. I've rolled back that change, so I'm closing this issue, and leaving #1379 open for now.
