### ISSUE TITLE
else clause narrowing for if (exists)

### ISSUE THREAD

**Issue by gavinking** [ceylon/ceylon-spec#1415]
Given:

```ceylon
void f<T>(T t) {
    if (exists t) {
    }
    else {
        //t has type Null here
    }
}
```

It would be better for `t` to be narrowed to `T&Null`, since `Null` is not a subtype of `T`.

**Comment by Zambonifofex** [comment]
Huh. Why? `T` can only be a subtype of either `Null` or `Object`, or it can be exactly either `Anything`or `Null|Object`, right? In all cases, `T&Null` will either be `Null` or `Nothing`, and when it is `Nothing` (`T` is a subtype of `Object`), the else clause will not be reached...

**Comment by gavinking** [comment]
@Zambonifofex within the body of `f()`, we don't know that `Null` is a subtype of `T`. For example, at runtime, `T` might be `String`, in which case `null` would not be soundly assignable to `T`.

**Comment by Zambonifofex** [comment]
Yes, I know (`T&Null` is `Nothing`), and in that case the `else` clause will not be executed...

**Comment by gavinking** [comment]
But why about the case where it _is_ executed! We might like to assign `t` to `T` but we can't because it's no longer of type `T`! I actually ran into this in a real function and had to use `assert (is T null)`.

**Comment by quintesse** [comment]
Ah you mean for something like:

```ceylon
variable T t = ....;
if (exists t) {
}
else {
    t = null; //can't do this
}
```

Now I understand.

**Comment by Zambonifofex** [comment]
No, @quintesse, I think he means:
```Ceylon
shared class<T>(T t)
{
    shared T tt;
    if(exists t)
    {
        assert(false);
    }
    else
    {
        // tt = t; // fails
        
        // workaround:
        assert(is T null);
        tt = null;
    }
}
```
I see what you mean now, @gavinking... I guess it makes sense, since `exists` is suppose to mean `is Object`, and with `is Object`, it works fine...

**Comment by quintesse** [comment]
Isn't that basically the same example as I gave @Zambonifofex ? ;)

**Comment by Zambonifofex** [comment]
No, if we could indeed narrow the type of a variable value, and assign to it a expression of its narrowed type, your example would work fine if `t` is narrowed to type `Null` (like what we have today)... =P

**Comment by RossTate** [comment]
Wouldn't the proper solution be to infer that `Null` is a subtype of `T`?

**Comment by quintesse** [comment]
@Zambonifofex well it's that `if` in your sentence that makes my example just fine the way it is right now ;)
(my example fails right now and would work with Gavi's suggested change)

**Comment by Zambonifofex** [comment]
I'm unsure what "if" you mean...

If it's the first ("*if we could indeed narrow the type of a variable value*")
It would still not work with Gavin's changes. You can't narrow the type of variables, getters, nor `actual`/`default` members... That's because their value can change to something that isn't an instance of the narrowed type! xP

If it's the second ("*if `t` is narrowed to type `Null`*")
That's what we have today. `t` **is currently** narrowed to `Null`. Gavin is proposing that it should be `Null&T`...

**Comment by gavinking** [comment]
@rosstate well that would be _a_ solution but the easiest/most consistent one for now is to just make `exists` behave exactly the same as `is Object`.

**Comment by gavinking** [comment]
Done.
