### ISSUE TITLE
Metamodel refs to non-shared constructors

### ISSUE THREAD

**Issue by tombentley** [ceylon/ceylon-spec#1421]
With a non-`shared` method I get a compiler error if I try to take a model reference:

    class Method() {
        void m() {}
        void use() {
            value x = `Method.m`;//ERROR:metamodel reference to local declaration
        }
    }

However, with a non-`shared` constructor I get no error:

    class Constructor {
        shared new () {}
        new c() {}
        void use() {
            value x = `Constructor.c`;
        }
    }

I assume this is a bug.

**Comment by gavinking** [comment]
@tombentley well, I don't think so ... they're not quite the same situation, are they? A constructor doesn't capture anything from its environment...

**Comment by tombentley** [comment]
That's true @gavinking, but it highlights another weirdness: We'd not normally describe `Method.m` as a *local* method. It's just a method and the whole back-end capturing thing is supposed to be a detail. `m` would usually be transformed to a java method and in that case there's no difficulty in providing a model for it, so I don't really understand why it's outlawed.

**Comment by gavinking** [comment]
I'm not certain. Ask @FroMage.

**Comment by FroMage** [comment]
It's outlawed because @gavinking did not want to specify how capturing works for the initialiser. It's supported in the metamodel because it's convenient and easier than the opposite.

**Comment by gavinking** [comment]
@tombentley the thing is that since neither `m()` nor `use()` are shared, they're both just local declarations belonging to the initializer. They do *not* result in a method of a Java class.

_Constructors_ are a very different case.

So I think I can close this issue, right?

**Comment by FroMage** [comment]
> They do not result in a method of a Java class.

They actually _do_.

**Comment by gavinking** [comment]
Heh, well, ok, sure. But they need not.

**Comment by tombentley** [comment]
> It's supported in the metamodel because it's convenient and easier than the opposite.

This is my problem I think, and that's also the problem with https://github.com/ceylon/ceylon.language/issues/746 -- what you get out from the metamodel seems to depend on whether stuff is considered captured. I think that's confusing and a source of bugs. Imagine your code suddenly not working because the metamodel API suddenly starts returning null because you did some innocuous-seeming refactoring which meant that something was no longer captured. We should make the metamodel API consistent irrespective of whether a non-`shared` is captured or not. Since it looks like constructor metamodels will always be available I'm happy to close this.
