### ISSUE TITLE
Exception when using a union type in type constraint

### ISSUE THREAD

**Issue by tombentley** [ceylon/ceylon-spec#1422]
Using a union type in a type constraint causes an exception in the type checker. For example

    shared formal Sequential<FunctionModel<Type, Arguments>|ValueModel<Type>> getDeclaredConstructors
            <Arguments=Nothing>
            (ClosedType<Annotation>* annotationTypes)
                given Arguments satisfies Anything[]?

Prints 

error: the 'SupertypeVisitor' caused an exception visiting a 'TypeConstraint' node: '"java.lang.RuntimeException: getSupertypes() not defined for union types or Nothing"' at 'com.redhat.ceylon.model.typechecker.model.Type.getSupertypes(Type.java:1370)'
[ceylon-compile]                 given Arguments satisfies Anything[]?;

In addition to the (expected, but disappointing):

error: upper bound must be a class, interface, or type parameter
[ceylon-compile]                 given Arguments satisfies Anything[]?;
[ceylon-compile]                                           ^

**Comment by tombentley** [comment]
FTR as first observed in https://github.com/ceylon/ceylon.language/issues/695

**Comment by gavinking** [comment]
Fixed. Thanks.
