### ISSUE TITLE
Support Java nullability annotations

### ISSUE THREAD

**Issue by lucaswerkmeister** [ceylon/ceylon-spec#1424]
Several frameworks have attempted to improve on Java’s nullability support by introducing annotations for something being `@Nullable` or `@NotNull`/`@NonNull`/`@Nonnull`. We should recognize these annotations, and warn or error if:

- a Java `@Nullable` value (method return type, or field) is assigned to a Ceylon non-optional value or a Java `@NotNull`, or
- a Ceylon optional value or a Java `@Nullable` value is assigned to a Java `@NotNull` value (method parameter, setter parameter, or field).

Behavior on unannotated elements should *not* change. Some frameworks define only one annotation because the other is the default, but we can’t detect that.

Test cases / examples: https://gist.github.com/lucaswerkmeister/07556232a9bd060dd593

Annotations to support (suggestion, potentially incomplete; list from [Kotlin](http://blog.jetbrains.com/kotlin/2015/04/upcoming-change-more-null-safety-for-java/)):

- `org.jetbrains.annotation`: [`@Nullable`, `@NotNull`](https://www.jetbrains.com/idea/help/nullable-and-notnull-annotations.html)
- `android.support.annotation`: [`@Nullable`](https://developer.android.com/reference/android/support/annotation/Nullable.html), [`@NonNull`](https://developer.android.com/reference/android/support/annotation/NonNull.html)
- `javax.annotation`: [`@Nullable`](https://code.google.com/p/jsr-305/source/browse/trunk/ri/src/main/java/javax/annotation/Nullable.java), [`@Nonnull`](https://code.google.com/p/jsr-305/source/browse/trunk/ri/src/main/java/javax/annotation/Nonnull.java) (JSR 305, not in main Java yet apparently)
- `edu.umd.cs.findbugs.annotations`: [`@Nullable`, `@NonNull`](http://findbugs.sourceforge.net/manual/annotations.html)
- `javax.validation.constraints`: [`@Null`](https://docs.oracle.com/javaee/7/api/javax/validation/constraints/Null.html) (“must be `null`” – wat?), [`@NotNull`](https://docs.oracle.com/javaee/7/api/javax/validation/constraints/NotNull.html)
- `lombok`: [`@NonNull`](https://projectlombok.org/features/NonNull.html)
- `org.eclipse.jdt.annotation`: [`@Nullable`](http://help.eclipse.org/mars/index.jsp?topic=%2Forg.eclipse.jdt.doc.isv%2Freference%2Fapi%2Forg%2Feclipse%2Fjdt%2Fannotation%2FNullable.html), [`@NonNull`](http://help.eclipse.org/mars/index.jsp?topic=%2Forg.eclipse.jdt.doc.isv%2Freference%2Fapi%2Forg%2Feclipse%2Fjdt%2Fannotation%2FNonNull.html) – warning, without JS these links redirect you to the main help page for some stupid reason
- `org.checkerframework.checker.nullness.qual`: [`@Nullable`](http://types.cs.washington.edu/checker-framework/current/api/org/checkerframework/checker/nullness/qual/Nullable.html), [`@NonNull`](http://types.cs.washington.edu/checker-framework/current/api/org/checkerframework/checker/nullness/qual/NonNull.html)

Alternatively, we could assume that any annotation named `@Nullable`, `@NotNull`, `@NonNull`, `@Nonnull` has this meaning. I think that’s probably a reasonable assumption.

**Comment by jvasileff** [comment]
Minor implementation note: assigning `null` returned from a function marked `@NotNull` to a Ceylon optional should *not* result in a runtime error.

And we probably shouldn't have compile time *errors* for:

```ceylon
if (exists x = getRequired()) { ... }
```

**Comment by lucaswerkmeister** [comment]
Moved to ceylon/ceylon-model#8.
