### ISSUE TITLE
Weird restriction for annotation parameter types

### ISSUE THREAD

**Issue by FroMage** [ceylon/ceylon-spec#1427]
Apparently I can have annotation parameters of type `[String*]` and `{String+}` but not `[String+]`, is that normal?

**Comment by gavinking** [comment]
Well, yes: spec §7.2.2. Is this a feature request against the spec and typechecker for 1.2?

**Comment by lucaswerkmeister** [comment]
I don’t see where 7.2.2 allows `{T+}`, so is that a bug?

**Comment by FroMage** [comment]
Well, yeah, that just seems arbitrary.

**Comment by gavinking** [comment]
Alright, so I have made that change, but you guys will have to write the code/tests to support it in both backends.

**Comment by FroMage** [comment]
Hey, I was fine with disallowing both, just as long as they are consistent ;)
