### ISSUE TITLE
error with legal string

### ISSUE THREAD

**Issue by jvasileff** [ceylon/ceylon-spec#1429]
The spec says:

> The following are legal strings:
...
`"\{00E5}ngstr\{00F6}ms"`

But the type checker says:

> Illegal unicode escape sequence: 00F6 is not a Unicode character
> Illegal unicode escape sequence: 00E5 is not a Unicode character

**Comment by jvasileff** [comment]
I guess it's supposed to be this?

    "\{#00E5}ngstr\{#00F6}ms"

**Comment by gavinking** [comment]
There are no unicode characters named 00E5 and 00F6.

**Comment by jvasileff** [comment]
Ok, I fixed the title...

**Comment by gavinking** [comment]
Ah OK, sure.
