### ISSUE TITLE
no validation of use of native declaration in type expressions

### ISSUE THREAD

**Issue by gavinking** [ceylon/ceylon-spec#1436]
In a cross-platform module, the typechecker rightly rejects the following code:

```ceylon
import java.lang {
	Integer
}

shared void run() {
    Integer("");
}
```

But it accepts this code:

```ceylon
import java.lang {
	Integer
}

shared void run() {
    Integer i;
}
```

It even accepts the following code:

```ceylon
import java.io {
	InputStream
}

class Run() extends InputStream() {
	shared actual Integer read() => nothing;
}
```

Which of course blows up the JS backend.

@quintesse this is for you, of course.

**Comment by quintesse** [comment]
Should be done, now. Closing.

**Comment by gavinking** [comment]
Thanks, I will try it out.

**Comment by gavinking** [comment]
Confirmed it's working. :)
