### ISSUE TITLE
support multiple backends per native annotation

### ISSUE THREAD

**Issue by jvasileff** [ceylon/ceylon-spec#1442]
Basically, make `native` variadic. This matters when there are three or more backends, since some "native" implementations may be suitable for multiple backends. For example, the Javascript implementation of `Contextual` can also be used for Dart.

**Comment by jvasileff** [comment]
I thought this was a copy&paste/DRY inconvenience, but it's actually a bug—there's no way to have a two-or-more-backend module.

**Comment by quintesse** [comment]
No for now you can only have one backend per declaration or per module. You can easily make a copy, not nice but certainly not a bug either.

**Comment by jvasileff** [comment]
> You can easily make a copy

How? I mean, I'm not arguing for any particular prioritization, but I don't see how this is possible.

**Comment by quintesse** [comment]
Just like it is now: you either have a module that works for all backends, or you make a module that works only for a single backend, which would mean that if the JS and the Dart backend code is really the same there's no other way right now than making a copy of the JS module and marking it Dart.

**Comment by quintesse** [comment]
Ok, this is now "unofficially" implemented. Unofficially because it's not a supported feature for 1.2.
Still needs tests too.
The syntax is like this `native("jvm", "js", "dart")`

**Comment by jvasileff** [comment]
Very cool!

**Comment by quintesse** [comment]
I'll consider this closed. Any problems can be put in new issues.

**Comment by FroMage** [comment]
Wrong repo, man.

**Comment by quintesse** [comment]
Heh
