### ISSUE TITLE
no error for missing native impls of toplevel function

### ISSUE THREAD

**Issue by jvasileff** [ceylon/ceylon-spec#1445]
For classes, native headers cannot provide their own default implementations. So I presume the same should be true for functions.

```ceylon
native void nf1() {
    print("nf1");
}

//native("js") void nf1() {}
//native("jvm") void nf1() {}

shared void run() {
    nf1();
}
```
results in "ReferenceError: nf1 is not defined" on JS. On the JVM, it compiles and outputs "nf1".

Should a body even be allowed for native function headers?

**Comment by quintesse** [comment]
If it works on the JVM then why do you open it for `ceylon-spec`? This is supported behaviour and the bug is in the JS backend.

**Comment by quintesse** [comment]
Copied to ceylon/ceylon-js/issues/655

**Comment by jvasileff** [comment]
> why do you open it for ceylon-spec

The answer is in the issue description.
