### ISSUE TITLE
direct invocations on grouped expressions

### ISSUE THREAD

**Issue by jvasileff** [ceylon/ceylon-spec#1449]
It seems this should be disallowed:

```ceylon
print(("Hello".plus) { " world"; });
```

FWIW, that example works on the JVM, but not:

```ceylon
print((1.plus) { 2; });
```

**Comment by gavinking** [comment]
This code is perfectly correct. Please report the second example as a bug in `ceylon-compiler`.

**Comment by lucaswerkmeister** [comment]
> Any invocation expression where the invoked expression is a callable reference expression is called a *direct invocation expression* of the function, class, or callable constructor to which the callable reference refers.

It’s not clear to me that this allows the typechecker to peek into grouped expressions. I would interpret this to mean that only `1.plus` is a callable reference expression, whereas `(1.plus)` would just be a callable expression.

(It doesn’t help that a “callable reference expression” is not the same thing as a “reference expression” that is callable – reference expressions are `` `class Object` ``, `` `function print` ``, etc.)
