### ISSUE TITLE
use of natively-imported module in non-native function

### ISSUE THREAD

**Issue by gavinking** [ceylon/ceylon-spec#1454]
I have, in a x-platform module:

```ceylon
module hello "1.0.0" {
	native("js") import ceylon.collection "1.2.0";
}
```

And then:

```ceylon
import ceylon.collection {
	ArrayList
}
shared void run() {
    print(ArrayList { [1,2], [3,4] });
}
```

I should get an error on the usage of `ArrayList` but I don't.

@quintesse?

**Comment by quintesse** [comment]
The CLI compilers handle this just fine. It's an IDE-only problem again related to the fact that it uses the JVM model loader for JS , nothing we can do anything about at this time. Moving to 1.3.

**Comment by quintesse** [comment]
Hmm wait, let me investigate a bit more, perhaps there's a way to catch this.

**Comment by quintesse** [comment]
Ok, should be fixed now although I haven't tested it in the IDE yet.
