### ISSUE TITLE
syntax error with invocation of grouped expression of base expression

### ISSUE THREAD

**Issue by jvasileff** [ceylon/ceylon-spec#1456]
These are unusual, but should be allowed, right?

```ceylon
class A {
    shared new create() {}
    shared String foo() => "";

    Anything a1 = (create)(); // incorrect syntax: no viable alternative at token ';'
    Anything a2 = (foo)(); // incorrect syntax: no viable alternative at token ';'
}
```

**Comment by lucaswerkmeister** [comment]
you’re missing a semicolon at the end of `foo() => ""`

**Comment by jvasileff** [comment]
Thanks @lucaswerkmeister , fixed.

**Comment by lucaswerkmeister** [comment]
oh, there’s still a syntax error… I thought that would fix it. Huh.

**Comment by jvasileff** [comment]
Hah, my example was full of errors. Just fixed `s/bar/create`.

**Comment by gavinking** [comment]
Is that better, @jvasileff?

**Comment by jvasileff** [comment]
@gavinking if it allows me to write `(create)()`, I'm sure my code will be much more legible going forward.
