### ISSUE TITLE
Should this project be deprecated?

### ISSUE THREAD

**Issue by simonthum** [ceylon/ceylon-spec#1471]
ceylon/typechecker seems to have it all.

**Comment by quintesse** [comment]
There was a time that @gavinking wanted to keep this project just for the specification (separate from its implementation which is the typechecker). I'm not sure he still wants that. If not we can indeed deprecate this project like the others.

**Comment by gavinking** [comment]
No, I changed my mind. It's fine for the spec to live in the main `ceylon` repo, I guess.

**Comment by quintesse** [comment]
Ok! Will mark this repo deprecated then. Thanks @simonthum, for bringing this up.
