### ISSUE TITLE
New artifact type for docs?

### ISSUE THREAD

**Issue by FroMage** [ceylon/ceylon-spec#189]
When uploading a project to a repo, we can't add any docs ATM. 

In Play Framework, when uploading a module, given that the whole source archive (including build) is uploaded, if the archive contains a `doc` folder with Markdown files, this is processed to HTML for user access.

This would be nice for a public repo, to allow users to browse the docs as well as the API.

Should we add such an artifact type? If yes, what are the rules?

**Comment by quintesse** [comment]
AFAICT this has all been implemented for some time already and this issue can be closed.

**Comment by gavinking** [comment]
@quintesse ok but perhaps it wasn't added to the spec?

**Comment by gavinking** [comment]
Oh, it seems it is documented in the spec under §9.3.5. OK.

**Comment by quintesse** [comment]
ah no, the spec is outdated

**Comment by gavinking** [comment]
@quintesse can you send me a PR that updates it please? It's not obvious to me what is wrong...

**Comment by quintesse** [comment]
On it already

**Comment by gavinking** [comment]
thx

On Tue, Aug 18, 2015 at 8:59 PM, Tako Schotanus <notifications@github.com>
wrote:

> On it already
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ceylon/ceylon-spec/issues/189#issuecomment-132186695>.
>



-- 
Gavin King
gavin@ceylon-lang.org
http://profiles.google.com/gavin.king
http://ceylon-lang.org
http://hibernate.org
http://seamframework.org

**Comment by quintesse** [comment]
Sent you a PR to look at
