### ISSUE TITLE
don't enforce type constraints at use-sites

### ISSUE THREAD

**Issue by gavinking** [ceylon/ceylon-spec#535]
We only need to check type constraints in `extends`/`satisfies` and instantiation expressions. The following code is perfectly well-typed:

```ceylon
interface X<T> given T satisfies Y {}
X<Anything> x = nothing;
```

As is:

```ceylon
class X<out T>(T t) given T satisfies Y {}
X<Anything> x = X(y);
```

This is not really a high-priority thing, however.

(Thanks to @RossTate for pointing this out.)

**Comment by gavinking** [comment]
This issue blocks #1291.

**Comment by gavinking** [comment]
Yaay, so apparently @tombentley (or someone else?) had actually done all the backend work needed for this a while ago, and simply hadn't realized it. Anyway, I've done some testing and I don't seem to be able to break the backend, not even with inheritance and refinement. 

I still need to update the spec to reflect this change.

**Comment by RossTate** [comment]
Snazzy!

**Comment by gavinking** [comment]
Done!

**Comment by gavinking** [comment]
And thanks, @RossTate, for the idea!
