### ISSUE TITLE
verbatim strings

### ISSUE THREAD

**Issue by gavinking** [ceylon/ceylon-spec#577]
Should we support _verbatim strings_? That is, string literals with no interpolation or backslash escapes. What should be the syntax? Triple-doubles?

A big question to be answered is: do you want these things to exhibit the same leading-whitespace-stripping behavior that other multiline string literals have? Or should we leave all the whitespace in?

**Comment by Zambonifofex** [comment]
>So perhaps what we can do is keep the current implementation, but add a check that every line past the second has to start with the same ws prefix as the second line? We would still count ws the way we do now, and require that they align as we do now.

That sounds like it is the best way to do it. I use a proportional font, and multi line strings currently look horrifying... With [elastic tabstops](http://nickgravgaard.com/elastic-tabstops/), I could do something like this:
```Ceylon
value string =[t]"Hello,
[t              ]World!";
```
But, unfortunately there is not elastic tabstop plugins for eclipse.
