### ISSUE TITLE
Specify what `native` does for user code

### ISSUE THREAD

**Issue by FroMage** [ceylon/ceylon-spec#648]
ATM it is only really supported for the language module, and even then it's not really clear what it does since for example the JVM backend ignores these declarations and provides model from the corresponding Java implementations to the typechecker via the model loader so it's not clear to me that the typechecker even sees them, or check that the native implementation schema corresponds to the native ceylon declaration.

We should spec this and support it for user modules, especially if we do #500 which will allow users to provide JS and JVM implementations of the same declaration, because having a Ceylon `native` declaration will help checking that both implementations have the right schema at compile-time.

**Comment by gavinking** [comment]
@quintesse is working on this, and when he is done, the spec needs to capture it.

**Comment by quintesse** [comment]
@gavinking you assigned this to me, what is it you want me to do exactly? Write a section of the spec?

**Comment by gavinking** [comment]
@quintesse no, well, I'm not even certain that this needs to go in the spec, being an interop concern. But it _does_ need to be properly documented _somewhere_, with examples.

**Comment by quintesse** [comment]
Ok, sure. @chochos already documented his part (although on the GitHub Wiki, not on the website) so I'd just add this to it.

**Comment by gavinking** [comment]
@quintesse Currently it's impossible to write code in a JavaScript-only project in the IDE. I get the following error on all references to `native` types in the language module:

    No native implementation for backend: native String is not implemented for one or more backends

**Comment by quintesse** [comment]
Did you even update the IDE? I have been up to $am fixing that for you.

**Comment by gavinking** [comment]
> Did you even update the IDE?

Ah no I did not.

> I have been up to 4am fixing that for you.

Ok, thanks!

**Comment by quintesse** [comment]
Sorry for sounding cranky. I'm still not entirely awake ^^

**Comment by gavinking** [comment]
I have lightly documented the semantics of `native` in the spec. It is _not_ a full specification, and I think that's reasonable, since the spec doesn't generally deal with these concerns. I'm going to call this "done".
