### ISSUE TITLE
Allow "throw" as lazy specifier/initializer

### ISSUE THREAD

**Issue by quintesse** [ceylon/ceylon-spec#651]
Right now the following gives an error:

``` ceylon
Boolean add(T? elem) => throw UnsupportedOperationException("add()");
```

Maybe we could allow this?

(I know we normally use `nothing` for these cases, but in this case its required by the Java interface I'm implementing)

**Comment by gavinking** [comment]
The only case I've really run into this in practice was in comprehensions, though now I can see how it could also happen in a `switch` expression. But it seems to me that what I want in those cases is never `throw`, but actually `assert`. Inline `assert` is actually something I'm a fair bit more open to...

**Comment by jvasileff** [comment]
As mentioned, I've found some lengthy expressions to be good for clarity - things like producing a value without looping, but with several ifs/elses/cases. It's very clear that 20 lines of code of this sort serves a single purpose, and in a fairly simple manner. But as the number of cases increases, so does the likelihood that one will need to result in a particular type of error.

For this, I'd actually be *more* frustrated with `assert` but not `throw`. Unless we are going to completely devalue exceptions, the distinction between `AssertionError` and `SomeException` is important (more so, `Error` vs. `Exception`, but I suppose discussing the finer points of that is for another day.) If given the choice to either settle for `assert` where an `Exception` is called for, or reformat (obfuscate?) 20 lines of code, it would be tough to resist just using `assert`.

And, of course, expressions *can* currently result in an exception, e.g. `1.divided(0)`, just not explicitly.

**Comment by jvasileff** [comment]
For example, I think the following would read well as an expression. Please disregard the actual exception type, which may be wrong in this case:

```ceylon
    shared actual Whole powerOfInteger(Integer exponent) {
        if (this.unit) {
            return this;
        }
        else if (exponent.zero) {
            return package.one;
        }
        else if (this.negativeOne) {
            return if (exponent.even)
            then package.one
            else this;
        }
        else if (exponent.unit) {
            return this;
        }
        else if (exponent.positive) {
            return powerBySquaringInteger(exponent);
        }
        else {
            throw AssertionError(
                "``string``^``exponent`` negative exponents not supported");
        }
    }
```
