### ISSUE TITLE
The problem with the ` (dead key on german keyboard)

### ISSUE THREAD

**Issue by ghost** [ceylon/ceylon-spec#672]
Well simply put, on a german keyboard, this is (I don't remember the correct term for this neither in german nor english) a key, that doesn't come out right after pressing it, but after pressing the following character. E.g. if I press "^" and then "o" I get "ô". It's the same for "`", I have to press SPACE to actually get the character into my text editor. Which means  `` is 4 keypresses for german people. This would be rather annoying.

**Comment by kitsunekyo** [comment]
even though this is an old thread, maybe it helps someone, stumbling over it.

for windows you can easily create your own keyboard layout, and disable the dead-key behavior on those keys. i happily share mine:

https://github.com/kitsunekyo/win-german-dev-keyboard
 
// edit: there are for sure options like this for OSX too
