### ISSUE TITLE
Syntax for access nested references

### ISSUE THREAD

**Issue by kelvio** [ceylon/ceylon-spec#673]
Hello everybody. 
I identified some cases where writing nested references (feature present in both Java in Ceylon) becomes barely readable.
I wrote the following code in Java to illustrate:

<pre>
class PacoteLances {

  private int quantidadeLances;
  private int bonus;
  
  //Getters and Setters
  
}

class CompraPacoteLances {

    private PacoteLances pacoteLances;
    
    //Getters and Setters
        
}

public class Counter {

    private CompraPacoteLances compraPacoteLances;
    
    //....
    
    public int sum() {
        return this.compraPacoteLances.getPacoteLances().getQuantidadeLances() + this.compraPacoteLances.getPacoteLances().getBonus();
    }
    
}
</pre>

The problem here is in the method "sum" to search values ​​in a reference within the attribute "compraPacoteLances".
 I could write something like:
<pre>
     public int sum() {
         PacoteLances p = this.compraPacoteLances.getPacoteLances();
         return p.getQuantidadeLances() + p.getBonus();
     }
</pre>

However, it bothers me not exist in Java syntax that facilitates access to nested references.
So I come to propose the following syntax to access nested references in Ceylon:
Assuming that the above code was written in Ceylon, we have:
<pre>
shared Integer sum() {
  return this.compraPacoteLances.pacoteLances : quantidadeLances + bonus;
}   
</pre>
Where, "this.compraPacoteLances.pacoteLances" is the way of reference where members "quantidadeLances" and "bonus" will be accessed.

**Comment by gavinking** [comment]
We actually added `let` expression in 1.2, so I think we can close this now.
