### ISSUE TITLE
narrow type in else block of if (is...)

### ISSUE THREAD

**Issue by gavinking** [ceylon/ceylon-spec#74]
Tako gives this example:

```
shared Integer q(Integer? x) {
    if (is Null x) {
        return 0;
    }
    else {
        return x; //compile error
    }
}
```

He argues, rather reasonably, that the compiler should be able to reason that `x` has type `Integer` where the error occurs.

I agree that it would be possible. This would not amount to supporting types like `X~Y`, which Ross says results in undecidability, if I recall correctly. It just means being able to utilize the identity `X|Y~Y == X`, which we already do utilize in certain places.

On the other hand:
1. This example is a bit contrived. It would be _much_ more usual to reverse the condition to do `if (is Integer x)` or `if (exists x)`.
2. For more complex cases, this is stepping on the turf of the `switch` statement.

So I'm not sure that this feature would really be especially practically useful. OTOH, it's easily doable.

**Comment by sgalles** [comment]
@gavinking  I stumbled upon something minor that I think is related to this issue :
This code obviously does not compile but there is a funny type in the error message :
```ceylon
 String foo<Bar> 
            (String|Bar element){
        if (is String element){
            return element;
        }else{
            return element;
        }
    }
```
`error: returned expression must be assignable to return type of 'foo': 'Bar&Object|Bar&null' is not assignable to 'String'`. 
(I can open an other issue if you don't want to reopen this one)

**Comment by gavinking** [comment]
@sgalles OK, I agree that this was worth improving. Not a _bug_ precisely, but anyway I have imrpved the algorithm in `ProducedType.minus()` to be a little bit less aggressive.

**Comment by jvasileff** [comment]
Oh, cool, this also addresses #1238!
