### ISSUE TITLE
more powerful annotation constraints

### ISSUE THREAD

**Issue by gavinking** [ceylon/ceylon-spec#760]
We would like to be able to constrain an annotation to appear only at program elements of a certain (return) type, or with certain parameter types. However, we've left this out of M6. See the discussion in #698.

**Comment by gavinking** [comment]
So, FTR, since we all seem to have forgotten the issue here, and why we didn't implement this at the time is this: types like `Function` and `Class` have a mix of `in` and `out` type parameters, and thus can't occur as type arguments to a satisfied supertype, according to a restriction invented by @RossTate that eliminates certain undecidable cases which I happen to forget right now. Thus, we can't use a supertype of the annotation type to encode constraints in terms of `Class`, `Function`, `Method`, or `Attribute`.

I can see three possible solutions:

1. Encode this info into an annotation instead. This can't be done right now because annotations don't accept typed models, only references.
2. Invent new invariant subtypes of all the model types, just for expressing constraints. Yew!
3. Encode `ReturnType` and `ParameterTypes` directly into the supertype. This isn't quite as powerful, but it's simple and can be implemented today. Seems like a pretty reasonable solution to me.

**Comment by tombentley** [comment]
> Encode `ReturnType` and `ParameterTypes` directly into the supertype. This isn't quite as powerful, but it's simple and can be implemented today. Seems like a pretty reasonable solution to me.

Could you give an example, please?

**Comment by gavinking** [comment]
```ceylon
final annotation class Bar() 
        satisfies OptionalAnnotation<Bar,Annotated,Basic,[String]> {
    string => "Foo";
}
annotation Bar bar() => Bar();
```

**Comment by tombentley** [comment]
Well it would work. But wow, that's ugly. Presumably 1. would look something like

```ceylon
target(`Class<Basic,[String]>`)
final annotation class Bar() 
        satisfies OptionalAnnotation<Bar,Annotated> {
    string => "Foo";
}
annotation Bar bar() => Bar();
```

which I find less ugly, because it doesn't "fragment" the return type and argument list.

**Comment by gavinking** [comment]
@tombentley it actually looks _more_ ugly to me...

**Comment by gavinking** [comment]
This is now implemented and is working fine. Three things:

0. Decide if we need to add an additional parameter to allow constraining an annotation to only occur on _members_ and not on toplevels. It would make `ConstrainedAnnotation` and friends even more complex/ugly, but I suppose it's quite useful ... ?
1. Spec.
3. Tests.

**Comment by gavinking** [comment]
So I've added support for constraining to members or toplevels, but it's kinda weird:

- it uses a pretty unnatural interpretation of `Null`, and
- doesn't consider constructors to be "members".

Not quite perfect, I suppose, but surely Good Enough.

**Comment by gavinking** [comment]
Aaaah, OK, I have managed to make the original approach work where you have just one type parameter that represents the model type. Just like we always planned.

_But_, there is one very weird thing about it: the variance had to go backwards! That is, an `OptionalAnnotation<X,X?,Value<Integer>>` is an `OptionalAnnotation<X,X?,Value<Object>>`, not the other way round! Well, that's wrong, but since we don't actually _use_ the third type parameter of `OptionalAnnotation` anywhere, I think it's tolerable. Anyway, the other approach of flattening out the return type and argument types suffered from the exact same problem.

So this issue is finally solved!
