### ISSUE TITLE
throw and return statements should affect flow sensitive typing

### ISSUE THREAD

**Issue by sgalles** [ceylon/ceylon-spec#891]
`throw` and `return` statements should affect flow sensitive typing :

```ceylon
Foo foo = ... ;
if (!is Bar foo) {
     throw FooBarException();
}
foo.bar(); //foo is a Bar here 
```
Same behavior expected if `return` is used instead of `throw`

**Comment by gavinking** [comment]
Note that the functionality which blocks this popular issue is #678 and #677, both of which have been around since M6, along with other related similar stuff in `ControlFlowVisitor`.

**Comment by gavinking** [comment]
Given how difficult this would be to implement, we should consider an alternative, which would be to add a block to `assert`, for example:

Hell, I'm not even sure if the `else` keyword is really needed for readability here. How about just:

```ceylon
assert (nonempty list) { return null; }
```

```ceylon
assert (is Foo arg) { throw IllegalTypeException(); }
```

```ceylon
assert (!name.empty, length>0) { return ""; }
```

Or, if you guys think it's necessary for readability, we could require an `else` keyword here:

```ceylon
assert (nonempty list) else { return null; }
```

```ceylon
assert (is Foo arg) else { throw IllegalTypeException(); }
```

```ceylon
assert (!name.empty, length>0) else { return ""; }
```

This is _much, much_ easier to implement, and doesn't actually seem worse to me.

**Comment by lucaswerkmeister** [comment]
I think the `else` makes the meaning much more obvious to readers unfamiliar with the syntax. With `else`, I really like this idea (though I’d probably still want to have the original issue *eventually*).

**Comment by sgalles** [comment]
Well I'm certainly not against it because https://groups.google.com/d/msg/ceylon-users/AbcLpWNrlCY/9Aa7XLXhPcQJ :smile: 
And yes, I also like the version with `else`

**Comment by jvasileff** [comment]
I agree with @lucaswerkmeister's comment.

It may also make sense to allow `break` and `continue`.

**Comment by lukedegruchy** [comment]
FWIW, I vote for the else version.

**Comment by lucaswerkmeister** [comment]
Actually, I don’t fully understand the semantics yet. What does this do?
```ceylon
void printFirst(Anything[] seq) {
    assert (nonempty seq) { print("<empty>"); }
    print(seq.first.string);
}
```
Implicit return after `print("<empty>");`? Or implicit throw? Or error from `ControlFlowVisitor`?

**Comment by jvasileff** [comment]
Error, "Does not definitely return", right?

**Comment by lucaswerkmeister** [comment]
Good idea, that error message could apply here.

**Comment by quintesse** [comment]
I think it's pretty horrible btw, suddenly `assert` has become some kind of special `if` statement? Do we really need to explain to people that they can't use `if` the way they expect it, but "hey we have this cool swiss army knife `assert` that does what you want!". I vote for not doing this and waiting until the moment we *can* do this for `if`, or just not at all.

**Comment by jvasileff** [comment]
See also the Swift `guard` statement.

**Comment by jvasileff** [comment]
@quintesse there is some benefit with `assert-else-return` over `if-return` to the reader, since with `assert` it's immediately clear that the condition will hold for the rest of the scope without having to manually perform the definite return analysis.

**Comment by sgalles** [comment]
@quintesse let me explain why I believe that the current `assert` of Ceylon is incomplete, and why I think the version proposed here is useful (useful for its own sake, and not only as a workaround for this issue)

And to illustrate this, I'm going to use a [real code example from my toy project](https://github.com/sgalles/ceylon-dddsample/blob/master/source/dddsample/cargotracker/application/internal/DefaultBookingService.ceylon#L75)

```ceylon
shared actual default void changeDestination(TrackingId trackingId, UnLocode unLocode) {
		Cargo? cargo = cargoRepository.find(trackingId);
		assert(exists cargo);
		Location? newDestination = locationRepository.find(unLocode);
		assert(exists newDestination);
		
		RouteSpecification routeSpecification = RouteSpecification.init(cargo.origin, newDestination, cargo.routeSpecification.arrivalDeadline);
		cargo.specifyNewRoute(routeSpecification);
		
		cargoRepository.store(cargo);
}
```
Don't you think that the two `assert` make the code super clear ? I do.
It this really what I wanted ? 
No. I wanted to throw a more specific business exception (with a dynamic message) for the entities that were not found. And now we are saying that I must restructure my code with a `if` to do that ? Why ? If we agree that `assert` is useful for the clarity of the code why am I not allowed to use it with my own specific exceptions ?

**Comment by gavinking** [comment]
The real reason why `assert` works better for this purpose than `if` is that it lets you combine conditions into one condition list. Compare:

```ceylon
assert (exists list, exists length, length>0) { return null; }
//etc
```

```ceylon
if (exists list) { return null; }
if (exists length) { return null; }
if (length>0) { return null; }
//etc
```

There's a big difference. `assert` says "if _any_ of these conditions fail". OTOH, `if` says "if _all_ of these conditions fail".

**Comment by sadmac7000** [comment]
It's new and scary, but I'll take it.

As long as we're sure we like this better (since even if we can make if work in the type checker one day, we can't remove this once we add it). But the last comment is sort of convincing me.

**Comment by gavinking** [comment]
Also, `assert` typically lets you express the conditions in non-negated form, i.e. `exists` instead of `!exists`.

**Comment by gavinking** [comment]
Alright, so I have, for 1.2, pushed a totally rubbish implementation of this feature which handles things like:

```ceylon
if (!exists foo) { return; }
foo.bar();
```

and:

```ceylon
if (!is Foo foo) { throw; }
foo.bar();
```

I detect `if` blocks which end in a `return`, `throw`, `break`, or `continue`. 

- I do _not_ detect `assert(false)` nor `while (true)`.
- Nor do I evaluate conditional branches to see if every branch definitely returns.

Furthermore, the code that supports this is by far the nastiest in the whole typechecker.

My motivation for pushing this now, right before the 1.2 relase is that I discovered how much code like this is being written write now:

```ceylon
if (!exists foo) {
    return null;
}
assert (exists foo);
```

Code like the above is an abomination in Ceylon, and undermines the typesafety we provide. Furthermore, code like _breaks immediately_ as soon as the issue is solved. So you guys definitely should not have been writing code like that!

Therefore, it was better to do this sooner rather than later.

**Comment by quintesse** [comment]
@jvasileff you have a condition and a true-block and a false-block, to me that's the definition of an `if` statement.

@sgalles well, first I don't find that it makes code "super clear", but I'll admit it's useful. But an assert is an assert and an if is an if, one is used to throw an exception for the highly unanticipated situation where the condition isn't true while an if is used to make choices. The moment you give an assert an else-block and use it to make decisions it's become an if and you should be using an if in my opinion.

> So you guys definitely should not have been writing code like that!

Well you can say that to *us*, but you just can't prevent the rest of the world from doing that, it's the closest thing Ceylon permits to what is an "early-exit" code style.

**Comment by gavinking** [comment]
I have reimplemented this in a slightly less-crappy way.

**Comment by FroMage** [comment]
So this works for what sort of conditions? `is` and `exists` for sure. Others? Multiple conditions?

Due to the semantics of `is`/`exists` wrt variables and transient values, it's not possible to get a new definition (virtual else var, after the `if` condition) that is not constant, which means that it doesn't matter that `int` is not evaluated three times here (contrary to how it looks):

```ceylon
            if (!exists int) {
                return 0;
            }
            return int+int;
```

In fact, ATM with my implementation it's evaluated _twice_ instead of the _once_ that would be possible. I assume that's not a problem?

**Comment by gavinking** [comment]
- `is`, `exists`, `nonempty`
- No, as soon as you have multiple conditions, you can't apply this reasoning, since you have no idea which of the conditions failed.

**Comment by gavinking** [comment]
> Due to the semantics of `is`/`exists` wrt variables and transient values, it's not possible to get a new definition (virtual else var, after the `if` condition) that is not constant, which means that it doesn't matter that `int` is not evaluated three times here (contrary to how it looks):

Right. Exactly. @tombentley totally misunderstood the point I was making about what was wrong with the previous implementation. It _does not matter_ if you re-evaluate the variable. It _does_ matter if you re-evaluate the _condition_. Which was a problem with the previous implementation.

**Comment by FroMage** [comment]
OK thanks.

**Comment by FroMage** [comment]
Mmm, does that also work with destructuring?

**Comment by gavinking** [comment]
@FroMage no, I don't think so.

**Comment by FroMage** [comment]
OK.

**Comment by FroMage** [comment]
Just keep in mind that I won't implement anything for what you say is not supported ;)

**Comment by FroMage** [comment]
Done.

**Comment by FroMage** [comment]
Sorry I meant to close the backend issue ;)

**Comment by gavinking** [comment]
Well, it's done anyway, and moved to #1434.

**Comment by lucaswerkmeister** [comment]
Shouldn’t we have a tracking issue for making this work even with `assert (false);` and `while (true)` (milestone “postponed indefinitely”)?
