### ISSUE TITLE
import singleton object members and constructors of toplevel classes

### ISSUE THREAD

**Issue by simonthum** [ceylon/ceylon-spec#928]
In #796 a syntax to import certain members was suggested which already exists for java static members.

It would be great to extend this functionality to shared `object` members. The object would then be passed without mentioning it a the invocation site. E.g.

```
shared object fns {
  shared void fn();
}
```

```
import object { fns { fn }}
fn(); //  fns.fn();
```

@gavinking  added:

> It would be for:
> - object members
> - constructors
> - static member references (maybe)

**Comment by FroMage** [comment]
Did you open an issue for the backend?

**Comment by gavinking** [comment]
Yes
