### ISSUE TITLE
Prohibit concrete members of dynamic interfaces

### ISSUE THREAD

**Issue by gavinking** [ceylon/ceylon-spec#993]
Should we require that every member declared or inherited by a `dynamic` interface be `formal`? @corbinu @chochos

**Comment by chochos** [comment]
why was this reopened?

**Comment by gavinking** [comment]
@chochos Because you're both telling me I need to add additional restrictions for member classes.

**Comment by gavinking** [comment]
I'm inclined to simply disallow member classes for `dynamic` interfaces.

**Comment by gavinking** [comment]
> I'm inclined to simply disallow member classes for `dynamic` interfaces.

I went with that. Re-closing.

**Comment by chochos** [comment]
Yay!
