### ISSUE TITLE
sealed methods/attributes

### ISSUE THREAD

**Issue by gavinking** [ceylon/ceylon-spec#998]
Now that we have `sealed` classes and interfaces, I wonder if we could use the same annotation to prevent invocation of a `shared` member of a `shared` type in a `shared` package from outside the module.

Pros:

- It's _totally_ useful.

Cons:

- It's arguably an abuse of the semantics of `sealed`, which isn't really about visibility control, or at least it didn't start out that way.

**Comment by Mandritti** [comment]
Whatever this annotation is, it can't be called shared.  It can't be a kind of shared, it defies the specification  and tons  of compiler inference.  And letting it anywhere near  inheritance (not just refinement, inheritance) is oodles of pain.

Building on lucaswerkmeister's reasoning, if a function or value is visible but cannot be invoked, it is a strange step to get an error any later than Syntax on any naming of it.  The difference, I guess, is between resolving the reference, and invocation.  For functions and values, -every- resolution of the reference is for the purpose of invocation or evaluation, so this is exactly a visibility specifier there.  For a type declaration, visibility and access are different.
On that note, and for some further reasoning I've done, I am sure that 'sealed' is not the right word for this.  The IntentionRevealingName, if we're honest, is 'module' ('module-private').  [I believe it is worth serious rumination  whether  forcing  the  boilerplate  workaround for package-privacy  would fit better with Ceylon's  design goal  of  making source say  what it means.]

At the point where this  functionality  bumps  into the polymorphism for Ceylon question,  you might need the word 'sealed'  for that case anyway, separate from the  visibility issue of module-privacy.  e.g. If you put sealed on a member, you expect this to mean the member  can't be used but that it "resolves" to something. This has an intelligible sense on a default member  which would be totally outside  what the annotation actually did.

**Comment by gavinking** [comment]
This thought bubble was actually already superseded by #1128. Closing.
